export * from './cRYPTOPUNKS.service';
import { CRYPTOPUNKSService } from './cRYPTOPUNKS.service';
export * from './cURVEFINANCEETHEREUM.service';
import { CURVEFINANCEETHEREUMService } from './cURVEFINANCEETHEREUM.service';
export * from './metadata.service';
import { MetadataService } from './metadata.service';
export * from './sUSHISWAPV3ETHEREUM.service';
import { SUSHISWAPV3ETHEREUMService } from './sUSHISWAPV3ETHEREUM.service';
export * from './uNISWAPV2ETHEREUM.service';
import { UNISWAPV2ETHEREUMService } from './uNISWAPV2ETHEREUM.service';
export * from './uNISWAPV3ETHEREUM.service';
import { UNISWAPV3ETHEREUMService } from './uNISWAPV3ETHEREUM.service';
export const APIS = [CRYPTOPUNKSService, CURVEFINANCEETHEREUMService, MetadataService, SUSHISWAPV3ETHEREUMService, UNISWAPV2ETHEREUMService, UNISWAPV3ETHEREUMService];
