import typing_extensions

from openapi_client.paths import PathValues
from openapi_client.apis.paths.metadata_chains import MetadataChains
from openapi_client.apis.paths.metadata_chains_chain_id import MetadataChainsChainId
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_bids_current import V1DappsCryptopunksEthereumBidsCurrent
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_collection_daily_snapshots_current import V1DappsCryptopunksEthereumCollectionDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_collections_current import V1DappsCryptopunksEthereumCollectionsCurrent
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_data_sources_current import V1DappsCryptopunksEthereumDataSourcesCurrent
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_items_current import V1DappsCryptopunksEthereumItemsCurrent
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_marketplace_daily_snapshots_current import V1DappsCryptopunksEthereumMarketplaceDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_market_places_current import V1DappsCryptopunksEthereumMarketPlacesCurrent
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_trades_current import V1DappsCryptopunksEthereumTradesCurrent
from openapi_client.apis.paths.v1_dapps_cryptopunks_ethereum_users_current import V1DappsCryptopunksEthereumUsersCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_accounts_current import V1DappsCurveFinanceEthereumAccountsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_active_accounts_current import V1DappsCurveFinanceEthereumActiveAccountsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_deposits_current import V1DappsCurveFinanceEthereumDepositsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_dex_amm_protocols_current import V1DappsCurveFinanceEthereumDexAmmProtocolsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_financials_daily_snapshots_current import V1DappsCurveFinanceEthereumFinancialsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_liquidity_gauges_current import V1DappsCurveFinanceEthereumLiquidityGaugesCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_liquidity_pool_daily_snapshots_current import V1DappsCurveFinanceEthereumLiquidityPoolDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_liquidity_pools_current import V1DappsCurveFinanceEthereumLiquidityPoolsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_liquidity_pool_fees_current import V1DappsCurveFinanceEthereumLiquidityPoolFeesCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_liquidity_pool_hourly_snapshots_current import V1DappsCurveFinanceEthereumLiquidityPoolHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_lp_tokens_current import V1DappsCurveFinanceEthereumLpTokensCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_reward_tokens_current import V1DappsCurveFinanceEthereumRewardTokensCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_swaps_current import V1DappsCurveFinanceEthereumSwapsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_tokens_current import V1DappsCurveFinanceEthereumTokensCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_usage_metrics_daily_snapshots_current import V1DappsCurveFinanceEthereumUsageMetricsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_usage_metrics_hourly_snapshots_current import V1DappsCurveFinanceEthereumUsageMetricsHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_curve_finance_ethereum_withdraws_current import V1DappsCurveFinanceEthereumWithdrawsCurrent
from openapi_client.apis.paths.metadata_dapps import MetadataDapps
from openapi_client.apis.paths.metadata_dapps_dapp_id import MetadataDappsDappId
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_accounts_current import V1DappsPancakeswapV3EthereumAccountsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_active_accounts_current import V1DappsPancakeswapV3EthereumActiveAccountsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_deposits_current import V1DappsPancakeswapV3EthereumDepositsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_dex_amm_protocols_current import V1DappsPancakeswapV3EthereumDexAmmProtocolsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_financials_daily_snapshots_current import V1DappsPancakeswapV3EthereumFinancialsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_liquidity_pool_amounts_current import V1DappsPancakeswapV3EthereumLiquidityPoolAmountsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_liquidity_pool_daily_snapshots_current import V1DappsPancakeswapV3EthereumLiquidityPoolDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_liquidity_pools_current import V1DappsPancakeswapV3EthereumLiquidityPoolsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_liquidity_pool_fees_current import V1DappsPancakeswapV3EthereumLiquidityPoolFeesCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_liquidity_pool_hourly_snapshots_current import V1DappsPancakeswapV3EthereumLiquidityPoolHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_positions_current import V1DappsPancakeswapV3EthereumPositionsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_position_snapshots_current import V1DappsPancakeswapV3EthereumPositionSnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_reward_tokens_current import V1DappsPancakeswapV3EthereumRewardTokensCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_swaps_current import V1DappsPancakeswapV3EthereumSwapsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_tick_daily_snapshots_current import V1DappsPancakeswapV3EthereumTickDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_ticks_current import V1DappsPancakeswapV3EthereumTicksCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_tick_hourly_snapshots_current import V1DappsPancakeswapV3EthereumTickHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_tokens_current import V1DappsPancakeswapV3EthereumTokensCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_token_white_lists_current import V1DappsPancakeswapV3EthereumTokenWhiteListsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_token_white_list_symbols_current import V1DappsPancakeswapV3EthereumTokenWhiteListSymbolsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_usage_metrics_daily_snapshots_current import V1DappsPancakeswapV3EthereumUsageMetricsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_usage_metrics_hourly_snapshots_current import V1DappsPancakeswapV3EthereumUsageMetricsHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_pancakeswap_v3_ethereum_withdraws_current import V1DappsPancakeswapV3EthereumWithdrawsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_accounts_current import V1DappsSushiswapV3EthereumAccountsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_active_accounts_current import V1DappsSushiswapV3EthereumActiveAccountsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_deposits_current import V1DappsSushiswapV3EthereumDepositsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_dex_amm_protocols_current import V1DappsSushiswapV3EthereumDexAmmProtocolsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_financials_daily_snapshots_current import V1DappsSushiswapV3EthereumFinancialsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_liquidity_pool_amounts_current import V1DappsSushiswapV3EthereumLiquidityPoolAmountsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_liquidity_pool_daily_snapshots_current import V1DappsSushiswapV3EthereumLiquidityPoolDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_liquidity_pools_current import V1DappsSushiswapV3EthereumLiquidityPoolsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_liquidity_pool_fees_current import V1DappsSushiswapV3EthereumLiquidityPoolFeesCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_liquidity_pool_hourly_snapshots_current import V1DappsSushiswapV3EthereumLiquidityPoolHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_positions_current import V1DappsSushiswapV3EthereumPositionsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_position_snapshots_current import V1DappsSushiswapV3EthereumPositionSnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_reward_tokens_current import V1DappsSushiswapV3EthereumRewardTokensCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_swaps_current import V1DappsSushiswapV3EthereumSwapsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_tick_daily_snapshots_current import V1DappsSushiswapV3EthereumTickDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_ticks_current import V1DappsSushiswapV3EthereumTicksCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_tick_hourly_snapshots_current import V1DappsSushiswapV3EthereumTickHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_tokens_current import V1DappsSushiswapV3EthereumTokensCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_token_white_lists_current import V1DappsSushiswapV3EthereumTokenWhiteListsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_token_white_list_symbols_current import V1DappsSushiswapV3EthereumTokenWhiteListSymbolsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_usage_metrics_daily_snapshots_current import V1DappsSushiswapV3EthereumUsageMetricsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_usage_metrics_hourly_snapshots_current import V1DappsSushiswapV3EthereumUsageMetricsHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_sushiswap_v3_ethereum_withdraws_current import V1DappsSushiswapV3EthereumWithdrawsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_accounts_current import V1DappsUniswapV2EthereumAccountsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_active_accounts_current import V1DappsUniswapV2EthereumActiveAccountsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_deposits_current import V1DappsUniswapV2EthereumDepositsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_dex_amm_protocols_current import V1DappsUniswapV2EthereumDexAmmProtocolsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_financials_daily_snapshots_current import V1DappsUniswapV2EthereumFinancialsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_liquidity_pool_amounts_current import V1DappsUniswapV2EthereumLiquidityPoolAmountsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_liquidity_pool_daily_snapshots_current import V1DappsUniswapV2EthereumLiquidityPoolDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_liquidity_pools_current import V1DappsUniswapV2EthereumLiquidityPoolsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_liquidity_pool_fees_current import V1DappsUniswapV2EthereumLiquidityPoolFeesCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_liquidity_pool_hourly_snapshots_current import V1DappsUniswapV2EthereumLiquidityPoolHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_master_chef_address_to_pids_current import V1DappsUniswapV2EthereumMasterChefAddressToPidsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_master_chefs_current import V1DappsUniswapV2EthereumMasterChefsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_master_chef_rewarders_current import V1DappsUniswapV2EthereumMasterChefRewardersCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_master_chef_staking_pools_current import V1DappsUniswapV2EthereumMasterChefStakingPoolsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_rewarder_probes_current import V1DappsUniswapV2EthereumRewarderProbesCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_reward_tokens_current import V1DappsUniswapV2EthereumRewardTokensCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_swaps_current import V1DappsUniswapV2EthereumSwapsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_tokens_current import V1DappsUniswapV2EthereumTokensCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_token_white_lists_current import V1DappsUniswapV2EthereumTokenWhiteListsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_transfers_current import V1DappsUniswapV2EthereumTransfersCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_usage_metrics_daily_snapshots_current import V1DappsUniswapV2EthereumUsageMetricsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_usage_metrics_hourly_snapshots_current import V1DappsUniswapV2EthereumUsageMetricsHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v2_ethereum_withdraws_current import V1DappsUniswapV2EthereumWithdrawsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_accounts_current import V1DappsUniswapV3EthereumAccountsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_active_accounts_current import V1DappsUniswapV3EthereumActiveAccountsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_deposits_current import V1DappsUniswapV3EthereumDepositsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_dex_amm_protocols_current import V1DappsUniswapV3EthereumDexAmmProtocolsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_financials_daily_snapshots_current import V1DappsUniswapV3EthereumFinancialsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_liquidity_pool_amounts_current import V1DappsUniswapV3EthereumLiquidityPoolAmountsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_liquidity_pool_daily_snapshots_current import V1DappsUniswapV3EthereumLiquidityPoolDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_liquidity_pools_current import V1DappsUniswapV3EthereumLiquidityPoolsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_liquidity_pool_fees_current import V1DappsUniswapV3EthereumLiquidityPoolFeesCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_liquidity_pool_hourly_snapshots_current import V1DappsUniswapV3EthereumLiquidityPoolHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_positions_current import V1DappsUniswapV3EthereumPositionsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_position_snapshots_current import V1DappsUniswapV3EthereumPositionSnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_reward_tokens_current import V1DappsUniswapV3EthereumRewardTokensCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_swaps_current import V1DappsUniswapV3EthereumSwapsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_tick_daily_snapshots_current import V1DappsUniswapV3EthereumTickDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_ticks_current import V1DappsUniswapV3EthereumTicksCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_tick_hourly_snapshots_current import V1DappsUniswapV3EthereumTickHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_tokens_current import V1DappsUniswapV3EthereumTokensCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_token_white_lists_current import V1DappsUniswapV3EthereumTokenWhiteListsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_token_white_list_symbols_current import V1DappsUniswapV3EthereumTokenWhiteListSymbolsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_usage_metrics_daily_snapshots_current import V1DappsUniswapV3EthereumUsageMetricsDailySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_usage_metrics_hourly_snapshots_current import V1DappsUniswapV3EthereumUsageMetricsHourlySnapshotsCurrent
from openapi_client.apis.paths.v1_dapps_uniswap_v3_ethereum_withdraws_current import V1DappsUniswapV3EthereumWithdrawsCurrent

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.METADATA_CHAINS: MetadataChains,
        PathValues.METADATA_CHAINS_CHAIN_ID: MetadataChainsChainId,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_BIDS_CURRENT: V1DappsCryptopunksEthereumBidsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_COLLECTION_DAILY_SNAPSHOTS_CURRENT: V1DappsCryptopunksEthereumCollectionDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_COLLECTIONS_CURRENT: V1DappsCryptopunksEthereumCollectionsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_DATA_SOURCES_CURRENT: V1DappsCryptopunksEthereumDataSourcesCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_ITEMS_CURRENT: V1DappsCryptopunksEthereumItemsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_MARKETPLACE_DAILY_SNAPSHOTS_CURRENT: V1DappsCryptopunksEthereumMarketplaceDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_MARKET_PLACES_CURRENT: V1DappsCryptopunksEthereumMarketPlacesCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_TRADES_CURRENT: V1DappsCryptopunksEthereumTradesCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_USERS_CURRENT: V1DappsCryptopunksEthereumUsersCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_ACCOUNTS_CURRENT: V1DappsCurveFinanceEthereumAccountsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsCurveFinanceEthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_DEPOSITS_CURRENT: V1DappsCurveFinanceEthereumDepositsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsCurveFinanceEthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_GAUGES_CURRENT: V1DappsCurveFinanceEthereumLiquidityGaugesCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsCurveFinanceEthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsCurveFinanceEthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LP_TOKENS_CURRENT: V1DappsCurveFinanceEthereumLpTokensCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_REWARD_TOKENS_CURRENT: V1DappsCurveFinanceEthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_SWAPS_CURRENT: V1DappsCurveFinanceEthereumSwapsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_TOKENS_CURRENT: V1DappsCurveFinanceEthereumTokensCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_WITHDRAWS_CURRENT: V1DappsCurveFinanceEthereumWithdrawsCurrent,
        PathValues.METADATA_DAPPS: MetadataDapps,
        PathValues.METADATA_DAPPS_DAPP_ID: MetadataDappsDappId,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_ACCOUNTS_CURRENT: V1DappsPancakeswapV3EthereumAccountsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsPancakeswapV3EthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_DEPOSITS_CURRENT: V1DappsPancakeswapV3EthereumDepositsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsPancakeswapV3EthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOL_AMOUNTS_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolAmountsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_POSITIONS_CURRENT: V1DappsPancakeswapV3EthereumPositionsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_POSITION_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumPositionSnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_REWARD_TOKENS_CURRENT: V1DappsPancakeswapV3EthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_SWAPS_CURRENT: V1DappsPancakeswapV3EthereumSwapsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TICK_DAILY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumTickDailySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TICKS_CURRENT: V1DappsPancakeswapV3EthereumTicksCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TICK_HOURLY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumTickHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TOKENS_CURRENT: V1DappsPancakeswapV3EthereumTokensCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TOKEN_WHITE_LISTS_CURRENT: V1DappsPancakeswapV3EthereumTokenWhiteListsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TOKEN_WHITE_LIST_SYMBOLS_CURRENT: V1DappsPancakeswapV3EthereumTokenWhiteListSymbolsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_WITHDRAWS_CURRENT: V1DappsPancakeswapV3EthereumWithdrawsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_ACCOUNTS_CURRENT: V1DappsSushiswapV3EthereumAccountsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsSushiswapV3EthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_DEPOSITS_CURRENT: V1DappsSushiswapV3EthereumDepositsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsSushiswapV3EthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOL_AMOUNTS_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolAmountsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_POSITIONS_CURRENT: V1DappsSushiswapV3EthereumPositionsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_POSITION_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumPositionSnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_REWARD_TOKENS_CURRENT: V1DappsSushiswapV3EthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_SWAPS_CURRENT: V1DappsSushiswapV3EthereumSwapsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TICK_DAILY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumTickDailySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TICKS_CURRENT: V1DappsSushiswapV3EthereumTicksCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TICK_HOURLY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumTickHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TOKENS_CURRENT: V1DappsSushiswapV3EthereumTokensCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TOKEN_WHITE_LISTS_CURRENT: V1DappsSushiswapV3EthereumTokenWhiteListsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TOKEN_WHITE_LIST_SYMBOLS_CURRENT: V1DappsSushiswapV3EthereumTokenWhiteListSymbolsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_WITHDRAWS_CURRENT: V1DappsSushiswapV3EthereumWithdrawsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_ACCOUNTS_CURRENT: V1DappsUniswapV2EthereumAccountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsUniswapV2EthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_DEPOSITS_CURRENT: V1DappsUniswapV2EthereumDepositsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsUniswapV2EthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOL_AMOUNTS_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolAmountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_MASTER_CHEF_ADDRESS_TO_PIDS_CURRENT: V1DappsUniswapV2EthereumMasterChefAddressToPidsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_MASTER_CHEFS_CURRENT: V1DappsUniswapV2EthereumMasterChefsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_MASTER_CHEF_REWARDERS_CURRENT: V1DappsUniswapV2EthereumMasterChefRewardersCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_MASTER_CHEF_STAKING_POOLS_CURRENT: V1DappsUniswapV2EthereumMasterChefStakingPoolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_REWARDER_PROBES_CURRENT: V1DappsUniswapV2EthereumRewarderProbesCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_REWARD_TOKENS_CURRENT: V1DappsUniswapV2EthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_SWAPS_CURRENT: V1DappsUniswapV2EthereumSwapsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_TOKENS_CURRENT: V1DappsUniswapV2EthereumTokensCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_TOKEN_WHITE_LISTS_CURRENT: V1DappsUniswapV2EthereumTokenWhiteListsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_TRANSFERS_CURRENT: V1DappsUniswapV2EthereumTransfersCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_WITHDRAWS_CURRENT: V1DappsUniswapV2EthereumWithdrawsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_ACCOUNTS_CURRENT: V1DappsUniswapV3EthereumAccountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsUniswapV3EthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_DEPOSITS_CURRENT: V1DappsUniswapV3EthereumDepositsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsUniswapV3EthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOL_AMOUNTS_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolAmountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_POSITIONS_CURRENT: V1DappsUniswapV3EthereumPositionsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_POSITION_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumPositionSnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_REWARD_TOKENS_CURRENT: V1DappsUniswapV3EthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_SWAPS_CURRENT: V1DappsUniswapV3EthereumSwapsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TICK_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumTickDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TICKS_CURRENT: V1DappsUniswapV3EthereumTicksCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TICK_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumTickHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TOKENS_CURRENT: V1DappsUniswapV3EthereumTokensCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TOKEN_WHITE_LISTS_CURRENT: V1DappsUniswapV3EthereumTokenWhiteListsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TOKEN_WHITE_LIST_SYMBOLS_CURRENT: V1DappsUniswapV3EthereumTokenWhiteListSymbolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_WITHDRAWS_CURRENT: V1DappsUniswapV3EthereumWithdrawsCurrent,
    }
)

path_to_api = PathToApi(
    {
        PathValues.METADATA_CHAINS: MetadataChains,
        PathValues.METADATA_CHAINS_CHAIN_ID: MetadataChainsChainId,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_BIDS_CURRENT: V1DappsCryptopunksEthereumBidsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_COLLECTION_DAILY_SNAPSHOTS_CURRENT: V1DappsCryptopunksEthereumCollectionDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_COLLECTIONS_CURRENT: V1DappsCryptopunksEthereumCollectionsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_DATA_SOURCES_CURRENT: V1DappsCryptopunksEthereumDataSourcesCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_ITEMS_CURRENT: V1DappsCryptopunksEthereumItemsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_MARKETPLACE_DAILY_SNAPSHOTS_CURRENT: V1DappsCryptopunksEthereumMarketplaceDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_MARKET_PLACES_CURRENT: V1DappsCryptopunksEthereumMarketPlacesCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_TRADES_CURRENT: V1DappsCryptopunksEthereumTradesCurrent,
        PathValues.V1_DAPPS_CRYPTOPUNKSETHEREUM_USERS_CURRENT: V1DappsCryptopunksEthereumUsersCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_ACCOUNTS_CURRENT: V1DappsCurveFinanceEthereumAccountsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsCurveFinanceEthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_DEPOSITS_CURRENT: V1DappsCurveFinanceEthereumDepositsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsCurveFinanceEthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_GAUGES_CURRENT: V1DappsCurveFinanceEthereumLiquidityGaugesCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsCurveFinanceEthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsCurveFinanceEthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_LP_TOKENS_CURRENT: V1DappsCurveFinanceEthereumLpTokensCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_REWARD_TOKENS_CURRENT: V1DappsCurveFinanceEthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_SWAPS_CURRENT: V1DappsCurveFinanceEthereumSwapsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_TOKENS_CURRENT: V1DappsCurveFinanceEthereumTokensCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsCurveFinanceEthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_CURVEFINANCEETHEREUM_WITHDRAWS_CURRENT: V1DappsCurveFinanceEthereumWithdrawsCurrent,
        PathValues.METADATA_DAPPS: MetadataDapps,
        PathValues.METADATA_DAPPS_DAPP_ID: MetadataDappsDappId,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_ACCOUNTS_CURRENT: V1DappsPancakeswapV3EthereumAccountsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsPancakeswapV3EthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_DEPOSITS_CURRENT: V1DappsPancakeswapV3EthereumDepositsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsPancakeswapV3EthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOL_AMOUNTS_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolAmountsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_POSITIONS_CURRENT: V1DappsPancakeswapV3EthereumPositionsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_POSITION_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumPositionSnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_REWARD_TOKENS_CURRENT: V1DappsPancakeswapV3EthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_SWAPS_CURRENT: V1DappsPancakeswapV3EthereumSwapsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TICK_DAILY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumTickDailySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TICKS_CURRENT: V1DappsPancakeswapV3EthereumTicksCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TICK_HOURLY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumTickHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TOKENS_CURRENT: V1DappsPancakeswapV3EthereumTokensCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TOKEN_WHITE_LISTS_CURRENT: V1DappsPancakeswapV3EthereumTokenWhiteListsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_TOKEN_WHITE_LIST_SYMBOLS_CURRENT: V1DappsPancakeswapV3EthereumTokenWhiteListSymbolsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsPancakeswapV3EthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_PANCAKESWAPV3ETHEREUM_WITHDRAWS_CURRENT: V1DappsPancakeswapV3EthereumWithdrawsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_ACCOUNTS_CURRENT: V1DappsSushiswapV3EthereumAccountsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsSushiswapV3EthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_DEPOSITS_CURRENT: V1DappsSushiswapV3EthereumDepositsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsSushiswapV3EthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOL_AMOUNTS_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolAmountsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_POSITIONS_CURRENT: V1DappsSushiswapV3EthereumPositionsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_POSITION_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumPositionSnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_REWARD_TOKENS_CURRENT: V1DappsSushiswapV3EthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_SWAPS_CURRENT: V1DappsSushiswapV3EthereumSwapsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TICK_DAILY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumTickDailySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TICKS_CURRENT: V1DappsSushiswapV3EthereumTicksCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TICK_HOURLY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumTickHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TOKENS_CURRENT: V1DappsSushiswapV3EthereumTokensCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TOKEN_WHITE_LISTS_CURRENT: V1DappsSushiswapV3EthereumTokenWhiteListsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_TOKEN_WHITE_LIST_SYMBOLS_CURRENT: V1DappsSushiswapV3EthereumTokenWhiteListSymbolsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsSushiswapV3EthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_SUSHISWAPV3ETHEREUM_WITHDRAWS_CURRENT: V1DappsSushiswapV3EthereumWithdrawsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_ACCOUNTS_CURRENT: V1DappsUniswapV2EthereumAccountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsUniswapV2EthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_DEPOSITS_CURRENT: V1DappsUniswapV2EthereumDepositsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsUniswapV2EthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOL_AMOUNTS_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolAmountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_MASTER_CHEF_ADDRESS_TO_PIDS_CURRENT: V1DappsUniswapV2EthereumMasterChefAddressToPidsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_MASTER_CHEFS_CURRENT: V1DappsUniswapV2EthereumMasterChefsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_MASTER_CHEF_REWARDERS_CURRENT: V1DappsUniswapV2EthereumMasterChefRewardersCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_MASTER_CHEF_STAKING_POOLS_CURRENT: V1DappsUniswapV2EthereumMasterChefStakingPoolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_REWARDER_PROBES_CURRENT: V1DappsUniswapV2EthereumRewarderProbesCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_REWARD_TOKENS_CURRENT: V1DappsUniswapV2EthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_SWAPS_CURRENT: V1DappsUniswapV2EthereumSwapsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_TOKENS_CURRENT: V1DappsUniswapV2EthereumTokensCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_TOKEN_WHITE_LISTS_CURRENT: V1DappsUniswapV2EthereumTokenWhiteListsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_TRANSFERS_CURRENT: V1DappsUniswapV2EthereumTransfersCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV2EthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV2ETHEREUM_WITHDRAWS_CURRENT: V1DappsUniswapV2EthereumWithdrawsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_ACCOUNTS_CURRENT: V1DappsUniswapV3EthereumAccountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_ACTIVE_ACCOUNTS_CURRENT: V1DappsUniswapV3EthereumActiveAccountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_DEPOSITS_CURRENT: V1DappsUniswapV3EthereumDepositsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_DEX_AMM_PROTOCOLS_CURRENT: V1DappsUniswapV3EthereumDexAmmProtocolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_FINANCIALS_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumFinancialsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOL_AMOUNTS_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolAmountsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOL_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOLS_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOL_FEES_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolFeesCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_LIQUIDITY_POOL_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumLiquidityPoolHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_POSITIONS_CURRENT: V1DappsUniswapV3EthereumPositionsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_POSITION_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumPositionSnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_REWARD_TOKENS_CURRENT: V1DappsUniswapV3EthereumRewardTokensCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_SWAPS_CURRENT: V1DappsUniswapV3EthereumSwapsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TICK_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumTickDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TICKS_CURRENT: V1DappsUniswapV3EthereumTicksCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TICK_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumTickHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TOKENS_CURRENT: V1DappsUniswapV3EthereumTokensCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TOKEN_WHITE_LISTS_CURRENT: V1DappsUniswapV3EthereumTokenWhiteListsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_TOKEN_WHITE_LIST_SYMBOLS_CURRENT: V1DappsUniswapV3EthereumTokenWhiteListSymbolsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_USAGE_METRICS_DAILY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumUsageMetricsDailySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_USAGE_METRICS_HOURLY_SNAPSHOTS_CURRENT: V1DappsUniswapV3EthereumUsageMetricsHourlySnapshotsCurrent,
        PathValues.V1_DAPPS_UNISWAPV3ETHEREUM_WITHDRAWS_CURRENT: V1DappsUniswapV3EthereumWithdrawsCurrent,
    }
)
