#
# On Chain Dapps - REST API
#  This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             
# Version: v1
# Contact: support@coinapi.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CURVEFINANCEETHEREUMLiquidityPoolDTO' {
    Context 'CURVEFINANCEETHEREUMLiquidityPoolDTO' {
        It 'Initialize-CURVEFINANCEETHEREUMLiquidityPoolDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-CURVEFINANCEETHEREUMLiquidityPoolDTO -EntryTime "TEST_VALUE" -RecvTime "TEST_VALUE" -BlockNumber "TEST_VALUE" -Vid "TEST_VALUE" -Id "TEST_VALUE" -Protocol "TEST_VALUE" -Name "TEST_VALUE" -Symbol "TEST_VALUE" -InputTokens "TEST_VALUE" -InputTokensOrdered "TEST_VALUE" -OutputToken "TEST_VALUE" -RewardTokens "TEST_VALUE" -Fees "TEST_VALUE" -IsSingleSided "TEST_VALUE" -CreatedTimestamp "TEST_VALUE" -CreatedBlockNumber "TEST_VALUE" -TotalValueLockedUsd "TEST_VALUE" -CumulativeSupplySideRevenueUsd "TEST_VALUE" -CumulativeProtocolSideRevenueUsd "TEST_VALUE" -CumulativeTotalRevenueUsd "TEST_VALUE" -CumulativeVolumeUsd "TEST_VALUE" -InputTokenBalances "TEST_VALUE" -InputTokenWeights "TEST_VALUE" -OutputTokenSupply "TEST_VALUE" -OutputTokenPriceUsd "TEST_VALUE" -StakedOutputTokenAmount "TEST_VALUE" -RewardTokenEmissionsAmount "TEST_VALUE" -RewardTokenEmissionsUsd "TEST_VALUE" -RegistryAddress "TEST_VALUE" -GaugeAddress "TEST_VALUE" -EvaluatedAsk "TEST_VALUE"
            #$NewObject | Should -BeOfType CURVEFINANCEETHEREUMLiquidityPoolDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
