#' Create a new CURVEFINANCEETHEREUMDexAmmProtocolDTO
#'
#' @description
#' Entity for calculating daily/hourly active users.
#'
#' @docType class
#' @title CURVEFINANCEETHEREUMDexAmmProtocolDTO
#' @description CURVEFINANCEETHEREUMDexAmmProtocolDTO Class
#' @format An \code{R6Class} generator object
#' @field entry_time  character [optional]
#' @field recv_time  character [optional]
#' @field block_number Number of block in which entity was recorded. integer [optional]
#' @field block_range  character [optional]
#' @field id Smart contract address of the protocol's main contract (Factory, Registry, etc) character [optional]
#' @field name Name of the protocol, including version. character [optional]
#' @field slug Slug of protocol, including version. character [optional]
#' @field schema_version Version of the subgraph schema, in SemVer format (e.g. 1.0.0) character [optional]
#' @field subgraph_version Version of the subgraph implementation, in SemVer format (e.g. 1.0.0) character [optional]
#' @field methodology_version Version of the methodology used to compute metrics, loosely based on SemVer format (e.g. 1.0.0) character [optional]
#' @field total_value_locked_usd Current TVL (Total Value Locked) of the entire protocol character [optional]
#' @field protocol_controlled_value_usd Current PCV (Protocol Controlled Value). Only relevant for protocols with PCV. character [optional]
#' @field cumulative_volume_usd All historical volume in USD character [optional]
#' @field cumulative_supply_side_revenue_usd Revenue claimed by suppliers to the protocol. LPs on DEXs (e.g. 0.25\% of the swap fee in Sushiswap). Depositors on Lending Protocols. NFT sellers on OpenSea. character [optional]
#' @field cumulative_protocol_side_revenue_usd Gross revenue for the protocol (revenue claimed by protocol). Examples: AMM protocol fee (Sushi’s 0.05\%). OpenSea 10\% sell fee. character [optional]
#' @field cumulative_total_revenue_usd All revenue generated by the protocol. e.g. 0.30\% of swap fee in Sushiswap, all yield generated by Yearn. character [optional]
#' @field cumulative_unique_users Number of cumulative unique users integer [optional]
#' @field total_pool_count Total number of pools integer [optional]
#' @field pool_ids All pools that belong to this protocol list(character) [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CURVEFINANCEETHEREUMDexAmmProtocolDTO <- R6::R6Class(
  "CURVEFINANCEETHEREUMDexAmmProtocolDTO",
  public = list(
    `entry_time` = NULL,
    `recv_time` = NULL,
    `block_number` = NULL,
    `block_range` = NULL,
    `id` = NULL,
    `name` = NULL,
    `slug` = NULL,
    `schema_version` = NULL,
    `subgraph_version` = NULL,
    `methodology_version` = NULL,
    `total_value_locked_usd` = NULL,
    `protocol_controlled_value_usd` = NULL,
    `cumulative_volume_usd` = NULL,
    `cumulative_supply_side_revenue_usd` = NULL,
    `cumulative_protocol_side_revenue_usd` = NULL,
    `cumulative_total_revenue_usd` = NULL,
    `cumulative_unique_users` = NULL,
    `total_pool_count` = NULL,
    `pool_ids` = NULL,
    #' Initialize a new CURVEFINANCEETHEREUMDexAmmProtocolDTO class.
    #'
    #' @description
    #' Initialize a new CURVEFINANCEETHEREUMDexAmmProtocolDTO class.
    #'
    #' @param entry_time entry_time
    #' @param recv_time recv_time
    #' @param block_number Number of block in which entity was recorded.
    #' @param block_range 
    #' @param id Smart contract address of the protocol's main contract (Factory, Registry, etc)
    #' @param name Name of the protocol, including version.
    #' @param slug Slug of protocol, including version.
    #' @param schema_version Version of the subgraph schema, in SemVer format (e.g. 1.0.0)
    #' @param subgraph_version Version of the subgraph implementation, in SemVer format (e.g. 1.0.0)
    #' @param methodology_version Version of the methodology used to compute metrics, loosely based on SemVer format (e.g. 1.0.0)
    #' @param total_value_locked_usd Current TVL (Total Value Locked) of the entire protocol
    #' @param protocol_controlled_value_usd Current PCV (Protocol Controlled Value). Only relevant for protocols with PCV.
    #' @param cumulative_volume_usd All historical volume in USD
    #' @param cumulative_supply_side_revenue_usd Revenue claimed by suppliers to the protocol. LPs on DEXs (e.g. 0.25\% of the swap fee in Sushiswap). Depositors on Lending Protocols. NFT sellers on OpenSea.
    #' @param cumulative_protocol_side_revenue_usd Gross revenue for the protocol (revenue claimed by protocol). Examples: AMM protocol fee (Sushi’s 0.05\%). OpenSea 10\% sell fee.
    #' @param cumulative_total_revenue_usd All revenue generated by the protocol. e.g. 0.30\% of swap fee in Sushiswap, all yield generated by Yearn.
    #' @param cumulative_unique_users Number of cumulative unique users
    #' @param total_pool_count Total number of pools
    #' @param pool_ids All pools that belong to this protocol
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(`entry_time` = NULL, `recv_time` = NULL, `block_number` = NULL, `block_range` = NULL, `id` = NULL, `name` = NULL, `slug` = NULL, `schema_version` = NULL, `subgraph_version` = NULL, `methodology_version` = NULL, `total_value_locked_usd` = NULL, `protocol_controlled_value_usd` = NULL, `cumulative_volume_usd` = NULL, `cumulative_supply_side_revenue_usd` = NULL, `cumulative_protocol_side_revenue_usd` = NULL, `cumulative_total_revenue_usd` = NULL, `cumulative_unique_users` = NULL, `total_pool_count` = NULL, `pool_ids` = NULL, ...) {
      if (!is.null(`entry_time`)) {
        if (!is.character(`entry_time`)) {
          stop(paste("Error! Invalid data for `entry_time`. Must be a string:", `entry_time`))
        }
        self$`entry_time` <- `entry_time`
      }
      if (!is.null(`recv_time`)) {
        if (!is.character(`recv_time`)) {
          stop(paste("Error! Invalid data for `recv_time`. Must be a string:", `recv_time`))
        }
        self$`recv_time` <- `recv_time`
      }
      if (!is.null(`block_number`)) {
        if (!(is.numeric(`block_number`) && length(`block_number`) == 1)) {
          stop(paste("Error! Invalid data for `block_number`. Must be an integer:", `block_number`))
        }
        self$`block_number` <- `block_number`
      }
      if (!is.null(`block_range`)) {
        if (!(is.character(`block_range`) && length(`block_range`) == 1)) {
          stop(paste("Error! Invalid data for `block_range`. Must be a string:", `block_range`))
        }
        self$`block_range` <- `block_range`
      }
      if (!is.null(`id`)) {
        if (!(is.character(`id`) && length(`id`) == 1)) {
          stop(paste("Error! Invalid data for `id`. Must be a string:", `id`))
        }
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        if (!(is.character(`name`) && length(`name`) == 1)) {
          stop(paste("Error! Invalid data for `name`. Must be a string:", `name`))
        }
        self$`name` <- `name`
      }
      if (!is.null(`slug`)) {
        if (!(is.character(`slug`) && length(`slug`) == 1)) {
          stop(paste("Error! Invalid data for `slug`. Must be a string:", `slug`))
        }
        self$`slug` <- `slug`
      }
      if (!is.null(`schema_version`)) {
        if (!(is.character(`schema_version`) && length(`schema_version`) == 1)) {
          stop(paste("Error! Invalid data for `schema_version`. Must be a string:", `schema_version`))
        }
        self$`schema_version` <- `schema_version`
      }
      if (!is.null(`subgraph_version`)) {
        if (!(is.character(`subgraph_version`) && length(`subgraph_version`) == 1)) {
          stop(paste("Error! Invalid data for `subgraph_version`. Must be a string:", `subgraph_version`))
        }
        self$`subgraph_version` <- `subgraph_version`
      }
      if (!is.null(`methodology_version`)) {
        if (!(is.character(`methodology_version`) && length(`methodology_version`) == 1)) {
          stop(paste("Error! Invalid data for `methodology_version`. Must be a string:", `methodology_version`))
        }
        self$`methodology_version` <- `methodology_version`
      }
      if (!is.null(`total_value_locked_usd`)) {
        if (!(is.character(`total_value_locked_usd`) && length(`total_value_locked_usd`) == 1)) {
          stop(paste("Error! Invalid data for `total_value_locked_usd`. Must be a string:", `total_value_locked_usd`))
        }
        self$`total_value_locked_usd` <- `total_value_locked_usd`
      }
      if (!is.null(`protocol_controlled_value_usd`)) {
        if (!(is.character(`protocol_controlled_value_usd`) && length(`protocol_controlled_value_usd`) == 1)) {
          stop(paste("Error! Invalid data for `protocol_controlled_value_usd`. Must be a string:", `protocol_controlled_value_usd`))
        }
        self$`protocol_controlled_value_usd` <- `protocol_controlled_value_usd`
      }
      if (!is.null(`cumulative_volume_usd`)) {
        if (!(is.character(`cumulative_volume_usd`) && length(`cumulative_volume_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_volume_usd`. Must be a string:", `cumulative_volume_usd`))
        }
        self$`cumulative_volume_usd` <- `cumulative_volume_usd`
      }
      if (!is.null(`cumulative_supply_side_revenue_usd`)) {
        if (!(is.character(`cumulative_supply_side_revenue_usd`) && length(`cumulative_supply_side_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_supply_side_revenue_usd`. Must be a string:", `cumulative_supply_side_revenue_usd`))
        }
        self$`cumulative_supply_side_revenue_usd` <- `cumulative_supply_side_revenue_usd`
      }
      if (!is.null(`cumulative_protocol_side_revenue_usd`)) {
        if (!(is.character(`cumulative_protocol_side_revenue_usd`) && length(`cumulative_protocol_side_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_protocol_side_revenue_usd`. Must be a string:", `cumulative_protocol_side_revenue_usd`))
        }
        self$`cumulative_protocol_side_revenue_usd` <- `cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(`cumulative_total_revenue_usd`)) {
        if (!(is.character(`cumulative_total_revenue_usd`) && length(`cumulative_total_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_total_revenue_usd`. Must be a string:", `cumulative_total_revenue_usd`))
        }
        self$`cumulative_total_revenue_usd` <- `cumulative_total_revenue_usd`
      }
      if (!is.null(`cumulative_unique_users`)) {
        if (!(is.numeric(`cumulative_unique_users`) && length(`cumulative_unique_users`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_unique_users`. Must be an integer:", `cumulative_unique_users`))
        }
        self$`cumulative_unique_users` <- `cumulative_unique_users`
      }
      if (!is.null(`total_pool_count`)) {
        if (!(is.numeric(`total_pool_count`) && length(`total_pool_count`) == 1)) {
          stop(paste("Error! Invalid data for `total_pool_count`. Must be an integer:", `total_pool_count`))
        }
        self$`total_pool_count` <- `total_pool_count`
      }
      if (!is.null(`pool_ids`)) {
        stopifnot(is.vector(`pool_ids`), length(`pool_ids`) != 0)
        sapply(`pool_ids`, function(x) stopifnot(is.character(x)))
        self$`pool_ids` <- `pool_ids`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return CURVEFINANCEETHEREUMDexAmmProtocolDTO in JSON format
    #' @export
    toJSON = function() {
      CURVEFINANCEETHEREUMDexAmmProtocolDTOObject <- list()
      if (!is.null(self$`entry_time`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["entry_time"]] <-
          self$`entry_time`
      }
      if (!is.null(self$`recv_time`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["recv_time"]] <-
          self$`recv_time`
      }
      if (!is.null(self$`block_number`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["block_number"]] <-
          self$`block_number`
      }
      if (!is.null(self$`block_range`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["block_range"]] <-
          self$`block_range`
      }
      if (!is.null(self$`id`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["id"]] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["name"]] <-
          self$`name`
      }
      if (!is.null(self$`slug`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["slug"]] <-
          self$`slug`
      }
      if (!is.null(self$`schema_version`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["schema_version"]] <-
          self$`schema_version`
      }
      if (!is.null(self$`subgraph_version`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["subgraph_version"]] <-
          self$`subgraph_version`
      }
      if (!is.null(self$`methodology_version`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["methodology_version"]] <-
          self$`methodology_version`
      }
      if (!is.null(self$`total_value_locked_usd`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["total_value_locked_usd"]] <-
          self$`total_value_locked_usd`
      }
      if (!is.null(self$`protocol_controlled_value_usd`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["protocol_controlled_value_usd"]] <-
          self$`protocol_controlled_value_usd`
      }
      if (!is.null(self$`cumulative_volume_usd`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["cumulative_volume_usd"]] <-
          self$`cumulative_volume_usd`
      }
      if (!is.null(self$`cumulative_supply_side_revenue_usd`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["cumulative_supply_side_revenue_usd"]] <-
          self$`cumulative_supply_side_revenue_usd`
      }
      if (!is.null(self$`cumulative_protocol_side_revenue_usd`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["cumulative_protocol_side_revenue_usd"]] <-
          self$`cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(self$`cumulative_total_revenue_usd`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["cumulative_total_revenue_usd"]] <-
          self$`cumulative_total_revenue_usd`
      }
      if (!is.null(self$`cumulative_unique_users`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["cumulative_unique_users"]] <-
          self$`cumulative_unique_users`
      }
      if (!is.null(self$`total_pool_count`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["total_pool_count"]] <-
          self$`total_pool_count`
      }
      if (!is.null(self$`pool_ids`)) {
        CURVEFINANCEETHEREUMDexAmmProtocolDTOObject[["pool_ids"]] <-
          self$`pool_ids`
      }
      CURVEFINANCEETHEREUMDexAmmProtocolDTOObject
    },
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMDexAmmProtocolDTO
    #'
    #' @description
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMDexAmmProtocolDTO
    #'
    #' @param input_json the JSON input
    #' @return the instance of CURVEFINANCEETHEREUMDexAmmProtocolDTO
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`entry_time`)) {
        self$`entry_time` <- this_object$`entry_time`
      }
      if (!is.null(this_object$`recv_time`)) {
        self$`recv_time` <- this_object$`recv_time`
      }
      if (!is.null(this_object$`block_number`)) {
        self$`block_number` <- this_object$`block_number`
      }
      if (!is.null(this_object$`block_range`)) {
        self$`block_range` <- this_object$`block_range`
      }
      if (!is.null(this_object$`id`)) {
        self$`id` <- this_object$`id`
      }
      if (!is.null(this_object$`name`)) {
        self$`name` <- this_object$`name`
      }
      if (!is.null(this_object$`slug`)) {
        self$`slug` <- this_object$`slug`
      }
      if (!is.null(this_object$`schema_version`)) {
        self$`schema_version` <- this_object$`schema_version`
      }
      if (!is.null(this_object$`subgraph_version`)) {
        self$`subgraph_version` <- this_object$`subgraph_version`
      }
      if (!is.null(this_object$`methodology_version`)) {
        self$`methodology_version` <- this_object$`methodology_version`
      }
      if (!is.null(this_object$`total_value_locked_usd`)) {
        self$`total_value_locked_usd` <- this_object$`total_value_locked_usd`
      }
      if (!is.null(this_object$`protocol_controlled_value_usd`)) {
        self$`protocol_controlled_value_usd` <- this_object$`protocol_controlled_value_usd`
      }
      if (!is.null(this_object$`cumulative_volume_usd`)) {
        self$`cumulative_volume_usd` <- this_object$`cumulative_volume_usd`
      }
      if (!is.null(this_object$`cumulative_supply_side_revenue_usd`)) {
        self$`cumulative_supply_side_revenue_usd` <- this_object$`cumulative_supply_side_revenue_usd`
      }
      if (!is.null(this_object$`cumulative_protocol_side_revenue_usd`)) {
        self$`cumulative_protocol_side_revenue_usd` <- this_object$`cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(this_object$`cumulative_total_revenue_usd`)) {
        self$`cumulative_total_revenue_usd` <- this_object$`cumulative_total_revenue_usd`
      }
      if (!is.null(this_object$`cumulative_unique_users`)) {
        self$`cumulative_unique_users` <- this_object$`cumulative_unique_users`
      }
      if (!is.null(this_object$`total_pool_count`)) {
        self$`total_pool_count` <- this_object$`total_pool_count`
      }
      if (!is.null(this_object$`pool_ids`)) {
        self$`pool_ids` <- ApiClient$new()$deserializeObj(this_object$`pool_ids`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return CURVEFINANCEETHEREUMDexAmmProtocolDTO in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`entry_time`)) {
          sprintf(
          '"entry_time":
            "%s"
                    ',
          self$`entry_time`
          )
        },
        if (!is.null(self$`recv_time`)) {
          sprintf(
          '"recv_time":
            "%s"
                    ',
          self$`recv_time`
          )
        },
        if (!is.null(self$`block_number`)) {
          sprintf(
          '"block_number":
            %d
                    ',
          self$`block_number`
          )
        },
        if (!is.null(self$`block_range`)) {
          sprintf(
          '"block_range":
            "%s"
                    ',
          self$`block_range`
          )
        },
        if (!is.null(self$`id`)) {
          sprintf(
          '"id":
            "%s"
                    ',
          self$`id`
          )
        },
        if (!is.null(self$`name`)) {
          sprintf(
          '"name":
            "%s"
                    ',
          self$`name`
          )
        },
        if (!is.null(self$`slug`)) {
          sprintf(
          '"slug":
            "%s"
                    ',
          self$`slug`
          )
        },
        if (!is.null(self$`schema_version`)) {
          sprintf(
          '"schema_version":
            "%s"
                    ',
          self$`schema_version`
          )
        },
        if (!is.null(self$`subgraph_version`)) {
          sprintf(
          '"subgraph_version":
            "%s"
                    ',
          self$`subgraph_version`
          )
        },
        if (!is.null(self$`methodology_version`)) {
          sprintf(
          '"methodology_version":
            "%s"
                    ',
          self$`methodology_version`
          )
        },
        if (!is.null(self$`total_value_locked_usd`)) {
          sprintf(
          '"total_value_locked_usd":
            "%s"
                    ',
          self$`total_value_locked_usd`
          )
        },
        if (!is.null(self$`protocol_controlled_value_usd`)) {
          sprintf(
          '"protocol_controlled_value_usd":
            "%s"
                    ',
          self$`protocol_controlled_value_usd`
          )
        },
        if (!is.null(self$`cumulative_volume_usd`)) {
          sprintf(
          '"cumulative_volume_usd":
            "%s"
                    ',
          self$`cumulative_volume_usd`
          )
        },
        if (!is.null(self$`cumulative_supply_side_revenue_usd`)) {
          sprintf(
          '"cumulative_supply_side_revenue_usd":
            "%s"
                    ',
          self$`cumulative_supply_side_revenue_usd`
          )
        },
        if (!is.null(self$`cumulative_protocol_side_revenue_usd`)) {
          sprintf(
          '"cumulative_protocol_side_revenue_usd":
            "%s"
                    ',
          self$`cumulative_protocol_side_revenue_usd`
          )
        },
        if (!is.null(self$`cumulative_total_revenue_usd`)) {
          sprintf(
          '"cumulative_total_revenue_usd":
            "%s"
                    ',
          self$`cumulative_total_revenue_usd`
          )
        },
        if (!is.null(self$`cumulative_unique_users`)) {
          sprintf(
          '"cumulative_unique_users":
            %d
                    ',
          self$`cumulative_unique_users`
          )
        },
        if (!is.null(self$`total_pool_count`)) {
          sprintf(
          '"total_pool_count":
            %d
                    ',
          self$`total_pool_count`
          )
        },
        if (!is.null(self$`pool_ids`)) {
          sprintf(
          '"pool_ids":
             [%s]
          ',
          paste(unlist(lapply(self$`pool_ids`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      json_string <- as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMDexAmmProtocolDTO
    #'
    #' @description
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMDexAmmProtocolDTO
    #'
    #' @param input_json the JSON input
    #' @return the instance of CURVEFINANCEETHEREUMDexAmmProtocolDTO
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`entry_time` <- this_object$`entry_time`
      self$`recv_time` <- this_object$`recv_time`
      self$`block_number` <- this_object$`block_number`
      self$`block_range` <- this_object$`block_range`
      self$`id` <- this_object$`id`
      self$`name` <- this_object$`name`
      self$`slug` <- this_object$`slug`
      self$`schema_version` <- this_object$`schema_version`
      self$`subgraph_version` <- this_object$`subgraph_version`
      self$`methodology_version` <- this_object$`methodology_version`
      self$`total_value_locked_usd` <- this_object$`total_value_locked_usd`
      self$`protocol_controlled_value_usd` <- this_object$`protocol_controlled_value_usd`
      self$`cumulative_volume_usd` <- this_object$`cumulative_volume_usd`
      self$`cumulative_supply_side_revenue_usd` <- this_object$`cumulative_supply_side_revenue_usd`
      self$`cumulative_protocol_side_revenue_usd` <- this_object$`cumulative_protocol_side_revenue_usd`
      self$`cumulative_total_revenue_usd` <- this_object$`cumulative_total_revenue_usd`
      self$`cumulative_unique_users` <- this_object$`cumulative_unique_users`
      self$`total_pool_count` <- this_object$`total_pool_count`
      self$`pool_ids` <- ApiClient$new()$deserializeObj(this_object$`pool_ids`, "array[character]", loadNamespace("openapi"))
      self
    },
    #' Validate JSON input with respect to CURVEFINANCEETHEREUMDexAmmProtocolDTO
    #'
    #' @description
    #' Validate JSON input with respect to CURVEFINANCEETHEREUMDexAmmProtocolDTO and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of CURVEFINANCEETHEREUMDexAmmProtocolDTO
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      invalid_fields
    },
    #' Print the object
    #'
    #' @description
    #' Print the object
    #'
    #' @export
    print = function() {
      print(jsonlite::prettify(self$toJSONString()))
      invisible(self)
    }
  ),
  # Lock the class to prevent modifications to the method or field
  lock_class = TRUE
)
## Uncomment below to unlock the class to allow modifications of the method or field
# CURVEFINANCEETHEREUMDexAmmProtocolDTO$unlock()
#
## Below is an example to define the print function
# CURVEFINANCEETHEREUMDexAmmProtocolDTO$set("public", "print", function(...) {
#   print(jsonlite::prettify(self$toJSONString()))
#   invisible(self)
# })
## Uncomment below to lock the class to prevent modifications to the method or field
# CURVEFINANCEETHEREUMDexAmmProtocolDTO$lock()

