#' Create a new CURVEFINANCEETHEREUMLiquidityPoolDTO
#'
#' @description
#' 
#'
#' @docType class
#' @title CURVEFINANCEETHEREUMLiquidityPoolDTO
#' @description CURVEFINANCEETHEREUMLiquidityPoolDTO Class
#' @format An \code{R6Class} generator object
#' @field entry_time  character [optional]
#' @field recv_time  character [optional]
#' @field block_number Number of block in which entity was recorded. integer [optional]
#' @field vid  integer [optional]
#' @field id Smart contract address of the pool character [optional]
#' @field protocol The protocol this pool belongs to character [optional]
#' @field name Name of liquidity pool (e.g. Curve.fi DAI/USDC/USDT) character [optional]
#' @field symbol Symbol of liquidity pool (e.g. 3CRV) character [optional]
#' @field input_tokens Tokens that need to be deposited to take a position in protocol. e.g. WETH and USDC to deposit into the WETH-USDC pool. Array to account for multi-asset pools like Curve and Balancer list(character) [optional]
#' @field input_tokens_ordered inputTokens in native (contract) order list(character) [optional]
#' @field output_token Token that is minted to track ownership of position in protocol character [optional]
#' @field reward_tokens Aditional tokens that are given as reward for position in a protocol, usually in liquidity mining programs. e.g. SUSHI in the Onsen program, MATIC for Aave Polygon list(character) [optional]
#' @field fees Fees per trade incurred to the user. Should include all fees that apply to a pool (e.g. Curve has a trading fee AND an admin fee, which is a portion of the trading fee. Uniswap only has a trading fee and no protocol fee.) list(character) [optional]
#' @field is_single_sided Whether this pool is single-sided (e.g. Bancor, Platypus's Alternative Pool). The specifics of the implementation depends on the protocol. character [optional]
#' @field created_timestamp Creation timestamp character [optional]
#' @field created_block_number Creation block number character [optional]
#' @field total_value_locked_usd Current TVL (Total Value Locked) of this pool in USD character [optional]
#' @field cumulative_supply_side_revenue_usd All revenue generated by the liquidity pool, accrued to the supply side. character [optional]
#' @field cumulative_protocol_side_revenue_usd All revenue generated by the liquidity pool, accrued to the protocol. character [optional]
#' @field cumulative_total_revenue_usd All revenue generated by the liquidity pool. character [optional]
#' @field cumulative_volume_usd All historical trade volume occurred in this pool, in USD character [optional]
#' @field input_token_balances Amount of input tokens in the pool. The ordering should be the same as the pool's `inputTokens` field. list(character) [optional]
#' @field input_token_weights Weights of input tokens in the liquidity pool in percentage values. list(character) [optional]
#' @field output_token_supply Total supply of output token. character [optional]
#' @field output_token_price_usd Price per share of output token in USD character [optional]
#' @field staked_output_token_amount Total supply of output tokens that are staked (usually in the MasterChef contract). Used to calculate reward APY. character [optional]
#' @field reward_token_emissions_amount Per-block reward token emission as of the current block normalized to a day, in token's native amount. list(character) [optional]
#' @field reward_token_emissions_usd Per-block reward token emission as of the current block normalized to a day, in USD value. list(character) [optional]
#' @field registry_address Registry that deployed this pool character [optional]
#' @field gauge_address Liquidity Gauge assocaited with this pool character [optional]
#' @field evaluated_ask  numeric [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CURVEFINANCEETHEREUMLiquidityPoolDTO <- R6::R6Class(
  "CURVEFINANCEETHEREUMLiquidityPoolDTO",
  public = list(
    `entry_time` = NULL,
    `recv_time` = NULL,
    `block_number` = NULL,
    `vid` = NULL,
    `id` = NULL,
    `protocol` = NULL,
    `name` = NULL,
    `symbol` = NULL,
    `input_tokens` = NULL,
    `input_tokens_ordered` = NULL,
    `output_token` = NULL,
    `reward_tokens` = NULL,
    `fees` = NULL,
    `is_single_sided` = NULL,
    `created_timestamp` = NULL,
    `created_block_number` = NULL,
    `total_value_locked_usd` = NULL,
    `cumulative_supply_side_revenue_usd` = NULL,
    `cumulative_protocol_side_revenue_usd` = NULL,
    `cumulative_total_revenue_usd` = NULL,
    `cumulative_volume_usd` = NULL,
    `input_token_balances` = NULL,
    `input_token_weights` = NULL,
    `output_token_supply` = NULL,
    `output_token_price_usd` = NULL,
    `staked_output_token_amount` = NULL,
    `reward_token_emissions_amount` = NULL,
    `reward_token_emissions_usd` = NULL,
    `registry_address` = NULL,
    `gauge_address` = NULL,
    `evaluated_ask` = NULL,
    #' Initialize a new CURVEFINANCEETHEREUMLiquidityPoolDTO class.
    #'
    #' @description
    #' Initialize a new CURVEFINANCEETHEREUMLiquidityPoolDTO class.
    #'
    #' @param entry_time entry_time
    #' @param recv_time recv_time
    #' @param block_number Number of block in which entity was recorded.
    #' @param vid 
    #' @param id Smart contract address of the pool
    #' @param protocol The protocol this pool belongs to
    #' @param name Name of liquidity pool (e.g. Curve.fi DAI/USDC/USDT)
    #' @param symbol Symbol of liquidity pool (e.g. 3CRV)
    #' @param input_tokens Tokens that need to be deposited to take a position in protocol. e.g. WETH and USDC to deposit into the WETH-USDC pool. Array to account for multi-asset pools like Curve and Balancer
    #' @param input_tokens_ordered inputTokens in native (contract) order
    #' @param output_token Token that is minted to track ownership of position in protocol
    #' @param reward_tokens Aditional tokens that are given as reward for position in a protocol, usually in liquidity mining programs. e.g. SUSHI in the Onsen program, MATIC for Aave Polygon
    #' @param fees Fees per trade incurred to the user. Should include all fees that apply to a pool (e.g. Curve has a trading fee AND an admin fee, which is a portion of the trading fee. Uniswap only has a trading fee and no protocol fee.)
    #' @param is_single_sided Whether this pool is single-sided (e.g. Bancor, Platypus's Alternative Pool). The specifics of the implementation depends on the protocol.
    #' @param created_timestamp Creation timestamp
    #' @param created_block_number Creation block number
    #' @param total_value_locked_usd Current TVL (Total Value Locked) of this pool in USD
    #' @param cumulative_supply_side_revenue_usd All revenue generated by the liquidity pool, accrued to the supply side.
    #' @param cumulative_protocol_side_revenue_usd All revenue generated by the liquidity pool, accrued to the protocol.
    #' @param cumulative_total_revenue_usd All revenue generated by the liquidity pool.
    #' @param cumulative_volume_usd All historical trade volume occurred in this pool, in USD
    #' @param input_token_balances Amount of input tokens in the pool. The ordering should be the same as the pool's `inputTokens` field.
    #' @param input_token_weights Weights of input tokens in the liquidity pool in percentage values.
    #' @param output_token_supply Total supply of output token.
    #' @param output_token_price_usd Price per share of output token in USD
    #' @param staked_output_token_amount Total supply of output tokens that are staked (usually in the MasterChef contract). Used to calculate reward APY.
    #' @param reward_token_emissions_amount Per-block reward token emission as of the current block normalized to a day, in token's native amount.
    #' @param reward_token_emissions_usd Per-block reward token emission as of the current block normalized to a day, in USD value.
    #' @param registry_address Registry that deployed this pool
    #' @param gauge_address Liquidity Gauge assocaited with this pool
    #' @param evaluated_ask evaluated_ask
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(`entry_time` = NULL, `recv_time` = NULL, `block_number` = NULL, `vid` = NULL, `id` = NULL, `protocol` = NULL, `name` = NULL, `symbol` = NULL, `input_tokens` = NULL, `input_tokens_ordered` = NULL, `output_token` = NULL, `reward_tokens` = NULL, `fees` = NULL, `is_single_sided` = NULL, `created_timestamp` = NULL, `created_block_number` = NULL, `total_value_locked_usd` = NULL, `cumulative_supply_side_revenue_usd` = NULL, `cumulative_protocol_side_revenue_usd` = NULL, `cumulative_total_revenue_usd` = NULL, `cumulative_volume_usd` = NULL, `input_token_balances` = NULL, `input_token_weights` = NULL, `output_token_supply` = NULL, `output_token_price_usd` = NULL, `staked_output_token_amount` = NULL, `reward_token_emissions_amount` = NULL, `reward_token_emissions_usd` = NULL, `registry_address` = NULL, `gauge_address` = NULL, `evaluated_ask` = NULL, ...) {
      if (!is.null(`entry_time`)) {
        if (!is.character(`entry_time`)) {
          stop(paste("Error! Invalid data for `entry_time`. Must be a string:", `entry_time`))
        }
        self$`entry_time` <- `entry_time`
      }
      if (!is.null(`recv_time`)) {
        if (!is.character(`recv_time`)) {
          stop(paste("Error! Invalid data for `recv_time`. Must be a string:", `recv_time`))
        }
        self$`recv_time` <- `recv_time`
      }
      if (!is.null(`block_number`)) {
        if (!(is.numeric(`block_number`) && length(`block_number`) == 1)) {
          stop(paste("Error! Invalid data for `block_number`. Must be an integer:", `block_number`))
        }
        self$`block_number` <- `block_number`
      }
      if (!is.null(`vid`)) {
        if (!(is.numeric(`vid`) && length(`vid`) == 1)) {
          stop(paste("Error! Invalid data for `vid`. Must be an integer:", `vid`))
        }
        self$`vid` <- `vid`
      }
      if (!is.null(`id`)) {
        if (!(is.character(`id`) && length(`id`) == 1)) {
          stop(paste("Error! Invalid data for `id`. Must be a string:", `id`))
        }
        self$`id` <- `id`
      }
      if (!is.null(`protocol`)) {
        if (!(is.character(`protocol`) && length(`protocol`) == 1)) {
          stop(paste("Error! Invalid data for `protocol`. Must be a string:", `protocol`))
        }
        self$`protocol` <- `protocol`
      }
      if (!is.null(`name`)) {
        if (!(is.character(`name`) && length(`name`) == 1)) {
          stop(paste("Error! Invalid data for `name`. Must be a string:", `name`))
        }
        self$`name` <- `name`
      }
      if (!is.null(`symbol`)) {
        if (!(is.character(`symbol`) && length(`symbol`) == 1)) {
          stop(paste("Error! Invalid data for `symbol`. Must be a string:", `symbol`))
        }
        self$`symbol` <- `symbol`
      }
      if (!is.null(`input_tokens`)) {
        stopifnot(is.vector(`input_tokens`), length(`input_tokens`) != 0)
        sapply(`input_tokens`, function(x) stopifnot(is.character(x)))
        self$`input_tokens` <- `input_tokens`
      }
      if (!is.null(`input_tokens_ordered`)) {
        stopifnot(is.vector(`input_tokens_ordered`), length(`input_tokens_ordered`) != 0)
        sapply(`input_tokens_ordered`, function(x) stopifnot(is.character(x)))
        self$`input_tokens_ordered` <- `input_tokens_ordered`
      }
      if (!is.null(`output_token`)) {
        if (!(is.character(`output_token`) && length(`output_token`) == 1)) {
          stop(paste("Error! Invalid data for `output_token`. Must be a string:", `output_token`))
        }
        self$`output_token` <- `output_token`
      }
      if (!is.null(`reward_tokens`)) {
        stopifnot(is.vector(`reward_tokens`), length(`reward_tokens`) != 0)
        sapply(`reward_tokens`, function(x) stopifnot(is.character(x)))
        self$`reward_tokens` <- `reward_tokens`
      }
      if (!is.null(`fees`)) {
        stopifnot(is.vector(`fees`), length(`fees`) != 0)
        sapply(`fees`, function(x) stopifnot(is.character(x)))
        self$`fees` <- `fees`
      }
      if (!is.null(`is_single_sided`)) {
        if (!(is.logical(`is_single_sided`) && length(`is_single_sided`) == 1)) {
          stop(paste("Error! Invalid data for `is_single_sided`. Must be a boolean:", `is_single_sided`))
        }
        self$`is_single_sided` <- `is_single_sided`
      }
      if (!is.null(`created_timestamp`)) {
        if (!(is.character(`created_timestamp`) && length(`created_timestamp`) == 1)) {
          stop(paste("Error! Invalid data for `created_timestamp`. Must be a string:", `created_timestamp`))
        }
        self$`created_timestamp` <- `created_timestamp`
      }
      if (!is.null(`created_block_number`)) {
        if (!(is.character(`created_block_number`) && length(`created_block_number`) == 1)) {
          stop(paste("Error! Invalid data for `created_block_number`. Must be a string:", `created_block_number`))
        }
        self$`created_block_number` <- `created_block_number`
      }
      if (!is.null(`total_value_locked_usd`)) {
        if (!(is.character(`total_value_locked_usd`) && length(`total_value_locked_usd`) == 1)) {
          stop(paste("Error! Invalid data for `total_value_locked_usd`. Must be a string:", `total_value_locked_usd`))
        }
        self$`total_value_locked_usd` <- `total_value_locked_usd`
      }
      if (!is.null(`cumulative_supply_side_revenue_usd`)) {
        if (!(is.character(`cumulative_supply_side_revenue_usd`) && length(`cumulative_supply_side_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_supply_side_revenue_usd`. Must be a string:", `cumulative_supply_side_revenue_usd`))
        }
        self$`cumulative_supply_side_revenue_usd` <- `cumulative_supply_side_revenue_usd`
      }
      if (!is.null(`cumulative_protocol_side_revenue_usd`)) {
        if (!(is.character(`cumulative_protocol_side_revenue_usd`) && length(`cumulative_protocol_side_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_protocol_side_revenue_usd`. Must be a string:", `cumulative_protocol_side_revenue_usd`))
        }
        self$`cumulative_protocol_side_revenue_usd` <- `cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(`cumulative_total_revenue_usd`)) {
        if (!(is.character(`cumulative_total_revenue_usd`) && length(`cumulative_total_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_total_revenue_usd`. Must be a string:", `cumulative_total_revenue_usd`))
        }
        self$`cumulative_total_revenue_usd` <- `cumulative_total_revenue_usd`
      }
      if (!is.null(`cumulative_volume_usd`)) {
        if (!(is.character(`cumulative_volume_usd`) && length(`cumulative_volume_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_volume_usd`. Must be a string:", `cumulative_volume_usd`))
        }
        self$`cumulative_volume_usd` <- `cumulative_volume_usd`
      }
      if (!is.null(`input_token_balances`)) {
        stopifnot(is.vector(`input_token_balances`), length(`input_token_balances`) != 0)
        sapply(`input_token_balances`, function(x) stopifnot(is.character(x)))
        self$`input_token_balances` <- `input_token_balances`
      }
      if (!is.null(`input_token_weights`)) {
        stopifnot(is.vector(`input_token_weights`), length(`input_token_weights`) != 0)
        sapply(`input_token_weights`, function(x) stopifnot(is.character(x)))
        self$`input_token_weights` <- `input_token_weights`
      }
      if (!is.null(`output_token_supply`)) {
        if (!(is.character(`output_token_supply`) && length(`output_token_supply`) == 1)) {
          stop(paste("Error! Invalid data for `output_token_supply`. Must be a string:", `output_token_supply`))
        }
        self$`output_token_supply` <- `output_token_supply`
      }
      if (!is.null(`output_token_price_usd`)) {
        if (!(is.character(`output_token_price_usd`) && length(`output_token_price_usd`) == 1)) {
          stop(paste("Error! Invalid data for `output_token_price_usd`. Must be a string:", `output_token_price_usd`))
        }
        self$`output_token_price_usd` <- `output_token_price_usd`
      }
      if (!is.null(`staked_output_token_amount`)) {
        if (!(is.character(`staked_output_token_amount`) && length(`staked_output_token_amount`) == 1)) {
          stop(paste("Error! Invalid data for `staked_output_token_amount`. Must be a string:", `staked_output_token_amount`))
        }
        self$`staked_output_token_amount` <- `staked_output_token_amount`
      }
      if (!is.null(`reward_token_emissions_amount`)) {
        stopifnot(is.vector(`reward_token_emissions_amount`), length(`reward_token_emissions_amount`) != 0)
        sapply(`reward_token_emissions_amount`, function(x) stopifnot(is.character(x)))
        self$`reward_token_emissions_amount` <- `reward_token_emissions_amount`
      }
      if (!is.null(`reward_token_emissions_usd`)) {
        stopifnot(is.vector(`reward_token_emissions_usd`), length(`reward_token_emissions_usd`) != 0)
        sapply(`reward_token_emissions_usd`, function(x) stopifnot(is.character(x)))
        self$`reward_token_emissions_usd` <- `reward_token_emissions_usd`
      }
      if (!is.null(`registry_address`)) {
        if (!(is.character(`registry_address`) && length(`registry_address`) == 1)) {
          stop(paste("Error! Invalid data for `registry_address`. Must be a string:", `registry_address`))
        }
        self$`registry_address` <- `registry_address`
      }
      if (!is.null(`gauge_address`)) {
        if (!(is.character(`gauge_address`) && length(`gauge_address`) == 1)) {
          stop(paste("Error! Invalid data for `gauge_address`. Must be a string:", `gauge_address`))
        }
        self$`gauge_address` <- `gauge_address`
      }
      if (!is.null(`evaluated_ask`)) {
        if (!(is.numeric(`evaluated_ask`) && length(`evaluated_ask`) == 1)) {
          stop(paste("Error! Invalid data for `evaluated_ask`. Must be a number:", `evaluated_ask`))
        }
        self$`evaluated_ask` <- `evaluated_ask`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return CURVEFINANCEETHEREUMLiquidityPoolDTO in JSON format
    #' @export
    toJSON = function() {
      CURVEFINANCEETHEREUMLiquidityPoolDTOObject <- list()
      if (!is.null(self$`entry_time`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["entry_time"]] <-
          self$`entry_time`
      }
      if (!is.null(self$`recv_time`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["recv_time"]] <-
          self$`recv_time`
      }
      if (!is.null(self$`block_number`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["block_number"]] <-
          self$`block_number`
      }
      if (!is.null(self$`vid`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["vid"]] <-
          self$`vid`
      }
      if (!is.null(self$`id`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["id"]] <-
          self$`id`
      }
      if (!is.null(self$`protocol`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["protocol"]] <-
          self$`protocol`
      }
      if (!is.null(self$`name`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["name"]] <-
          self$`name`
      }
      if (!is.null(self$`symbol`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["symbol"]] <-
          self$`symbol`
      }
      if (!is.null(self$`input_tokens`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["input_tokens"]] <-
          self$`input_tokens`
      }
      if (!is.null(self$`input_tokens_ordered`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["input_tokens_ordered"]] <-
          self$`input_tokens_ordered`
      }
      if (!is.null(self$`output_token`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["output_token"]] <-
          self$`output_token`
      }
      if (!is.null(self$`reward_tokens`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["reward_tokens"]] <-
          self$`reward_tokens`
      }
      if (!is.null(self$`fees`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["fees"]] <-
          self$`fees`
      }
      if (!is.null(self$`is_single_sided`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["is_single_sided"]] <-
          self$`is_single_sided`
      }
      if (!is.null(self$`created_timestamp`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["created_timestamp"]] <-
          self$`created_timestamp`
      }
      if (!is.null(self$`created_block_number`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["created_block_number"]] <-
          self$`created_block_number`
      }
      if (!is.null(self$`total_value_locked_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["total_value_locked_usd"]] <-
          self$`total_value_locked_usd`
      }
      if (!is.null(self$`cumulative_supply_side_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["cumulative_supply_side_revenue_usd"]] <-
          self$`cumulative_supply_side_revenue_usd`
      }
      if (!is.null(self$`cumulative_protocol_side_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["cumulative_protocol_side_revenue_usd"]] <-
          self$`cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(self$`cumulative_total_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["cumulative_total_revenue_usd"]] <-
          self$`cumulative_total_revenue_usd`
      }
      if (!is.null(self$`cumulative_volume_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["cumulative_volume_usd"]] <-
          self$`cumulative_volume_usd`
      }
      if (!is.null(self$`input_token_balances`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["input_token_balances"]] <-
          self$`input_token_balances`
      }
      if (!is.null(self$`input_token_weights`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["input_token_weights"]] <-
          self$`input_token_weights`
      }
      if (!is.null(self$`output_token_supply`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["output_token_supply"]] <-
          self$`output_token_supply`
      }
      if (!is.null(self$`output_token_price_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["output_token_price_usd"]] <-
          self$`output_token_price_usd`
      }
      if (!is.null(self$`staked_output_token_amount`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["staked_output_token_amount"]] <-
          self$`staked_output_token_amount`
      }
      if (!is.null(self$`reward_token_emissions_amount`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["reward_token_emissions_amount"]] <-
          self$`reward_token_emissions_amount`
      }
      if (!is.null(self$`reward_token_emissions_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["reward_token_emissions_usd"]] <-
          self$`reward_token_emissions_usd`
      }
      if (!is.null(self$`registry_address`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["registry_address"]] <-
          self$`registry_address`
      }
      if (!is.null(self$`gauge_address`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["gauge_address"]] <-
          self$`gauge_address`
      }
      if (!is.null(self$`evaluated_ask`)) {
        CURVEFINANCEETHEREUMLiquidityPoolDTOObject[["evaluated_ask"]] <-
          self$`evaluated_ask`
      }
      CURVEFINANCEETHEREUMLiquidityPoolDTOObject
    },
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMLiquidityPoolDTO
    #'
    #' @description
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMLiquidityPoolDTO
    #'
    #' @param input_json the JSON input
    #' @return the instance of CURVEFINANCEETHEREUMLiquidityPoolDTO
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`entry_time`)) {
        self$`entry_time` <- this_object$`entry_time`
      }
      if (!is.null(this_object$`recv_time`)) {
        self$`recv_time` <- this_object$`recv_time`
      }
      if (!is.null(this_object$`block_number`)) {
        self$`block_number` <- this_object$`block_number`
      }
      if (!is.null(this_object$`vid`)) {
        self$`vid` <- this_object$`vid`
      }
      if (!is.null(this_object$`id`)) {
        self$`id` <- this_object$`id`
      }
      if (!is.null(this_object$`protocol`)) {
        self$`protocol` <- this_object$`protocol`
      }
      if (!is.null(this_object$`name`)) {
        self$`name` <- this_object$`name`
      }
      if (!is.null(this_object$`symbol`)) {
        self$`symbol` <- this_object$`symbol`
      }
      if (!is.null(this_object$`input_tokens`)) {
        self$`input_tokens` <- ApiClient$new()$deserializeObj(this_object$`input_tokens`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`input_tokens_ordered`)) {
        self$`input_tokens_ordered` <- ApiClient$new()$deserializeObj(this_object$`input_tokens_ordered`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`output_token`)) {
        self$`output_token` <- this_object$`output_token`
      }
      if (!is.null(this_object$`reward_tokens`)) {
        self$`reward_tokens` <- ApiClient$new()$deserializeObj(this_object$`reward_tokens`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`fees`)) {
        self$`fees` <- ApiClient$new()$deserializeObj(this_object$`fees`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`is_single_sided`)) {
        self$`is_single_sided` <- this_object$`is_single_sided`
      }
      if (!is.null(this_object$`created_timestamp`)) {
        self$`created_timestamp` <- this_object$`created_timestamp`
      }
      if (!is.null(this_object$`created_block_number`)) {
        self$`created_block_number` <- this_object$`created_block_number`
      }
      if (!is.null(this_object$`total_value_locked_usd`)) {
        self$`total_value_locked_usd` <- this_object$`total_value_locked_usd`
      }
      if (!is.null(this_object$`cumulative_supply_side_revenue_usd`)) {
        self$`cumulative_supply_side_revenue_usd` <- this_object$`cumulative_supply_side_revenue_usd`
      }
      if (!is.null(this_object$`cumulative_protocol_side_revenue_usd`)) {
        self$`cumulative_protocol_side_revenue_usd` <- this_object$`cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(this_object$`cumulative_total_revenue_usd`)) {
        self$`cumulative_total_revenue_usd` <- this_object$`cumulative_total_revenue_usd`
      }
      if (!is.null(this_object$`cumulative_volume_usd`)) {
        self$`cumulative_volume_usd` <- this_object$`cumulative_volume_usd`
      }
      if (!is.null(this_object$`input_token_balances`)) {
        self$`input_token_balances` <- ApiClient$new()$deserializeObj(this_object$`input_token_balances`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`input_token_weights`)) {
        self$`input_token_weights` <- ApiClient$new()$deserializeObj(this_object$`input_token_weights`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`output_token_supply`)) {
        self$`output_token_supply` <- this_object$`output_token_supply`
      }
      if (!is.null(this_object$`output_token_price_usd`)) {
        self$`output_token_price_usd` <- this_object$`output_token_price_usd`
      }
      if (!is.null(this_object$`staked_output_token_amount`)) {
        self$`staked_output_token_amount` <- this_object$`staked_output_token_amount`
      }
      if (!is.null(this_object$`reward_token_emissions_amount`)) {
        self$`reward_token_emissions_amount` <- ApiClient$new()$deserializeObj(this_object$`reward_token_emissions_amount`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`reward_token_emissions_usd`)) {
        self$`reward_token_emissions_usd` <- ApiClient$new()$deserializeObj(this_object$`reward_token_emissions_usd`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`registry_address`)) {
        self$`registry_address` <- this_object$`registry_address`
      }
      if (!is.null(this_object$`gauge_address`)) {
        self$`gauge_address` <- this_object$`gauge_address`
      }
      if (!is.null(this_object$`evaluated_ask`)) {
        self$`evaluated_ask` <- this_object$`evaluated_ask`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return CURVEFINANCEETHEREUMLiquidityPoolDTO in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`entry_time`)) {
          sprintf(
          '"entry_time":
            "%s"
                    ',
          self$`entry_time`
          )
        },
        if (!is.null(self$`recv_time`)) {
          sprintf(
          '"recv_time":
            "%s"
                    ',
          self$`recv_time`
          )
        },
        if (!is.null(self$`block_number`)) {
          sprintf(
          '"block_number":
            %d
                    ',
          self$`block_number`
          )
        },
        if (!is.null(self$`vid`)) {
          sprintf(
          '"vid":
            %d
                    ',
          self$`vid`
          )
        },
        if (!is.null(self$`id`)) {
          sprintf(
          '"id":
            "%s"
                    ',
          self$`id`
          )
        },
        if (!is.null(self$`protocol`)) {
          sprintf(
          '"protocol":
            "%s"
                    ',
          self$`protocol`
          )
        },
        if (!is.null(self$`name`)) {
          sprintf(
          '"name":
            "%s"
                    ',
          self$`name`
          )
        },
        if (!is.null(self$`symbol`)) {
          sprintf(
          '"symbol":
            "%s"
                    ',
          self$`symbol`
          )
        },
        if (!is.null(self$`input_tokens`)) {
          sprintf(
          '"input_tokens":
             [%s]
          ',
          paste(unlist(lapply(self$`input_tokens`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`input_tokens_ordered`)) {
          sprintf(
          '"input_tokens_ordered":
             [%s]
          ',
          paste(unlist(lapply(self$`input_tokens_ordered`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`output_token`)) {
          sprintf(
          '"output_token":
            "%s"
                    ',
          self$`output_token`
          )
        },
        if (!is.null(self$`reward_tokens`)) {
          sprintf(
          '"reward_tokens":
             [%s]
          ',
          paste(unlist(lapply(self$`reward_tokens`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`fees`)) {
          sprintf(
          '"fees":
             [%s]
          ',
          paste(unlist(lapply(self$`fees`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`is_single_sided`)) {
          sprintf(
          '"is_single_sided":
            %s
                    ',
          tolower(self$`is_single_sided`)
          )
        },
        if (!is.null(self$`created_timestamp`)) {
          sprintf(
          '"created_timestamp":
            "%s"
                    ',
          self$`created_timestamp`
          )
        },
        if (!is.null(self$`created_block_number`)) {
          sprintf(
          '"created_block_number":
            "%s"
                    ',
          self$`created_block_number`
          )
        },
        if (!is.null(self$`total_value_locked_usd`)) {
          sprintf(
          '"total_value_locked_usd":
            "%s"
                    ',
          self$`total_value_locked_usd`
          )
        },
        if (!is.null(self$`cumulative_supply_side_revenue_usd`)) {
          sprintf(
          '"cumulative_supply_side_revenue_usd":
            "%s"
                    ',
          self$`cumulative_supply_side_revenue_usd`
          )
        },
        if (!is.null(self$`cumulative_protocol_side_revenue_usd`)) {
          sprintf(
          '"cumulative_protocol_side_revenue_usd":
            "%s"
                    ',
          self$`cumulative_protocol_side_revenue_usd`
          )
        },
        if (!is.null(self$`cumulative_total_revenue_usd`)) {
          sprintf(
          '"cumulative_total_revenue_usd":
            "%s"
                    ',
          self$`cumulative_total_revenue_usd`
          )
        },
        if (!is.null(self$`cumulative_volume_usd`)) {
          sprintf(
          '"cumulative_volume_usd":
            "%s"
                    ',
          self$`cumulative_volume_usd`
          )
        },
        if (!is.null(self$`input_token_balances`)) {
          sprintf(
          '"input_token_balances":
             [%s]
          ',
          paste(unlist(lapply(self$`input_token_balances`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`input_token_weights`)) {
          sprintf(
          '"input_token_weights":
             [%s]
          ',
          paste(unlist(lapply(self$`input_token_weights`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`output_token_supply`)) {
          sprintf(
          '"output_token_supply":
            "%s"
                    ',
          self$`output_token_supply`
          )
        },
        if (!is.null(self$`output_token_price_usd`)) {
          sprintf(
          '"output_token_price_usd":
            "%s"
                    ',
          self$`output_token_price_usd`
          )
        },
        if (!is.null(self$`staked_output_token_amount`)) {
          sprintf(
          '"staked_output_token_amount":
            "%s"
                    ',
          self$`staked_output_token_amount`
          )
        },
        if (!is.null(self$`reward_token_emissions_amount`)) {
          sprintf(
          '"reward_token_emissions_amount":
             [%s]
          ',
          paste(unlist(lapply(self$`reward_token_emissions_amount`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`reward_token_emissions_usd`)) {
          sprintf(
          '"reward_token_emissions_usd":
             [%s]
          ',
          paste(unlist(lapply(self$`reward_token_emissions_usd`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`registry_address`)) {
          sprintf(
          '"registry_address":
            "%s"
                    ',
          self$`registry_address`
          )
        },
        if (!is.null(self$`gauge_address`)) {
          sprintf(
          '"gauge_address":
            "%s"
                    ',
          self$`gauge_address`
          )
        },
        if (!is.null(self$`evaluated_ask`)) {
          sprintf(
          '"evaluated_ask":
            %d
                    ',
          self$`evaluated_ask`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      json_string <- as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMLiquidityPoolDTO
    #'
    #' @description
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMLiquidityPoolDTO
    #'
    #' @param input_json the JSON input
    #' @return the instance of CURVEFINANCEETHEREUMLiquidityPoolDTO
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`entry_time` <- this_object$`entry_time`
      self$`recv_time` <- this_object$`recv_time`
      self$`block_number` <- this_object$`block_number`
      self$`vid` <- this_object$`vid`
      self$`id` <- this_object$`id`
      self$`protocol` <- this_object$`protocol`
      self$`name` <- this_object$`name`
      self$`symbol` <- this_object$`symbol`
      self$`input_tokens` <- ApiClient$new()$deserializeObj(this_object$`input_tokens`, "array[character]", loadNamespace("openapi"))
      self$`input_tokens_ordered` <- ApiClient$new()$deserializeObj(this_object$`input_tokens_ordered`, "array[character]", loadNamespace("openapi"))
      self$`output_token` <- this_object$`output_token`
      self$`reward_tokens` <- ApiClient$new()$deserializeObj(this_object$`reward_tokens`, "array[character]", loadNamespace("openapi"))
      self$`fees` <- ApiClient$new()$deserializeObj(this_object$`fees`, "array[character]", loadNamespace("openapi"))
      self$`is_single_sided` <- this_object$`is_single_sided`
      self$`created_timestamp` <- this_object$`created_timestamp`
      self$`created_block_number` <- this_object$`created_block_number`
      self$`total_value_locked_usd` <- this_object$`total_value_locked_usd`
      self$`cumulative_supply_side_revenue_usd` <- this_object$`cumulative_supply_side_revenue_usd`
      self$`cumulative_protocol_side_revenue_usd` <- this_object$`cumulative_protocol_side_revenue_usd`
      self$`cumulative_total_revenue_usd` <- this_object$`cumulative_total_revenue_usd`
      self$`cumulative_volume_usd` <- this_object$`cumulative_volume_usd`
      self$`input_token_balances` <- ApiClient$new()$deserializeObj(this_object$`input_token_balances`, "array[character]", loadNamespace("openapi"))
      self$`input_token_weights` <- ApiClient$new()$deserializeObj(this_object$`input_token_weights`, "array[character]", loadNamespace("openapi"))
      self$`output_token_supply` <- this_object$`output_token_supply`
      self$`output_token_price_usd` <- this_object$`output_token_price_usd`
      self$`staked_output_token_amount` <- this_object$`staked_output_token_amount`
      self$`reward_token_emissions_amount` <- ApiClient$new()$deserializeObj(this_object$`reward_token_emissions_amount`, "array[character]", loadNamespace("openapi"))
      self$`reward_token_emissions_usd` <- ApiClient$new()$deserializeObj(this_object$`reward_token_emissions_usd`, "array[character]", loadNamespace("openapi"))
      self$`registry_address` <- this_object$`registry_address`
      self$`gauge_address` <- this_object$`gauge_address`
      self$`evaluated_ask` <- this_object$`evaluated_ask`
      self
    },
    #' Validate JSON input with respect to CURVEFINANCEETHEREUMLiquidityPoolDTO
    #'
    #' @description
    #' Validate JSON input with respect to CURVEFINANCEETHEREUMLiquidityPoolDTO and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of CURVEFINANCEETHEREUMLiquidityPoolDTO
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      invalid_fields
    },
    #' Print the object
    #'
    #' @description
    #' Print the object
    #'
    #' @export
    print = function() {
      print(jsonlite::prettify(self$toJSONString()))
      invisible(self)
    }
  ),
  # Lock the class to prevent modifications to the method or field
  lock_class = TRUE
)
## Uncomment below to unlock the class to allow modifications of the method or field
# CURVEFINANCEETHEREUMLiquidityPoolDTO$unlock()
#
## Below is an example to define the print function
# CURVEFINANCEETHEREUMLiquidityPoolDTO$set("public", "print", function(...) {
#   print(jsonlite::prettify(self$toJSONString()))
#   invisible(self)
# })
## Uncomment below to lock the class to prevent modifications to the method or field
# CURVEFINANCEETHEREUMLiquidityPoolDTO$lock()

