#' Create a new CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
#'
#' @description
#' 
#'
#' @docType class
#' @title CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
#' @description CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO Class
#' @format An \code{R6Class} generator object
#' @field entry_time  character [optional]
#' @field recv_time  character [optional]
#' @field block_number Number of block in which entity was recorded. integer [optional]
#' @field block_range  character [optional]
#' @field id (smart contract address of the pool)-(# of hours since unix epoch time) character [optional]
#' @field protocol The protocol this snapshot belongs to character [optional]
#' @field pool The pool this snapshot belongs to character [optional]
#' @field timestamp Timestamp of this snapshot character [optional]
#' @field total_value_locked_usd Current TVL (Total Value Locked) of this pool character [optional]
#' @field cumulative_supply_side_revenue_usd All revenue generated by the liquidity pool, accrued to the supply side. character [optional]
#' @field hourly_supply_side_revenue_usd Hourly revenue generated by the liquidity pool, accrued to the supply side. character [optional]
#' @field cumulative_protocol_side_revenue_usd All revenue generated by the liquidity pool, accrued to the protocol. character [optional]
#' @field hourly_protocol_side_revenue_usd Hourly revenue generated by the liquidity pool, accrued to the protocol. character [optional]
#' @field cumulative_total_revenue_usd All revenue generated by the liquidity pool. character [optional]
#' @field hourly_total_revenue_usd Hourly revenue generated by the liquidity pool. character [optional]
#' @field hourly_volume_usd All trade volume occurred in a given hour, in USD character [optional]
#' @field hourly_volume_by_token_amount All trade volume occurred in a given hour for a specific input token, in native amount. The ordering should be the same as the pool's 'inputTokens' field. list(character) [optional]
#' @field hourly_volume_by_token_usd All trade volume occurred in a given hour for a specific input token, in USD. The ordering should be the same as the pool's 'inputTokens' field. list(character) [optional]
#' @field cumulative_volume_usd All historical trade volume occurred in this pool, in USD character [optional]
#' @field input_token_balances Amount of input tokens in the pool. The ordering should be the same as the pool's 'inputTokens' field. list(character) [optional]
#' @field input_token_weights Weights of input tokens in the liquidity pool in percentage values. For example, 50/50 for Uniswap pools, 48.2/51.8 for a Curve pool, 10/10/80 for a Balancer pool list(character) [optional]
#' @field output_token_supply Total supply of output token. Note that certain DEXes don't have an output token (e.g. Bancor) character [optional]
#' @field output_token_price_usd Price per share of output token in USD character [optional]
#' @field staked_output_token_amount Total supply of output tokens that are staked (usually in the MasterChef contract). Used to calculate reward APY. character [optional]
#' @field reward_token_emissions_amount Per-block reward token emission as of the current block normalized to a day (not hour), in token's native amount. This should be ideally calculated as the theoretical rate instead of the realized amount. list(character) [optional]
#' @field reward_token_emissions_usd Per-block reward token emission as of the current block normalized to a day (not hour), in USD value. This should be ideally calculated as the theoretical rate instead of the realized amount. list(character) [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO <- R6::R6Class(
  "CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO",
  public = list(
    `entry_time` = NULL,
    `recv_time` = NULL,
    `block_number` = NULL,
    `block_range` = NULL,
    `id` = NULL,
    `protocol` = NULL,
    `pool` = NULL,
    `timestamp` = NULL,
    `total_value_locked_usd` = NULL,
    `cumulative_supply_side_revenue_usd` = NULL,
    `hourly_supply_side_revenue_usd` = NULL,
    `cumulative_protocol_side_revenue_usd` = NULL,
    `hourly_protocol_side_revenue_usd` = NULL,
    `cumulative_total_revenue_usd` = NULL,
    `hourly_total_revenue_usd` = NULL,
    `hourly_volume_usd` = NULL,
    `hourly_volume_by_token_amount` = NULL,
    `hourly_volume_by_token_usd` = NULL,
    `cumulative_volume_usd` = NULL,
    `input_token_balances` = NULL,
    `input_token_weights` = NULL,
    `output_token_supply` = NULL,
    `output_token_price_usd` = NULL,
    `staked_output_token_amount` = NULL,
    `reward_token_emissions_amount` = NULL,
    `reward_token_emissions_usd` = NULL,
    #' Initialize a new CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO class.
    #'
    #' @description
    #' Initialize a new CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO class.
    #'
    #' @param entry_time entry_time
    #' @param recv_time recv_time
    #' @param block_number Number of block in which entity was recorded.
    #' @param block_range 
    #' @param id (smart contract address of the pool)-(# of hours since unix epoch time)
    #' @param protocol The protocol this snapshot belongs to
    #' @param pool The pool this snapshot belongs to
    #' @param timestamp Timestamp of this snapshot
    #' @param total_value_locked_usd Current TVL (Total Value Locked) of this pool
    #' @param cumulative_supply_side_revenue_usd All revenue generated by the liquidity pool, accrued to the supply side.
    #' @param hourly_supply_side_revenue_usd Hourly revenue generated by the liquidity pool, accrued to the supply side.
    #' @param cumulative_protocol_side_revenue_usd All revenue generated by the liquidity pool, accrued to the protocol.
    #' @param hourly_protocol_side_revenue_usd Hourly revenue generated by the liquidity pool, accrued to the protocol.
    #' @param cumulative_total_revenue_usd All revenue generated by the liquidity pool.
    #' @param hourly_total_revenue_usd Hourly revenue generated by the liquidity pool.
    #' @param hourly_volume_usd All trade volume occurred in a given hour, in USD
    #' @param hourly_volume_by_token_amount All trade volume occurred in a given hour for a specific input token, in native amount. The ordering should be the same as the pool's 'inputTokens' field.
    #' @param hourly_volume_by_token_usd All trade volume occurred in a given hour for a specific input token, in USD. The ordering should be the same as the pool's 'inputTokens' field.
    #' @param cumulative_volume_usd All historical trade volume occurred in this pool, in USD
    #' @param input_token_balances Amount of input tokens in the pool. The ordering should be the same as the pool's 'inputTokens' field.
    #' @param input_token_weights Weights of input tokens in the liquidity pool in percentage values. For example, 50/50 for Uniswap pools, 48.2/51.8 for a Curve pool, 10/10/80 for a Balancer pool
    #' @param output_token_supply Total supply of output token. Note that certain DEXes don't have an output token (e.g. Bancor)
    #' @param output_token_price_usd Price per share of output token in USD
    #' @param staked_output_token_amount Total supply of output tokens that are staked (usually in the MasterChef contract). Used to calculate reward APY.
    #' @param reward_token_emissions_amount Per-block reward token emission as of the current block normalized to a day (not hour), in token's native amount. This should be ideally calculated as the theoretical rate instead of the realized amount.
    #' @param reward_token_emissions_usd Per-block reward token emission as of the current block normalized to a day (not hour), in USD value. This should be ideally calculated as the theoretical rate instead of the realized amount.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(`entry_time` = NULL, `recv_time` = NULL, `block_number` = NULL, `block_range` = NULL, `id` = NULL, `protocol` = NULL, `pool` = NULL, `timestamp` = NULL, `total_value_locked_usd` = NULL, `cumulative_supply_side_revenue_usd` = NULL, `hourly_supply_side_revenue_usd` = NULL, `cumulative_protocol_side_revenue_usd` = NULL, `hourly_protocol_side_revenue_usd` = NULL, `cumulative_total_revenue_usd` = NULL, `hourly_total_revenue_usd` = NULL, `hourly_volume_usd` = NULL, `hourly_volume_by_token_amount` = NULL, `hourly_volume_by_token_usd` = NULL, `cumulative_volume_usd` = NULL, `input_token_balances` = NULL, `input_token_weights` = NULL, `output_token_supply` = NULL, `output_token_price_usd` = NULL, `staked_output_token_amount` = NULL, `reward_token_emissions_amount` = NULL, `reward_token_emissions_usd` = NULL, ...) {
      if (!is.null(`entry_time`)) {
        if (!is.character(`entry_time`)) {
          stop(paste("Error! Invalid data for `entry_time`. Must be a string:", `entry_time`))
        }
        self$`entry_time` <- `entry_time`
      }
      if (!is.null(`recv_time`)) {
        if (!is.character(`recv_time`)) {
          stop(paste("Error! Invalid data for `recv_time`. Must be a string:", `recv_time`))
        }
        self$`recv_time` <- `recv_time`
      }
      if (!is.null(`block_number`)) {
        if (!(is.numeric(`block_number`) && length(`block_number`) == 1)) {
          stop(paste("Error! Invalid data for `block_number`. Must be an integer:", `block_number`))
        }
        self$`block_number` <- `block_number`
      }
      if (!is.null(`block_range`)) {
        if (!(is.character(`block_range`) && length(`block_range`) == 1)) {
          stop(paste("Error! Invalid data for `block_range`. Must be a string:", `block_range`))
        }
        self$`block_range` <- `block_range`
      }
      if (!is.null(`id`)) {
        if (!(is.character(`id`) && length(`id`) == 1)) {
          stop(paste("Error! Invalid data for `id`. Must be a string:", `id`))
        }
        self$`id` <- `id`
      }
      if (!is.null(`protocol`)) {
        if (!(is.character(`protocol`) && length(`protocol`) == 1)) {
          stop(paste("Error! Invalid data for `protocol`. Must be a string:", `protocol`))
        }
        self$`protocol` <- `protocol`
      }
      if (!is.null(`pool`)) {
        if (!(is.character(`pool`) && length(`pool`) == 1)) {
          stop(paste("Error! Invalid data for `pool`. Must be a string:", `pool`))
        }
        self$`pool` <- `pool`
      }
      if (!is.null(`timestamp`)) {
        if (!(is.character(`timestamp`) && length(`timestamp`) == 1)) {
          stop(paste("Error! Invalid data for `timestamp`. Must be a string:", `timestamp`))
        }
        self$`timestamp` <- `timestamp`
      }
      if (!is.null(`total_value_locked_usd`)) {
        if (!(is.character(`total_value_locked_usd`) && length(`total_value_locked_usd`) == 1)) {
          stop(paste("Error! Invalid data for `total_value_locked_usd`. Must be a string:", `total_value_locked_usd`))
        }
        self$`total_value_locked_usd` <- `total_value_locked_usd`
      }
      if (!is.null(`cumulative_supply_side_revenue_usd`)) {
        if (!(is.character(`cumulative_supply_side_revenue_usd`) && length(`cumulative_supply_side_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_supply_side_revenue_usd`. Must be a string:", `cumulative_supply_side_revenue_usd`))
        }
        self$`cumulative_supply_side_revenue_usd` <- `cumulative_supply_side_revenue_usd`
      }
      if (!is.null(`hourly_supply_side_revenue_usd`)) {
        if (!(is.character(`hourly_supply_side_revenue_usd`) && length(`hourly_supply_side_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `hourly_supply_side_revenue_usd`. Must be a string:", `hourly_supply_side_revenue_usd`))
        }
        self$`hourly_supply_side_revenue_usd` <- `hourly_supply_side_revenue_usd`
      }
      if (!is.null(`cumulative_protocol_side_revenue_usd`)) {
        if (!(is.character(`cumulative_protocol_side_revenue_usd`) && length(`cumulative_protocol_side_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_protocol_side_revenue_usd`. Must be a string:", `cumulative_protocol_side_revenue_usd`))
        }
        self$`cumulative_protocol_side_revenue_usd` <- `cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(`hourly_protocol_side_revenue_usd`)) {
        if (!(is.character(`hourly_protocol_side_revenue_usd`) && length(`hourly_protocol_side_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `hourly_protocol_side_revenue_usd`. Must be a string:", `hourly_protocol_side_revenue_usd`))
        }
        self$`hourly_protocol_side_revenue_usd` <- `hourly_protocol_side_revenue_usd`
      }
      if (!is.null(`cumulative_total_revenue_usd`)) {
        if (!(is.character(`cumulative_total_revenue_usd`) && length(`cumulative_total_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_total_revenue_usd`. Must be a string:", `cumulative_total_revenue_usd`))
        }
        self$`cumulative_total_revenue_usd` <- `cumulative_total_revenue_usd`
      }
      if (!is.null(`hourly_total_revenue_usd`)) {
        if (!(is.character(`hourly_total_revenue_usd`) && length(`hourly_total_revenue_usd`) == 1)) {
          stop(paste("Error! Invalid data for `hourly_total_revenue_usd`. Must be a string:", `hourly_total_revenue_usd`))
        }
        self$`hourly_total_revenue_usd` <- `hourly_total_revenue_usd`
      }
      if (!is.null(`hourly_volume_usd`)) {
        if (!(is.character(`hourly_volume_usd`) && length(`hourly_volume_usd`) == 1)) {
          stop(paste("Error! Invalid data for `hourly_volume_usd`. Must be a string:", `hourly_volume_usd`))
        }
        self$`hourly_volume_usd` <- `hourly_volume_usd`
      }
      if (!is.null(`hourly_volume_by_token_amount`)) {
        stopifnot(is.vector(`hourly_volume_by_token_amount`), length(`hourly_volume_by_token_amount`) != 0)
        sapply(`hourly_volume_by_token_amount`, function(x) stopifnot(is.character(x)))
        self$`hourly_volume_by_token_amount` <- `hourly_volume_by_token_amount`
      }
      if (!is.null(`hourly_volume_by_token_usd`)) {
        stopifnot(is.vector(`hourly_volume_by_token_usd`), length(`hourly_volume_by_token_usd`) != 0)
        sapply(`hourly_volume_by_token_usd`, function(x) stopifnot(is.character(x)))
        self$`hourly_volume_by_token_usd` <- `hourly_volume_by_token_usd`
      }
      if (!is.null(`cumulative_volume_usd`)) {
        if (!(is.character(`cumulative_volume_usd`) && length(`cumulative_volume_usd`) == 1)) {
          stop(paste("Error! Invalid data for `cumulative_volume_usd`. Must be a string:", `cumulative_volume_usd`))
        }
        self$`cumulative_volume_usd` <- `cumulative_volume_usd`
      }
      if (!is.null(`input_token_balances`)) {
        stopifnot(is.vector(`input_token_balances`), length(`input_token_balances`) != 0)
        sapply(`input_token_balances`, function(x) stopifnot(is.character(x)))
        self$`input_token_balances` <- `input_token_balances`
      }
      if (!is.null(`input_token_weights`)) {
        stopifnot(is.vector(`input_token_weights`), length(`input_token_weights`) != 0)
        sapply(`input_token_weights`, function(x) stopifnot(is.character(x)))
        self$`input_token_weights` <- `input_token_weights`
      }
      if (!is.null(`output_token_supply`)) {
        if (!(is.character(`output_token_supply`) && length(`output_token_supply`) == 1)) {
          stop(paste("Error! Invalid data for `output_token_supply`. Must be a string:", `output_token_supply`))
        }
        self$`output_token_supply` <- `output_token_supply`
      }
      if (!is.null(`output_token_price_usd`)) {
        if (!(is.character(`output_token_price_usd`) && length(`output_token_price_usd`) == 1)) {
          stop(paste("Error! Invalid data for `output_token_price_usd`. Must be a string:", `output_token_price_usd`))
        }
        self$`output_token_price_usd` <- `output_token_price_usd`
      }
      if (!is.null(`staked_output_token_amount`)) {
        if (!(is.character(`staked_output_token_amount`) && length(`staked_output_token_amount`) == 1)) {
          stop(paste("Error! Invalid data for `staked_output_token_amount`. Must be a string:", `staked_output_token_amount`))
        }
        self$`staked_output_token_amount` <- `staked_output_token_amount`
      }
      if (!is.null(`reward_token_emissions_amount`)) {
        stopifnot(is.vector(`reward_token_emissions_amount`), length(`reward_token_emissions_amount`) != 0)
        sapply(`reward_token_emissions_amount`, function(x) stopifnot(is.character(x)))
        self$`reward_token_emissions_amount` <- `reward_token_emissions_amount`
      }
      if (!is.null(`reward_token_emissions_usd`)) {
        stopifnot(is.vector(`reward_token_emissions_usd`), length(`reward_token_emissions_usd`) != 0)
        sapply(`reward_token_emissions_usd`, function(x) stopifnot(is.character(x)))
        self$`reward_token_emissions_usd` <- `reward_token_emissions_usd`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO in JSON format
    #' @export
    toJSON = function() {
      CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject <- list()
      if (!is.null(self$`entry_time`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["entry_time"]] <-
          self$`entry_time`
      }
      if (!is.null(self$`recv_time`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["recv_time"]] <-
          self$`recv_time`
      }
      if (!is.null(self$`block_number`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["block_number"]] <-
          self$`block_number`
      }
      if (!is.null(self$`block_range`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["block_range"]] <-
          self$`block_range`
      }
      if (!is.null(self$`id`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["id"]] <-
          self$`id`
      }
      if (!is.null(self$`protocol`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["protocol"]] <-
          self$`protocol`
      }
      if (!is.null(self$`pool`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["pool"]] <-
          self$`pool`
      }
      if (!is.null(self$`timestamp`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["timestamp"]] <-
          self$`timestamp`
      }
      if (!is.null(self$`total_value_locked_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["total_value_locked_usd"]] <-
          self$`total_value_locked_usd`
      }
      if (!is.null(self$`cumulative_supply_side_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["cumulative_supply_side_revenue_usd"]] <-
          self$`cumulative_supply_side_revenue_usd`
      }
      if (!is.null(self$`hourly_supply_side_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["hourly_supply_side_revenue_usd"]] <-
          self$`hourly_supply_side_revenue_usd`
      }
      if (!is.null(self$`cumulative_protocol_side_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["cumulative_protocol_side_revenue_usd"]] <-
          self$`cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(self$`hourly_protocol_side_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["hourly_protocol_side_revenue_usd"]] <-
          self$`hourly_protocol_side_revenue_usd`
      }
      if (!is.null(self$`cumulative_total_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["cumulative_total_revenue_usd"]] <-
          self$`cumulative_total_revenue_usd`
      }
      if (!is.null(self$`hourly_total_revenue_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["hourly_total_revenue_usd"]] <-
          self$`hourly_total_revenue_usd`
      }
      if (!is.null(self$`hourly_volume_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["hourly_volume_usd"]] <-
          self$`hourly_volume_usd`
      }
      if (!is.null(self$`hourly_volume_by_token_amount`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["hourly_volume_by_token_amount"]] <-
          self$`hourly_volume_by_token_amount`
      }
      if (!is.null(self$`hourly_volume_by_token_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["hourly_volume_by_token_usd"]] <-
          self$`hourly_volume_by_token_usd`
      }
      if (!is.null(self$`cumulative_volume_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["cumulative_volume_usd"]] <-
          self$`cumulative_volume_usd`
      }
      if (!is.null(self$`input_token_balances`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["input_token_balances"]] <-
          self$`input_token_balances`
      }
      if (!is.null(self$`input_token_weights`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["input_token_weights"]] <-
          self$`input_token_weights`
      }
      if (!is.null(self$`output_token_supply`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["output_token_supply"]] <-
          self$`output_token_supply`
      }
      if (!is.null(self$`output_token_price_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["output_token_price_usd"]] <-
          self$`output_token_price_usd`
      }
      if (!is.null(self$`staked_output_token_amount`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["staked_output_token_amount"]] <-
          self$`staked_output_token_amount`
      }
      if (!is.null(self$`reward_token_emissions_amount`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["reward_token_emissions_amount"]] <-
          self$`reward_token_emissions_amount`
      }
      if (!is.null(self$`reward_token_emissions_usd`)) {
        CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject[["reward_token_emissions_usd"]] <-
          self$`reward_token_emissions_usd`
      }
      CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTOObject
    },
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
    #'
    #' @description
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
    #'
    #' @param input_json the JSON input
    #' @return the instance of CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`entry_time`)) {
        self$`entry_time` <- this_object$`entry_time`
      }
      if (!is.null(this_object$`recv_time`)) {
        self$`recv_time` <- this_object$`recv_time`
      }
      if (!is.null(this_object$`block_number`)) {
        self$`block_number` <- this_object$`block_number`
      }
      if (!is.null(this_object$`block_range`)) {
        self$`block_range` <- this_object$`block_range`
      }
      if (!is.null(this_object$`id`)) {
        self$`id` <- this_object$`id`
      }
      if (!is.null(this_object$`protocol`)) {
        self$`protocol` <- this_object$`protocol`
      }
      if (!is.null(this_object$`pool`)) {
        self$`pool` <- this_object$`pool`
      }
      if (!is.null(this_object$`timestamp`)) {
        self$`timestamp` <- this_object$`timestamp`
      }
      if (!is.null(this_object$`total_value_locked_usd`)) {
        self$`total_value_locked_usd` <- this_object$`total_value_locked_usd`
      }
      if (!is.null(this_object$`cumulative_supply_side_revenue_usd`)) {
        self$`cumulative_supply_side_revenue_usd` <- this_object$`cumulative_supply_side_revenue_usd`
      }
      if (!is.null(this_object$`hourly_supply_side_revenue_usd`)) {
        self$`hourly_supply_side_revenue_usd` <- this_object$`hourly_supply_side_revenue_usd`
      }
      if (!is.null(this_object$`cumulative_protocol_side_revenue_usd`)) {
        self$`cumulative_protocol_side_revenue_usd` <- this_object$`cumulative_protocol_side_revenue_usd`
      }
      if (!is.null(this_object$`hourly_protocol_side_revenue_usd`)) {
        self$`hourly_protocol_side_revenue_usd` <- this_object$`hourly_protocol_side_revenue_usd`
      }
      if (!is.null(this_object$`cumulative_total_revenue_usd`)) {
        self$`cumulative_total_revenue_usd` <- this_object$`cumulative_total_revenue_usd`
      }
      if (!is.null(this_object$`hourly_total_revenue_usd`)) {
        self$`hourly_total_revenue_usd` <- this_object$`hourly_total_revenue_usd`
      }
      if (!is.null(this_object$`hourly_volume_usd`)) {
        self$`hourly_volume_usd` <- this_object$`hourly_volume_usd`
      }
      if (!is.null(this_object$`hourly_volume_by_token_amount`)) {
        self$`hourly_volume_by_token_amount` <- ApiClient$new()$deserializeObj(this_object$`hourly_volume_by_token_amount`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`hourly_volume_by_token_usd`)) {
        self$`hourly_volume_by_token_usd` <- ApiClient$new()$deserializeObj(this_object$`hourly_volume_by_token_usd`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`cumulative_volume_usd`)) {
        self$`cumulative_volume_usd` <- this_object$`cumulative_volume_usd`
      }
      if (!is.null(this_object$`input_token_balances`)) {
        self$`input_token_balances` <- ApiClient$new()$deserializeObj(this_object$`input_token_balances`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`input_token_weights`)) {
        self$`input_token_weights` <- ApiClient$new()$deserializeObj(this_object$`input_token_weights`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`output_token_supply`)) {
        self$`output_token_supply` <- this_object$`output_token_supply`
      }
      if (!is.null(this_object$`output_token_price_usd`)) {
        self$`output_token_price_usd` <- this_object$`output_token_price_usd`
      }
      if (!is.null(this_object$`staked_output_token_amount`)) {
        self$`staked_output_token_amount` <- this_object$`staked_output_token_amount`
      }
      if (!is.null(this_object$`reward_token_emissions_amount`)) {
        self$`reward_token_emissions_amount` <- ApiClient$new()$deserializeObj(this_object$`reward_token_emissions_amount`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(this_object$`reward_token_emissions_usd`)) {
        self$`reward_token_emissions_usd` <- ApiClient$new()$deserializeObj(this_object$`reward_token_emissions_usd`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`entry_time`)) {
          sprintf(
          '"entry_time":
            "%s"
                    ',
          self$`entry_time`
          )
        },
        if (!is.null(self$`recv_time`)) {
          sprintf(
          '"recv_time":
            "%s"
                    ',
          self$`recv_time`
          )
        },
        if (!is.null(self$`block_number`)) {
          sprintf(
          '"block_number":
            %d
                    ',
          self$`block_number`
          )
        },
        if (!is.null(self$`block_range`)) {
          sprintf(
          '"block_range":
            "%s"
                    ',
          self$`block_range`
          )
        },
        if (!is.null(self$`id`)) {
          sprintf(
          '"id":
            "%s"
                    ',
          self$`id`
          )
        },
        if (!is.null(self$`protocol`)) {
          sprintf(
          '"protocol":
            "%s"
                    ',
          self$`protocol`
          )
        },
        if (!is.null(self$`pool`)) {
          sprintf(
          '"pool":
            "%s"
                    ',
          self$`pool`
          )
        },
        if (!is.null(self$`timestamp`)) {
          sprintf(
          '"timestamp":
            "%s"
                    ',
          self$`timestamp`
          )
        },
        if (!is.null(self$`total_value_locked_usd`)) {
          sprintf(
          '"total_value_locked_usd":
            "%s"
                    ',
          self$`total_value_locked_usd`
          )
        },
        if (!is.null(self$`cumulative_supply_side_revenue_usd`)) {
          sprintf(
          '"cumulative_supply_side_revenue_usd":
            "%s"
                    ',
          self$`cumulative_supply_side_revenue_usd`
          )
        },
        if (!is.null(self$`hourly_supply_side_revenue_usd`)) {
          sprintf(
          '"hourly_supply_side_revenue_usd":
            "%s"
                    ',
          self$`hourly_supply_side_revenue_usd`
          )
        },
        if (!is.null(self$`cumulative_protocol_side_revenue_usd`)) {
          sprintf(
          '"cumulative_protocol_side_revenue_usd":
            "%s"
                    ',
          self$`cumulative_protocol_side_revenue_usd`
          )
        },
        if (!is.null(self$`hourly_protocol_side_revenue_usd`)) {
          sprintf(
          '"hourly_protocol_side_revenue_usd":
            "%s"
                    ',
          self$`hourly_protocol_side_revenue_usd`
          )
        },
        if (!is.null(self$`cumulative_total_revenue_usd`)) {
          sprintf(
          '"cumulative_total_revenue_usd":
            "%s"
                    ',
          self$`cumulative_total_revenue_usd`
          )
        },
        if (!is.null(self$`hourly_total_revenue_usd`)) {
          sprintf(
          '"hourly_total_revenue_usd":
            "%s"
                    ',
          self$`hourly_total_revenue_usd`
          )
        },
        if (!is.null(self$`hourly_volume_usd`)) {
          sprintf(
          '"hourly_volume_usd":
            "%s"
                    ',
          self$`hourly_volume_usd`
          )
        },
        if (!is.null(self$`hourly_volume_by_token_amount`)) {
          sprintf(
          '"hourly_volume_by_token_amount":
             [%s]
          ',
          paste(unlist(lapply(self$`hourly_volume_by_token_amount`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`hourly_volume_by_token_usd`)) {
          sprintf(
          '"hourly_volume_by_token_usd":
             [%s]
          ',
          paste(unlist(lapply(self$`hourly_volume_by_token_usd`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`cumulative_volume_usd`)) {
          sprintf(
          '"cumulative_volume_usd":
            "%s"
                    ',
          self$`cumulative_volume_usd`
          )
        },
        if (!is.null(self$`input_token_balances`)) {
          sprintf(
          '"input_token_balances":
             [%s]
          ',
          paste(unlist(lapply(self$`input_token_balances`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`input_token_weights`)) {
          sprintf(
          '"input_token_weights":
             [%s]
          ',
          paste(unlist(lapply(self$`input_token_weights`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`output_token_supply`)) {
          sprintf(
          '"output_token_supply":
            "%s"
                    ',
          self$`output_token_supply`
          )
        },
        if (!is.null(self$`output_token_price_usd`)) {
          sprintf(
          '"output_token_price_usd":
            "%s"
                    ',
          self$`output_token_price_usd`
          )
        },
        if (!is.null(self$`staked_output_token_amount`)) {
          sprintf(
          '"staked_output_token_amount":
            "%s"
                    ',
          self$`staked_output_token_amount`
          )
        },
        if (!is.null(self$`reward_token_emissions_amount`)) {
          sprintf(
          '"reward_token_emissions_amount":
             [%s]
          ',
          paste(unlist(lapply(self$`reward_token_emissions_amount`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`reward_token_emissions_usd`)) {
          sprintf(
          '"reward_token_emissions_usd":
             [%s]
          ',
          paste(unlist(lapply(self$`reward_token_emissions_usd`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      json_string <- as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
    #'
    #' @description
    #' Deserialize JSON string into an instance of CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
    #'
    #' @param input_json the JSON input
    #' @return the instance of CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`entry_time` <- this_object$`entry_time`
      self$`recv_time` <- this_object$`recv_time`
      self$`block_number` <- this_object$`block_number`
      self$`block_range` <- this_object$`block_range`
      self$`id` <- this_object$`id`
      self$`protocol` <- this_object$`protocol`
      self$`pool` <- this_object$`pool`
      self$`timestamp` <- this_object$`timestamp`
      self$`total_value_locked_usd` <- this_object$`total_value_locked_usd`
      self$`cumulative_supply_side_revenue_usd` <- this_object$`cumulative_supply_side_revenue_usd`
      self$`hourly_supply_side_revenue_usd` <- this_object$`hourly_supply_side_revenue_usd`
      self$`cumulative_protocol_side_revenue_usd` <- this_object$`cumulative_protocol_side_revenue_usd`
      self$`hourly_protocol_side_revenue_usd` <- this_object$`hourly_protocol_side_revenue_usd`
      self$`cumulative_total_revenue_usd` <- this_object$`cumulative_total_revenue_usd`
      self$`hourly_total_revenue_usd` <- this_object$`hourly_total_revenue_usd`
      self$`hourly_volume_usd` <- this_object$`hourly_volume_usd`
      self$`hourly_volume_by_token_amount` <- ApiClient$new()$deserializeObj(this_object$`hourly_volume_by_token_amount`, "array[character]", loadNamespace("openapi"))
      self$`hourly_volume_by_token_usd` <- ApiClient$new()$deserializeObj(this_object$`hourly_volume_by_token_usd`, "array[character]", loadNamespace("openapi"))
      self$`cumulative_volume_usd` <- this_object$`cumulative_volume_usd`
      self$`input_token_balances` <- ApiClient$new()$deserializeObj(this_object$`input_token_balances`, "array[character]", loadNamespace("openapi"))
      self$`input_token_weights` <- ApiClient$new()$deserializeObj(this_object$`input_token_weights`, "array[character]", loadNamespace("openapi"))
      self$`output_token_supply` <- this_object$`output_token_supply`
      self$`output_token_price_usd` <- this_object$`output_token_price_usd`
      self$`staked_output_token_amount` <- this_object$`staked_output_token_amount`
      self$`reward_token_emissions_amount` <- ApiClient$new()$deserializeObj(this_object$`reward_token_emissions_amount`, "array[character]", loadNamespace("openapi"))
      self$`reward_token_emissions_usd` <- ApiClient$new()$deserializeObj(this_object$`reward_token_emissions_usd`, "array[character]", loadNamespace("openapi"))
      self
    },
    #' Validate JSON input with respect to CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
    #'
    #' @description
    #' Validate JSON input with respect to CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      invalid_fields
    },
    #' Print the object
    #'
    #' @description
    #' Print the object
    #'
    #' @export
    print = function() {
      print(jsonlite::prettify(self$toJSONString()))
      invisible(self)
    }
  ),
  # Lock the class to prevent modifications to the method or field
  lock_class = TRUE
)
## Uncomment below to unlock the class to allow modifications of the method or field
# CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO$unlock()
#
## Below is an example to define the print function
# CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO$set("public", "print", function(...) {
#   print(jsonlite::prettify(self$toJSONString()))
#   invisible(self)
# })
## Uncomment below to lock the class to prevent modifications to the method or field
# CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO$lock()

