# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CRYPTOPUNKSETHEREUMApi")

api_instance <- CRYPTOPUNKSETHEREUMApi$new()

test_that("CRYPTOPUNKSETHEREUMBidsCurrent", {
  # tests for CRYPTOPUNKSETHEREUMBidsCurrent
  # base path: https://onchain.coinapi.io
  # Bids (current)
  # Gets bids.
  # @return [array[CRYPTOPUNKSBidDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CRYPTOPUNKSETHEREUMCollectionDailySnapshotsCurrent", {
  # tests for CRYPTOPUNKSETHEREUMCollectionDailySnapshotsCurrent
  # base path: https://onchain.coinapi.io
  # CollectionDailySnapshots (current)
  # Gets collectionDailySnapshots.
  # @return [array[CRYPTOPUNKSCollectionDailySnapshotDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CRYPTOPUNKSETHEREUMCollectionsCurrent", {
  # tests for CRYPTOPUNKSETHEREUMCollectionsCurrent
  # base path: https://onchain.coinapi.io
  # Collections (current)
  # Gets collections.
  # @return [array[CRYPTOPUNKSCollectionDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CRYPTOPUNKSETHEREUMDataSourcesCurrent", {
  # tests for CRYPTOPUNKSETHEREUMDataSourcesCurrent
  # base path: https://onchain.coinapi.io
  # DataSources (current)
  # Gets dataSources.
  # @return [array[CRYPTOPUNKSDataSourcesDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CRYPTOPUNKSETHEREUMItemsCurrent", {
  # tests for CRYPTOPUNKSETHEREUMItemsCurrent
  # base path: https://onchain.coinapi.io
  # Items (current)
  # Gets items.
  # @return [array[CRYPTOPUNKSItemDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CRYPTOPUNKSETHEREUMMarketPlacesCurrent", {
  # tests for CRYPTOPUNKSETHEREUMMarketPlacesCurrent
  # base path: https://onchain.coinapi.io
  # MarketPlaces (current)
  # Gets marketPlaces.
  # @return [array[CRYPTOPUNKSMarketPlaceDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CRYPTOPUNKSETHEREUMMarketplaceDailySnapshotsCurrent", {
  # tests for CRYPTOPUNKSETHEREUMMarketplaceDailySnapshotsCurrent
  # base path: https://onchain.coinapi.io
  # MarketplaceDailySnapshots (current)
  # Gets marketplaceDailySnapshots.
  # @return [array[CRYPTOPUNKSMarketplaceDailySnapshotDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CRYPTOPUNKSETHEREUMTradesCurrent", {
  # tests for CRYPTOPUNKSETHEREUMTradesCurrent
  # base path: https://onchain.coinapi.io
  # Trades (current)
  # Gets trades.
  # @return [array[CRYPTOPUNKSTradeDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CRYPTOPUNKSETHEREUMUsersCurrent", {
  # tests for CRYPTOPUNKSETHEREUMUsersCurrent
  # base path: https://onchain.coinapi.io
  # Users (current)
  # Gets users.
  # @return [array[CRYPTOPUNKSUserDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
