{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import OnChainDapps-REST.Model
import OnChainDapps-REST.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSBidDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSCollectionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSCollectionDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSDataSourcesDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSItemDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSMarketPlaceDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSMarketplaceDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSTradeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CRYPTOPUNKSUserDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMActiveAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMDepositDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMDexAmmProtocolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMFinancialsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMLiquidityGaugeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMLiquidityPoolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMLiquidityPoolDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMLiquidityPoolFeeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMLiquidityPoolHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMLpTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMRewardTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMSwapDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMUsageMetricsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMUsageMetricsHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CURVEFINANCEETHEREUMWithdrawDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMActiveAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMDepositDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMDexAmmProtocolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMFinancialsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMLiquidityPoolAmountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMLiquidityPoolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMLiquidityPoolFeeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMLiquidityPoolHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMPositionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMPositionSnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMRewardTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMSwapDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMTickDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMTickDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMTickHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMTokenWhiteListDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMTokenWhiteListSymbolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMUsageMetricsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMUsageMetricsHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy PANCAKESWAPV3ETHEREUMWithdrawDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMActiveAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMDepositDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMDexAmmProtocolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMFinancialsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMLiquidityPoolAmountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMLiquidityPoolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMLiquidityPoolFeeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMLiquidityPoolHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMPositionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMPositionSnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMRewardTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMSwapDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMTickDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMTickDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMTickHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMTokenWhiteListDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMTokenWhiteListSymbolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMUsageMetricsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMUsageMetricsHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SUSHISWAPV3ETHEREUMWithdrawDTO)
      propMimeEq MimeJSON (Proxy :: Proxy TransactionsETradeAggressiveSide)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMActiveAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMDepositDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMDexAmmProtocolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMFinancialsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMLiquidityPoolAmountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMLiquidityPoolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMLiquidityPoolDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMLiquidityPoolFeeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMLiquidityPoolHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMMasterChefAddressToPidDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMMasterChefDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMMasterChefRewarderDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMMasterChefStakingPoolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMRewardTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMRewarderProbeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMSwapDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMTokenWhiteListDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMTransferDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMUsageMetricsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMUsageMetricsHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV2ETHEREUMWithdrawDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMActiveAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMDepositDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMDexAmmProtocolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMFinancialsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMLiquidityPoolAmountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMLiquidityPoolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMLiquidityPoolFeeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMLiquidityPoolHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMPositionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMPositionSnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMRewardTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMSwapDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMTickDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMTickDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMTickHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMTokenWhiteListDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMTokenWhiteListSymbolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMUsageMetricsDailySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMUsageMetricsHourlySnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UNISWAPV3ETHEREUMWithdrawDTO)
      
