/*
On Chain Dapps - REST API

 This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             

API version: v1
Contact: support@coinapi.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO{}

// PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO Represents a liquidity pool daily snapshot for PancakeSwap V3.
type PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO struct {
	EntryTime *time.Time `json:"entry_time,omitempty"`
	RecvTime *time.Time `json:"recv_time,omitempty"`
	// Number of block in which entity was recorded.
	BlockNumber *int64 `json:"block_number,omitempty"`
	// The Ethereum block number associated with the liquidity pool daily snapshot.
	Block *int32 `json:"block_,omitempty"`
	// Identifier, format: (smart contract address of the pool)-(# of days since Unix epoch time).
	Id NullableString `json:"id,omitempty"`
	// Number of days since Unix epoch time.
	Day *int32 `json:"day,omitempty"`
	// Protocol associated with the liquidity pool.
	Protocol NullableString `json:"protocol,omitempty"`
	// Pool this snapshot belongs to.
	Pool NullableString `json:"pool,omitempty"`
	// Current tick representing the price of token0/token1.
	Tick NullableString `json:"tick,omitempty"`
	// Current TVL (Total Value Locked) of this pool.
	TotalValueLockedUsd NullableString `json:"total_value_locked_usd,omitempty"`
	// The sum of all active and non-active liquidity for this pool.
	TotalLiquidity NullableString `json:"total_liquidity,omitempty"`
	// Sum of all active and non-active liquidity in USD for this pool.
	TotalLiquidityUsd NullableString `json:"total_liquidity_usd,omitempty"`
	// All liquidity `k` that is active. Will be equal to totalLiquidity except for in concentrated liquidity - where activeLiquidity is all liquidity positions that contain the pools current tick.
	ActiveLiquidity NullableString `json:"active_liquidity,omitempty"`
	// All liquidity in USD that is active. Will be equal to totalLiquidity except for in concentrated liquidity - where activeLiquidity is all liquidity positions that contain the pools current tick.
	ActiveLiquidityUsd NullableString `json:"active_liquidity_usd,omitempty"`
	// All protocol-side value locked in token amounts that remains uncollected and unused in the pool.
	UncollectedProtocolSideTokenAmounts []string `json:"uncollected_protocol_side_token_amounts,omitempty"`
	// All protocol-side value locking in USD that remains uncollected and unused in the pool.
	UncollectedProtocolSideValuesUsd []string `json:"uncollected_protocol_side_values_usd,omitempty"`
	// All supply-side value locked in token amounts that remains uncollected and unused in the pool.
	UncollectedSupplySideTokenAmounts []string `json:"uncollected_supply_side_token_amounts,omitempty"`
	// All supply-side value locked in USD that remains uncollected and unused in the pool.
	UncollectedSupplySideValuesUsd []string `json:"uncollected_supply_side_values_usd,omitempty"`
	// All revenue generated by the liquidity pool, accrued to the supply side.
	CumulativeSupplySideRevenueUsd NullableString `json:"cumulative_supply_side_revenue_usd,omitempty"`
	// Daily revenue generated by the liquidity pool, accrued to the supply side.
	DailySupplySideRevenueUsd NullableString `json:"daily_supply_side_revenue_usd,omitempty"`
	// All revenue generated by the liquidity pool, accrued to the protocol.
	CumulativeProtocolSideRevenueUsd NullableString `json:"cumulative_protocol_side_revenue_usd,omitempty"`
	// Daily revenue generated by the liquidity pool, accrued to the protocol.
	DailyProtocolSideRevenueUsd NullableString `json:"daily_protocol_side_revenue_usd,omitempty"`
	// All revenue generated by the liquidity pool.
	CumulativeTotalRevenueUsd NullableString `json:"cumulative_total_revenue_usd,omitempty"`
	// Daily revenue generated by the liquidity pool.
	DailyTotalRevenueUsd NullableString `json:"daily_total_revenue_usd,omitempty"`
	// All historical trade volume occurred in this pool, in USD.
	CumulativeVolumeUsd NullableString `json:"cumulative_volume_usd,omitempty"`
	// All trade volume occurred in a given day, in USD.
	DailyVolumeUsd NullableString `json:"daily_volume_usd,omitempty"`
	// All trade volume , in native amount. The ordering should be the same as the pool's `inputTokens` field.
	CumulativeVolumeByTokenAmount []string `json:"cumulative_volume_by_token_amount,omitempty"`
	// All trade volume occurred in a given day for a specific input token, in native amount. The ordering should be the same as the pool's `inputTokens` field.
	DailyVolumeByTokenAmount []string `json:"daily_volume_by_token_amount,omitempty"`
	// All trade volume, in USD. The ordering should be the same as the pool's `inputTokens` field.
	CumulativeVolumeByTokenUsd []string `json:"cumulative_volume_by_token_usd,omitempty"`
	//  All trade volume occurred in a given day for a specific input token, in USD. The ordering should be the same as the pool's `inputTokens` field.
	DailyVolumeByTokenUsd []string `json:"daily_volume_by_token_usd,omitempty"`
	// Amount of input tokens in the pool. The ordering should be the same as the pool's `inputTokens` field.
	InputTokenBalances []string `json:"input_token_balances,omitempty"`
	// Amount of input tokens in USD in the pool. The ordering should be the same as the pool's `inputTokens` field.
	InputTokenBalancesUsd []string `json:"input_token_balances_usd,omitempty"`
	// Weights of input tokens in the liquidity pool in percentage values. For example, 50/50 for Uniswap pools, 48.2/51.8 for a Curve pool, 10/10/80 for a Balancer pool.
	InputTokenWeights []string `json:"input_token_weights,omitempty"`
	// Total supply of output tokens that are staked (usually in the MasterChef contract). Used to calculate reward APY.
	StakedOutputTokenAmount NullableString `json:"staked_output_token_amount,omitempty"`
	// Per-block reward token emission as of the current block normalized to a day, in token's native amount. This should be ideally calculated as the theoretical rate instead of the realized amount.
	RewardTokenEmissionsAmount []string `json:"reward_token_emissions_amount,omitempty"`
	// Per-block reward token emission as of the current block normalized to a day, in USD value. This should be ideally calculated as the theoretical rate instead of the realized amount.
	RewardTokenEmissionsUsd []string `json:"reward_token_emissions_usd,omitempty"`
	// Total number of deposits (add liquidity).
	CumulativeDepositCount *int32 `json:"cumulative_deposit_count,omitempty"`
	// Total number of deposits (add liquidity) in a day.
	DailyDepositCount *int32 `json:"daily_deposit_count,omitempty"`
	// Total number of withdrawals (remove liquidity).
	CumulativeWithdrawCount *int32 `json:"cumulative_withdraw_count,omitempty"`
	// Total number of withdrawals (remove liquidity) in a day.
	DailyWithdrawCount *int32 `json:"daily_withdraw_count,omitempty"`
	// Total number of trades (swaps).
	CumulativeSwapCount *int32 `json:"cumulative_swap_count,omitempty"`
	// Total number of trades (swaps) in a day.
	DailySwapCount *int32 `json:"daily_swap_count,omitempty"`
	// Number of positions in this market.
	PositionCount *int32 `json:"position_count,omitempty"`
	// Number of open positions in this market.
	OpenPositionCount *int32 `json:"open_position_count,omitempty"`
	// Number of closed positions in this market.
	ClosedPositionCount *int32 `json:"closed_position_count,omitempty"`
	// Timestamp of when this snapshot was taken/last modified (May be taken after interval has passed).
	Timestamp NullableString `json:"timestamp,omitempty"`
}

// NewPANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO instantiates a new PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO() *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO {
	this := PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO{}
	return &this
}

// NewPANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTOWithDefaults instantiates a new PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTOWithDefaults() *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO {
	this := PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO{}
	return &this
}

// GetEntryTime returns the EntryTime field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetEntryTime() time.Time {
	if o == nil || IsNil(o.EntryTime) {
		var ret time.Time
		return ret
	}
	return *o.EntryTime
}

// GetEntryTimeOk returns a tuple with the EntryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetEntryTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EntryTime) {
		return nil, false
	}
	return o.EntryTime, true
}

// HasEntryTime returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasEntryTime() bool {
	if o != nil && !IsNil(o.EntryTime) {
		return true
	}

	return false
}

// SetEntryTime gets a reference to the given time.Time and assigns it to the EntryTime field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetEntryTime(v time.Time) {
	o.EntryTime = &v
}

// GetRecvTime returns the RecvTime field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetRecvTime() time.Time {
	if o == nil || IsNil(o.RecvTime) {
		var ret time.Time
		return ret
	}
	return *o.RecvTime
}

// GetRecvTimeOk returns a tuple with the RecvTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetRecvTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RecvTime) {
		return nil, false
	}
	return o.RecvTime, true
}

// HasRecvTime returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasRecvTime() bool {
	if o != nil && !IsNil(o.RecvTime) {
		return true
	}

	return false
}

// SetRecvTime gets a reference to the given time.Time and assigns it to the RecvTime field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetRecvTime(v time.Time) {
	o.RecvTime = &v
}

// GetBlockNumber returns the BlockNumber field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetBlockNumber() int64 {
	if o == nil || IsNil(o.BlockNumber) {
		var ret int64
		return ret
	}
	return *o.BlockNumber
}

// GetBlockNumberOk returns a tuple with the BlockNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetBlockNumberOk() (*int64, bool) {
	if o == nil || IsNil(o.BlockNumber) {
		return nil, false
	}
	return o.BlockNumber, true
}

// HasBlockNumber returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasBlockNumber() bool {
	if o != nil && !IsNil(o.BlockNumber) {
		return true
	}

	return false
}

// SetBlockNumber gets a reference to the given int64 and assigns it to the BlockNumber field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetBlockNumber(v int64) {
	o.BlockNumber = &v
}

// GetBlock returns the Block field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetBlock() int32 {
	if o == nil || IsNil(o.Block) {
		var ret int32
		return ret
	}
	return *o.Block
}

// GetBlockOk returns a tuple with the Block field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetBlockOk() (*int32, bool) {
	if o == nil || IsNil(o.Block) {
		return nil, false
	}
	return o.Block, true
}

// HasBlock returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasBlock() bool {
	if o != nil && !IsNil(o.Block) {
		return true
	}

	return false
}

// SetBlock gets a reference to the given int32 and assigns it to the Block field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetBlock(v int32) {
	o.Block = &v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetId() {
	o.Id.Unset()
}

// GetDay returns the Day field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDay() int32 {
	if o == nil || IsNil(o.Day) {
		var ret int32
		return ret
	}
	return *o.Day
}

// GetDayOk returns a tuple with the Day field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDayOk() (*int32, bool) {
	if o == nil || IsNil(o.Day) {
		return nil, false
	}
	return o.Day, true
}

// HasDay returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDay() bool {
	if o != nil && !IsNil(o.Day) {
		return true
	}

	return false
}

// SetDay gets a reference to the given int32 and assigns it to the Day field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDay(v int32) {
	o.Day = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetProtocol() string {
	if o == nil || IsNil(o.Protocol.Get()) {
		var ret string
		return ret
	}
	return *o.Protocol.Get()
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Protocol.Get(), o.Protocol.IsSet()
}

// HasProtocol returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasProtocol() bool {
	if o != nil && o.Protocol.IsSet() {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given NullableString and assigns it to the Protocol field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetProtocol(v string) {
	o.Protocol.Set(&v)
}
// SetProtocolNil sets the value for Protocol to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetProtocolNil() {
	o.Protocol.Set(nil)
}

// UnsetProtocol ensures that no value is present for Protocol, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetProtocol() {
	o.Protocol.Unset()
}

// GetPool returns the Pool field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetPool() string {
	if o == nil || IsNil(o.Pool.Get()) {
		var ret string
		return ret
	}
	return *o.Pool.Get()
}

// GetPoolOk returns a tuple with the Pool field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetPoolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pool.Get(), o.Pool.IsSet()
}

// HasPool returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasPool() bool {
	if o != nil && o.Pool.IsSet() {
		return true
	}

	return false
}

// SetPool gets a reference to the given NullableString and assigns it to the Pool field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetPool(v string) {
	o.Pool.Set(&v)
}
// SetPoolNil sets the value for Pool to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetPoolNil() {
	o.Pool.Set(nil)
}

// UnsetPool ensures that no value is present for Pool, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetPool() {
	o.Pool.Unset()
}

// GetTick returns the Tick field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTick() string {
	if o == nil || IsNil(o.Tick.Get()) {
		var ret string
		return ret
	}
	return *o.Tick.Get()
}

// GetTickOk returns a tuple with the Tick field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTickOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tick.Get(), o.Tick.IsSet()
}

// HasTick returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasTick() bool {
	if o != nil && o.Tick.IsSet() {
		return true
	}

	return false
}

// SetTick gets a reference to the given NullableString and assigns it to the Tick field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTick(v string) {
	o.Tick.Set(&v)
}
// SetTickNil sets the value for Tick to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTickNil() {
	o.Tick.Set(nil)
}

// UnsetTick ensures that no value is present for Tick, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetTick() {
	o.Tick.Unset()
}

// GetTotalValueLockedUsd returns the TotalValueLockedUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTotalValueLockedUsd() string {
	if o == nil || IsNil(o.TotalValueLockedUsd.Get()) {
		var ret string
		return ret
	}
	return *o.TotalValueLockedUsd.Get()
}

// GetTotalValueLockedUsdOk returns a tuple with the TotalValueLockedUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTotalValueLockedUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalValueLockedUsd.Get(), o.TotalValueLockedUsd.IsSet()
}

// HasTotalValueLockedUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasTotalValueLockedUsd() bool {
	if o != nil && o.TotalValueLockedUsd.IsSet() {
		return true
	}

	return false
}

// SetTotalValueLockedUsd gets a reference to the given NullableString and assigns it to the TotalValueLockedUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTotalValueLockedUsd(v string) {
	o.TotalValueLockedUsd.Set(&v)
}
// SetTotalValueLockedUsdNil sets the value for TotalValueLockedUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTotalValueLockedUsdNil() {
	o.TotalValueLockedUsd.Set(nil)
}

// UnsetTotalValueLockedUsd ensures that no value is present for TotalValueLockedUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetTotalValueLockedUsd() {
	o.TotalValueLockedUsd.Unset()
}

// GetTotalLiquidity returns the TotalLiquidity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTotalLiquidity() string {
	if o == nil || IsNil(o.TotalLiquidity.Get()) {
		var ret string
		return ret
	}
	return *o.TotalLiquidity.Get()
}

// GetTotalLiquidityOk returns a tuple with the TotalLiquidity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTotalLiquidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalLiquidity.Get(), o.TotalLiquidity.IsSet()
}

// HasTotalLiquidity returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasTotalLiquidity() bool {
	if o != nil && o.TotalLiquidity.IsSet() {
		return true
	}

	return false
}

// SetTotalLiquidity gets a reference to the given NullableString and assigns it to the TotalLiquidity field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTotalLiquidity(v string) {
	o.TotalLiquidity.Set(&v)
}
// SetTotalLiquidityNil sets the value for TotalLiquidity to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTotalLiquidityNil() {
	o.TotalLiquidity.Set(nil)
}

// UnsetTotalLiquidity ensures that no value is present for TotalLiquidity, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetTotalLiquidity() {
	o.TotalLiquidity.Unset()
}

// GetTotalLiquidityUsd returns the TotalLiquidityUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTotalLiquidityUsd() string {
	if o == nil || IsNil(o.TotalLiquidityUsd.Get()) {
		var ret string
		return ret
	}
	return *o.TotalLiquidityUsd.Get()
}

// GetTotalLiquidityUsdOk returns a tuple with the TotalLiquidityUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTotalLiquidityUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalLiquidityUsd.Get(), o.TotalLiquidityUsd.IsSet()
}

// HasTotalLiquidityUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasTotalLiquidityUsd() bool {
	if o != nil && o.TotalLiquidityUsd.IsSet() {
		return true
	}

	return false
}

// SetTotalLiquidityUsd gets a reference to the given NullableString and assigns it to the TotalLiquidityUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTotalLiquidityUsd(v string) {
	o.TotalLiquidityUsd.Set(&v)
}
// SetTotalLiquidityUsdNil sets the value for TotalLiquidityUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTotalLiquidityUsdNil() {
	o.TotalLiquidityUsd.Set(nil)
}

// UnsetTotalLiquidityUsd ensures that no value is present for TotalLiquidityUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetTotalLiquidityUsd() {
	o.TotalLiquidityUsd.Unset()
}

// GetActiveLiquidity returns the ActiveLiquidity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetActiveLiquidity() string {
	if o == nil || IsNil(o.ActiveLiquidity.Get()) {
		var ret string
		return ret
	}
	return *o.ActiveLiquidity.Get()
}

// GetActiveLiquidityOk returns a tuple with the ActiveLiquidity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetActiveLiquidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveLiquidity.Get(), o.ActiveLiquidity.IsSet()
}

// HasActiveLiquidity returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasActiveLiquidity() bool {
	if o != nil && o.ActiveLiquidity.IsSet() {
		return true
	}

	return false
}

// SetActiveLiquidity gets a reference to the given NullableString and assigns it to the ActiveLiquidity field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetActiveLiquidity(v string) {
	o.ActiveLiquidity.Set(&v)
}
// SetActiveLiquidityNil sets the value for ActiveLiquidity to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetActiveLiquidityNil() {
	o.ActiveLiquidity.Set(nil)
}

// UnsetActiveLiquidity ensures that no value is present for ActiveLiquidity, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetActiveLiquidity() {
	o.ActiveLiquidity.Unset()
}

// GetActiveLiquidityUsd returns the ActiveLiquidityUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetActiveLiquidityUsd() string {
	if o == nil || IsNil(o.ActiveLiquidityUsd.Get()) {
		var ret string
		return ret
	}
	return *o.ActiveLiquidityUsd.Get()
}

// GetActiveLiquidityUsdOk returns a tuple with the ActiveLiquidityUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetActiveLiquidityUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveLiquidityUsd.Get(), o.ActiveLiquidityUsd.IsSet()
}

// HasActiveLiquidityUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasActiveLiquidityUsd() bool {
	if o != nil && o.ActiveLiquidityUsd.IsSet() {
		return true
	}

	return false
}

// SetActiveLiquidityUsd gets a reference to the given NullableString and assigns it to the ActiveLiquidityUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetActiveLiquidityUsd(v string) {
	o.ActiveLiquidityUsd.Set(&v)
}
// SetActiveLiquidityUsdNil sets the value for ActiveLiquidityUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetActiveLiquidityUsdNil() {
	o.ActiveLiquidityUsd.Set(nil)
}

// UnsetActiveLiquidityUsd ensures that no value is present for ActiveLiquidityUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetActiveLiquidityUsd() {
	o.ActiveLiquidityUsd.Unset()
}

// GetUncollectedProtocolSideTokenAmounts returns the UncollectedProtocolSideTokenAmounts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetUncollectedProtocolSideTokenAmounts() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.UncollectedProtocolSideTokenAmounts
}

// GetUncollectedProtocolSideTokenAmountsOk returns a tuple with the UncollectedProtocolSideTokenAmounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetUncollectedProtocolSideTokenAmountsOk() ([]string, bool) {
	if o == nil || IsNil(o.UncollectedProtocolSideTokenAmounts) {
		return nil, false
	}
	return o.UncollectedProtocolSideTokenAmounts, true
}

// HasUncollectedProtocolSideTokenAmounts returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasUncollectedProtocolSideTokenAmounts() bool {
	if o != nil && IsNil(o.UncollectedProtocolSideTokenAmounts) {
		return true
	}

	return false
}

// SetUncollectedProtocolSideTokenAmounts gets a reference to the given []string and assigns it to the UncollectedProtocolSideTokenAmounts field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetUncollectedProtocolSideTokenAmounts(v []string) {
	o.UncollectedProtocolSideTokenAmounts = v
}

// GetUncollectedProtocolSideValuesUsd returns the UncollectedProtocolSideValuesUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetUncollectedProtocolSideValuesUsd() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.UncollectedProtocolSideValuesUsd
}

// GetUncollectedProtocolSideValuesUsdOk returns a tuple with the UncollectedProtocolSideValuesUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetUncollectedProtocolSideValuesUsdOk() ([]string, bool) {
	if o == nil || IsNil(o.UncollectedProtocolSideValuesUsd) {
		return nil, false
	}
	return o.UncollectedProtocolSideValuesUsd, true
}

// HasUncollectedProtocolSideValuesUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasUncollectedProtocolSideValuesUsd() bool {
	if o != nil && IsNil(o.UncollectedProtocolSideValuesUsd) {
		return true
	}

	return false
}

// SetUncollectedProtocolSideValuesUsd gets a reference to the given []string and assigns it to the UncollectedProtocolSideValuesUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetUncollectedProtocolSideValuesUsd(v []string) {
	o.UncollectedProtocolSideValuesUsd = v
}

// GetUncollectedSupplySideTokenAmounts returns the UncollectedSupplySideTokenAmounts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetUncollectedSupplySideTokenAmounts() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.UncollectedSupplySideTokenAmounts
}

// GetUncollectedSupplySideTokenAmountsOk returns a tuple with the UncollectedSupplySideTokenAmounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetUncollectedSupplySideTokenAmountsOk() ([]string, bool) {
	if o == nil || IsNil(o.UncollectedSupplySideTokenAmounts) {
		return nil, false
	}
	return o.UncollectedSupplySideTokenAmounts, true
}

// HasUncollectedSupplySideTokenAmounts returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasUncollectedSupplySideTokenAmounts() bool {
	if o != nil && IsNil(o.UncollectedSupplySideTokenAmounts) {
		return true
	}

	return false
}

// SetUncollectedSupplySideTokenAmounts gets a reference to the given []string and assigns it to the UncollectedSupplySideTokenAmounts field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetUncollectedSupplySideTokenAmounts(v []string) {
	o.UncollectedSupplySideTokenAmounts = v
}

// GetUncollectedSupplySideValuesUsd returns the UncollectedSupplySideValuesUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetUncollectedSupplySideValuesUsd() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.UncollectedSupplySideValuesUsd
}

// GetUncollectedSupplySideValuesUsdOk returns a tuple with the UncollectedSupplySideValuesUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetUncollectedSupplySideValuesUsdOk() ([]string, bool) {
	if o == nil || IsNil(o.UncollectedSupplySideValuesUsd) {
		return nil, false
	}
	return o.UncollectedSupplySideValuesUsd, true
}

// HasUncollectedSupplySideValuesUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasUncollectedSupplySideValuesUsd() bool {
	if o != nil && IsNil(o.UncollectedSupplySideValuesUsd) {
		return true
	}

	return false
}

// SetUncollectedSupplySideValuesUsd gets a reference to the given []string and assigns it to the UncollectedSupplySideValuesUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetUncollectedSupplySideValuesUsd(v []string) {
	o.UncollectedSupplySideValuesUsd = v
}

// GetCumulativeSupplySideRevenueUsd returns the CumulativeSupplySideRevenueUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeSupplySideRevenueUsd() string {
	if o == nil || IsNil(o.CumulativeSupplySideRevenueUsd.Get()) {
		var ret string
		return ret
	}
	return *o.CumulativeSupplySideRevenueUsd.Get()
}

// GetCumulativeSupplySideRevenueUsdOk returns a tuple with the CumulativeSupplySideRevenueUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeSupplySideRevenueUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CumulativeSupplySideRevenueUsd.Get(), o.CumulativeSupplySideRevenueUsd.IsSet()
}

// HasCumulativeSupplySideRevenueUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeSupplySideRevenueUsd() bool {
	if o != nil && o.CumulativeSupplySideRevenueUsd.IsSet() {
		return true
	}

	return false
}

// SetCumulativeSupplySideRevenueUsd gets a reference to the given NullableString and assigns it to the CumulativeSupplySideRevenueUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeSupplySideRevenueUsd(v string) {
	o.CumulativeSupplySideRevenueUsd.Set(&v)
}
// SetCumulativeSupplySideRevenueUsdNil sets the value for CumulativeSupplySideRevenueUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeSupplySideRevenueUsdNil() {
	o.CumulativeSupplySideRevenueUsd.Set(nil)
}

// UnsetCumulativeSupplySideRevenueUsd ensures that no value is present for CumulativeSupplySideRevenueUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetCumulativeSupplySideRevenueUsd() {
	o.CumulativeSupplySideRevenueUsd.Unset()
}

// GetDailySupplySideRevenueUsd returns the DailySupplySideRevenueUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailySupplySideRevenueUsd() string {
	if o == nil || IsNil(o.DailySupplySideRevenueUsd.Get()) {
		var ret string
		return ret
	}
	return *o.DailySupplySideRevenueUsd.Get()
}

// GetDailySupplySideRevenueUsdOk returns a tuple with the DailySupplySideRevenueUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailySupplySideRevenueUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DailySupplySideRevenueUsd.Get(), o.DailySupplySideRevenueUsd.IsSet()
}

// HasDailySupplySideRevenueUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailySupplySideRevenueUsd() bool {
	if o != nil && o.DailySupplySideRevenueUsd.IsSet() {
		return true
	}

	return false
}

// SetDailySupplySideRevenueUsd gets a reference to the given NullableString and assigns it to the DailySupplySideRevenueUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailySupplySideRevenueUsd(v string) {
	o.DailySupplySideRevenueUsd.Set(&v)
}
// SetDailySupplySideRevenueUsdNil sets the value for DailySupplySideRevenueUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailySupplySideRevenueUsdNil() {
	o.DailySupplySideRevenueUsd.Set(nil)
}

// UnsetDailySupplySideRevenueUsd ensures that no value is present for DailySupplySideRevenueUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetDailySupplySideRevenueUsd() {
	o.DailySupplySideRevenueUsd.Unset()
}

// GetCumulativeProtocolSideRevenueUsd returns the CumulativeProtocolSideRevenueUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeProtocolSideRevenueUsd() string {
	if o == nil || IsNil(o.CumulativeProtocolSideRevenueUsd.Get()) {
		var ret string
		return ret
	}
	return *o.CumulativeProtocolSideRevenueUsd.Get()
}

// GetCumulativeProtocolSideRevenueUsdOk returns a tuple with the CumulativeProtocolSideRevenueUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeProtocolSideRevenueUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CumulativeProtocolSideRevenueUsd.Get(), o.CumulativeProtocolSideRevenueUsd.IsSet()
}

// HasCumulativeProtocolSideRevenueUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeProtocolSideRevenueUsd() bool {
	if o != nil && o.CumulativeProtocolSideRevenueUsd.IsSet() {
		return true
	}

	return false
}

// SetCumulativeProtocolSideRevenueUsd gets a reference to the given NullableString and assigns it to the CumulativeProtocolSideRevenueUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeProtocolSideRevenueUsd(v string) {
	o.CumulativeProtocolSideRevenueUsd.Set(&v)
}
// SetCumulativeProtocolSideRevenueUsdNil sets the value for CumulativeProtocolSideRevenueUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeProtocolSideRevenueUsdNil() {
	o.CumulativeProtocolSideRevenueUsd.Set(nil)
}

// UnsetCumulativeProtocolSideRevenueUsd ensures that no value is present for CumulativeProtocolSideRevenueUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetCumulativeProtocolSideRevenueUsd() {
	o.CumulativeProtocolSideRevenueUsd.Unset()
}

// GetDailyProtocolSideRevenueUsd returns the DailyProtocolSideRevenueUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyProtocolSideRevenueUsd() string {
	if o == nil || IsNil(o.DailyProtocolSideRevenueUsd.Get()) {
		var ret string
		return ret
	}
	return *o.DailyProtocolSideRevenueUsd.Get()
}

// GetDailyProtocolSideRevenueUsdOk returns a tuple with the DailyProtocolSideRevenueUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyProtocolSideRevenueUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DailyProtocolSideRevenueUsd.Get(), o.DailyProtocolSideRevenueUsd.IsSet()
}

// HasDailyProtocolSideRevenueUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailyProtocolSideRevenueUsd() bool {
	if o != nil && o.DailyProtocolSideRevenueUsd.IsSet() {
		return true
	}

	return false
}

// SetDailyProtocolSideRevenueUsd gets a reference to the given NullableString and assigns it to the DailyProtocolSideRevenueUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyProtocolSideRevenueUsd(v string) {
	o.DailyProtocolSideRevenueUsd.Set(&v)
}
// SetDailyProtocolSideRevenueUsdNil sets the value for DailyProtocolSideRevenueUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyProtocolSideRevenueUsdNil() {
	o.DailyProtocolSideRevenueUsd.Set(nil)
}

// UnsetDailyProtocolSideRevenueUsd ensures that no value is present for DailyProtocolSideRevenueUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetDailyProtocolSideRevenueUsd() {
	o.DailyProtocolSideRevenueUsd.Unset()
}

// GetCumulativeTotalRevenueUsd returns the CumulativeTotalRevenueUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeTotalRevenueUsd() string {
	if o == nil || IsNil(o.CumulativeTotalRevenueUsd.Get()) {
		var ret string
		return ret
	}
	return *o.CumulativeTotalRevenueUsd.Get()
}

// GetCumulativeTotalRevenueUsdOk returns a tuple with the CumulativeTotalRevenueUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeTotalRevenueUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CumulativeTotalRevenueUsd.Get(), o.CumulativeTotalRevenueUsd.IsSet()
}

// HasCumulativeTotalRevenueUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeTotalRevenueUsd() bool {
	if o != nil && o.CumulativeTotalRevenueUsd.IsSet() {
		return true
	}

	return false
}

// SetCumulativeTotalRevenueUsd gets a reference to the given NullableString and assigns it to the CumulativeTotalRevenueUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeTotalRevenueUsd(v string) {
	o.CumulativeTotalRevenueUsd.Set(&v)
}
// SetCumulativeTotalRevenueUsdNil sets the value for CumulativeTotalRevenueUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeTotalRevenueUsdNil() {
	o.CumulativeTotalRevenueUsd.Set(nil)
}

// UnsetCumulativeTotalRevenueUsd ensures that no value is present for CumulativeTotalRevenueUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetCumulativeTotalRevenueUsd() {
	o.CumulativeTotalRevenueUsd.Unset()
}

// GetDailyTotalRevenueUsd returns the DailyTotalRevenueUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyTotalRevenueUsd() string {
	if o == nil || IsNil(o.DailyTotalRevenueUsd.Get()) {
		var ret string
		return ret
	}
	return *o.DailyTotalRevenueUsd.Get()
}

// GetDailyTotalRevenueUsdOk returns a tuple with the DailyTotalRevenueUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyTotalRevenueUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DailyTotalRevenueUsd.Get(), o.DailyTotalRevenueUsd.IsSet()
}

// HasDailyTotalRevenueUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailyTotalRevenueUsd() bool {
	if o != nil && o.DailyTotalRevenueUsd.IsSet() {
		return true
	}

	return false
}

// SetDailyTotalRevenueUsd gets a reference to the given NullableString and assigns it to the DailyTotalRevenueUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyTotalRevenueUsd(v string) {
	o.DailyTotalRevenueUsd.Set(&v)
}
// SetDailyTotalRevenueUsdNil sets the value for DailyTotalRevenueUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyTotalRevenueUsdNil() {
	o.DailyTotalRevenueUsd.Set(nil)
}

// UnsetDailyTotalRevenueUsd ensures that no value is present for DailyTotalRevenueUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetDailyTotalRevenueUsd() {
	o.DailyTotalRevenueUsd.Unset()
}

// GetCumulativeVolumeUsd returns the CumulativeVolumeUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeVolumeUsd() string {
	if o == nil || IsNil(o.CumulativeVolumeUsd.Get()) {
		var ret string
		return ret
	}
	return *o.CumulativeVolumeUsd.Get()
}

// GetCumulativeVolumeUsdOk returns a tuple with the CumulativeVolumeUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeVolumeUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CumulativeVolumeUsd.Get(), o.CumulativeVolumeUsd.IsSet()
}

// HasCumulativeVolumeUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeVolumeUsd() bool {
	if o != nil && o.CumulativeVolumeUsd.IsSet() {
		return true
	}

	return false
}

// SetCumulativeVolumeUsd gets a reference to the given NullableString and assigns it to the CumulativeVolumeUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeVolumeUsd(v string) {
	o.CumulativeVolumeUsd.Set(&v)
}
// SetCumulativeVolumeUsdNil sets the value for CumulativeVolumeUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeVolumeUsdNil() {
	o.CumulativeVolumeUsd.Set(nil)
}

// UnsetCumulativeVolumeUsd ensures that no value is present for CumulativeVolumeUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetCumulativeVolumeUsd() {
	o.CumulativeVolumeUsd.Unset()
}

// GetDailyVolumeUsd returns the DailyVolumeUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyVolumeUsd() string {
	if o == nil || IsNil(o.DailyVolumeUsd.Get()) {
		var ret string
		return ret
	}
	return *o.DailyVolumeUsd.Get()
}

// GetDailyVolumeUsdOk returns a tuple with the DailyVolumeUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyVolumeUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DailyVolumeUsd.Get(), o.DailyVolumeUsd.IsSet()
}

// HasDailyVolumeUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailyVolumeUsd() bool {
	if o != nil && o.DailyVolumeUsd.IsSet() {
		return true
	}

	return false
}

// SetDailyVolumeUsd gets a reference to the given NullableString and assigns it to the DailyVolumeUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyVolumeUsd(v string) {
	o.DailyVolumeUsd.Set(&v)
}
// SetDailyVolumeUsdNil sets the value for DailyVolumeUsd to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyVolumeUsdNil() {
	o.DailyVolumeUsd.Set(nil)
}

// UnsetDailyVolumeUsd ensures that no value is present for DailyVolumeUsd, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetDailyVolumeUsd() {
	o.DailyVolumeUsd.Unset()
}

// GetCumulativeVolumeByTokenAmount returns the CumulativeVolumeByTokenAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeVolumeByTokenAmount() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.CumulativeVolumeByTokenAmount
}

// GetCumulativeVolumeByTokenAmountOk returns a tuple with the CumulativeVolumeByTokenAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeVolumeByTokenAmountOk() ([]string, bool) {
	if o == nil || IsNil(o.CumulativeVolumeByTokenAmount) {
		return nil, false
	}
	return o.CumulativeVolumeByTokenAmount, true
}

// HasCumulativeVolumeByTokenAmount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeVolumeByTokenAmount() bool {
	if o != nil && IsNil(o.CumulativeVolumeByTokenAmount) {
		return true
	}

	return false
}

// SetCumulativeVolumeByTokenAmount gets a reference to the given []string and assigns it to the CumulativeVolumeByTokenAmount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeVolumeByTokenAmount(v []string) {
	o.CumulativeVolumeByTokenAmount = v
}

// GetDailyVolumeByTokenAmount returns the DailyVolumeByTokenAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyVolumeByTokenAmount() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.DailyVolumeByTokenAmount
}

// GetDailyVolumeByTokenAmountOk returns a tuple with the DailyVolumeByTokenAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyVolumeByTokenAmountOk() ([]string, bool) {
	if o == nil || IsNil(o.DailyVolumeByTokenAmount) {
		return nil, false
	}
	return o.DailyVolumeByTokenAmount, true
}

// HasDailyVolumeByTokenAmount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailyVolumeByTokenAmount() bool {
	if o != nil && IsNil(o.DailyVolumeByTokenAmount) {
		return true
	}

	return false
}

// SetDailyVolumeByTokenAmount gets a reference to the given []string and assigns it to the DailyVolumeByTokenAmount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyVolumeByTokenAmount(v []string) {
	o.DailyVolumeByTokenAmount = v
}

// GetCumulativeVolumeByTokenUsd returns the CumulativeVolumeByTokenUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeVolumeByTokenUsd() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.CumulativeVolumeByTokenUsd
}

// GetCumulativeVolumeByTokenUsdOk returns a tuple with the CumulativeVolumeByTokenUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeVolumeByTokenUsdOk() ([]string, bool) {
	if o == nil || IsNil(o.CumulativeVolumeByTokenUsd) {
		return nil, false
	}
	return o.CumulativeVolumeByTokenUsd, true
}

// HasCumulativeVolumeByTokenUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeVolumeByTokenUsd() bool {
	if o != nil && IsNil(o.CumulativeVolumeByTokenUsd) {
		return true
	}

	return false
}

// SetCumulativeVolumeByTokenUsd gets a reference to the given []string and assigns it to the CumulativeVolumeByTokenUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeVolumeByTokenUsd(v []string) {
	o.CumulativeVolumeByTokenUsd = v
}

// GetDailyVolumeByTokenUsd returns the DailyVolumeByTokenUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyVolumeByTokenUsd() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.DailyVolumeByTokenUsd
}

// GetDailyVolumeByTokenUsdOk returns a tuple with the DailyVolumeByTokenUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyVolumeByTokenUsdOk() ([]string, bool) {
	if o == nil || IsNil(o.DailyVolumeByTokenUsd) {
		return nil, false
	}
	return o.DailyVolumeByTokenUsd, true
}

// HasDailyVolumeByTokenUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailyVolumeByTokenUsd() bool {
	if o != nil && IsNil(o.DailyVolumeByTokenUsd) {
		return true
	}

	return false
}

// SetDailyVolumeByTokenUsd gets a reference to the given []string and assigns it to the DailyVolumeByTokenUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyVolumeByTokenUsd(v []string) {
	o.DailyVolumeByTokenUsd = v
}

// GetInputTokenBalances returns the InputTokenBalances field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetInputTokenBalances() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.InputTokenBalances
}

// GetInputTokenBalancesOk returns a tuple with the InputTokenBalances field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetInputTokenBalancesOk() ([]string, bool) {
	if o == nil || IsNil(o.InputTokenBalances) {
		return nil, false
	}
	return o.InputTokenBalances, true
}

// HasInputTokenBalances returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasInputTokenBalances() bool {
	if o != nil && IsNil(o.InputTokenBalances) {
		return true
	}

	return false
}

// SetInputTokenBalances gets a reference to the given []string and assigns it to the InputTokenBalances field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetInputTokenBalances(v []string) {
	o.InputTokenBalances = v
}

// GetInputTokenBalancesUsd returns the InputTokenBalancesUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetInputTokenBalancesUsd() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.InputTokenBalancesUsd
}

// GetInputTokenBalancesUsdOk returns a tuple with the InputTokenBalancesUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetInputTokenBalancesUsdOk() ([]string, bool) {
	if o == nil || IsNil(o.InputTokenBalancesUsd) {
		return nil, false
	}
	return o.InputTokenBalancesUsd, true
}

// HasInputTokenBalancesUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasInputTokenBalancesUsd() bool {
	if o != nil && IsNil(o.InputTokenBalancesUsd) {
		return true
	}

	return false
}

// SetInputTokenBalancesUsd gets a reference to the given []string and assigns it to the InputTokenBalancesUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetInputTokenBalancesUsd(v []string) {
	o.InputTokenBalancesUsd = v
}

// GetInputTokenWeights returns the InputTokenWeights field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetInputTokenWeights() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.InputTokenWeights
}

// GetInputTokenWeightsOk returns a tuple with the InputTokenWeights field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetInputTokenWeightsOk() ([]string, bool) {
	if o == nil || IsNil(o.InputTokenWeights) {
		return nil, false
	}
	return o.InputTokenWeights, true
}

// HasInputTokenWeights returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasInputTokenWeights() bool {
	if o != nil && IsNil(o.InputTokenWeights) {
		return true
	}

	return false
}

// SetInputTokenWeights gets a reference to the given []string and assigns it to the InputTokenWeights field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetInputTokenWeights(v []string) {
	o.InputTokenWeights = v
}

// GetStakedOutputTokenAmount returns the StakedOutputTokenAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetStakedOutputTokenAmount() string {
	if o == nil || IsNil(o.StakedOutputTokenAmount.Get()) {
		var ret string
		return ret
	}
	return *o.StakedOutputTokenAmount.Get()
}

// GetStakedOutputTokenAmountOk returns a tuple with the StakedOutputTokenAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetStakedOutputTokenAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StakedOutputTokenAmount.Get(), o.StakedOutputTokenAmount.IsSet()
}

// HasStakedOutputTokenAmount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasStakedOutputTokenAmount() bool {
	if o != nil && o.StakedOutputTokenAmount.IsSet() {
		return true
	}

	return false
}

// SetStakedOutputTokenAmount gets a reference to the given NullableString and assigns it to the StakedOutputTokenAmount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetStakedOutputTokenAmount(v string) {
	o.StakedOutputTokenAmount.Set(&v)
}
// SetStakedOutputTokenAmountNil sets the value for StakedOutputTokenAmount to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetStakedOutputTokenAmountNil() {
	o.StakedOutputTokenAmount.Set(nil)
}

// UnsetStakedOutputTokenAmount ensures that no value is present for StakedOutputTokenAmount, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetStakedOutputTokenAmount() {
	o.StakedOutputTokenAmount.Unset()
}

// GetRewardTokenEmissionsAmount returns the RewardTokenEmissionsAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetRewardTokenEmissionsAmount() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RewardTokenEmissionsAmount
}

// GetRewardTokenEmissionsAmountOk returns a tuple with the RewardTokenEmissionsAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetRewardTokenEmissionsAmountOk() ([]string, bool) {
	if o == nil || IsNil(o.RewardTokenEmissionsAmount) {
		return nil, false
	}
	return o.RewardTokenEmissionsAmount, true
}

// HasRewardTokenEmissionsAmount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasRewardTokenEmissionsAmount() bool {
	if o != nil && IsNil(o.RewardTokenEmissionsAmount) {
		return true
	}

	return false
}

// SetRewardTokenEmissionsAmount gets a reference to the given []string and assigns it to the RewardTokenEmissionsAmount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetRewardTokenEmissionsAmount(v []string) {
	o.RewardTokenEmissionsAmount = v
}

// GetRewardTokenEmissionsUsd returns the RewardTokenEmissionsUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetRewardTokenEmissionsUsd() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RewardTokenEmissionsUsd
}

// GetRewardTokenEmissionsUsdOk returns a tuple with the RewardTokenEmissionsUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetRewardTokenEmissionsUsdOk() ([]string, bool) {
	if o == nil || IsNil(o.RewardTokenEmissionsUsd) {
		return nil, false
	}
	return o.RewardTokenEmissionsUsd, true
}

// HasRewardTokenEmissionsUsd returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasRewardTokenEmissionsUsd() bool {
	if o != nil && IsNil(o.RewardTokenEmissionsUsd) {
		return true
	}

	return false
}

// SetRewardTokenEmissionsUsd gets a reference to the given []string and assigns it to the RewardTokenEmissionsUsd field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetRewardTokenEmissionsUsd(v []string) {
	o.RewardTokenEmissionsUsd = v
}

// GetCumulativeDepositCount returns the CumulativeDepositCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeDepositCount() int32 {
	if o == nil || IsNil(o.CumulativeDepositCount) {
		var ret int32
		return ret
	}
	return *o.CumulativeDepositCount
}

// GetCumulativeDepositCountOk returns a tuple with the CumulativeDepositCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeDepositCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CumulativeDepositCount) {
		return nil, false
	}
	return o.CumulativeDepositCount, true
}

// HasCumulativeDepositCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeDepositCount() bool {
	if o != nil && !IsNil(o.CumulativeDepositCount) {
		return true
	}

	return false
}

// SetCumulativeDepositCount gets a reference to the given int32 and assigns it to the CumulativeDepositCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeDepositCount(v int32) {
	o.CumulativeDepositCount = &v
}

// GetDailyDepositCount returns the DailyDepositCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyDepositCount() int32 {
	if o == nil || IsNil(o.DailyDepositCount) {
		var ret int32
		return ret
	}
	return *o.DailyDepositCount
}

// GetDailyDepositCountOk returns a tuple with the DailyDepositCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyDepositCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DailyDepositCount) {
		return nil, false
	}
	return o.DailyDepositCount, true
}

// HasDailyDepositCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailyDepositCount() bool {
	if o != nil && !IsNil(o.DailyDepositCount) {
		return true
	}

	return false
}

// SetDailyDepositCount gets a reference to the given int32 and assigns it to the DailyDepositCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyDepositCount(v int32) {
	o.DailyDepositCount = &v
}

// GetCumulativeWithdrawCount returns the CumulativeWithdrawCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeWithdrawCount() int32 {
	if o == nil || IsNil(o.CumulativeWithdrawCount) {
		var ret int32
		return ret
	}
	return *o.CumulativeWithdrawCount
}

// GetCumulativeWithdrawCountOk returns a tuple with the CumulativeWithdrawCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeWithdrawCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CumulativeWithdrawCount) {
		return nil, false
	}
	return o.CumulativeWithdrawCount, true
}

// HasCumulativeWithdrawCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeWithdrawCount() bool {
	if o != nil && !IsNil(o.CumulativeWithdrawCount) {
		return true
	}

	return false
}

// SetCumulativeWithdrawCount gets a reference to the given int32 and assigns it to the CumulativeWithdrawCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeWithdrawCount(v int32) {
	o.CumulativeWithdrawCount = &v
}

// GetDailyWithdrawCount returns the DailyWithdrawCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyWithdrawCount() int32 {
	if o == nil || IsNil(o.DailyWithdrawCount) {
		var ret int32
		return ret
	}
	return *o.DailyWithdrawCount
}

// GetDailyWithdrawCountOk returns a tuple with the DailyWithdrawCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailyWithdrawCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DailyWithdrawCount) {
		return nil, false
	}
	return o.DailyWithdrawCount, true
}

// HasDailyWithdrawCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailyWithdrawCount() bool {
	if o != nil && !IsNil(o.DailyWithdrawCount) {
		return true
	}

	return false
}

// SetDailyWithdrawCount gets a reference to the given int32 and assigns it to the DailyWithdrawCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailyWithdrawCount(v int32) {
	o.DailyWithdrawCount = &v
}

// GetCumulativeSwapCount returns the CumulativeSwapCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeSwapCount() int32 {
	if o == nil || IsNil(o.CumulativeSwapCount) {
		var ret int32
		return ret
	}
	return *o.CumulativeSwapCount
}

// GetCumulativeSwapCountOk returns a tuple with the CumulativeSwapCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetCumulativeSwapCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CumulativeSwapCount) {
		return nil, false
	}
	return o.CumulativeSwapCount, true
}

// HasCumulativeSwapCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasCumulativeSwapCount() bool {
	if o != nil && !IsNil(o.CumulativeSwapCount) {
		return true
	}

	return false
}

// SetCumulativeSwapCount gets a reference to the given int32 and assigns it to the CumulativeSwapCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetCumulativeSwapCount(v int32) {
	o.CumulativeSwapCount = &v
}

// GetDailySwapCount returns the DailySwapCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailySwapCount() int32 {
	if o == nil || IsNil(o.DailySwapCount) {
		var ret int32
		return ret
	}
	return *o.DailySwapCount
}

// GetDailySwapCountOk returns a tuple with the DailySwapCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetDailySwapCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DailySwapCount) {
		return nil, false
	}
	return o.DailySwapCount, true
}

// HasDailySwapCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasDailySwapCount() bool {
	if o != nil && !IsNil(o.DailySwapCount) {
		return true
	}

	return false
}

// SetDailySwapCount gets a reference to the given int32 and assigns it to the DailySwapCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetDailySwapCount(v int32) {
	o.DailySwapCount = &v
}

// GetPositionCount returns the PositionCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetPositionCount() int32 {
	if o == nil || IsNil(o.PositionCount) {
		var ret int32
		return ret
	}
	return *o.PositionCount
}

// GetPositionCountOk returns a tuple with the PositionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetPositionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.PositionCount) {
		return nil, false
	}
	return o.PositionCount, true
}

// HasPositionCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasPositionCount() bool {
	if o != nil && !IsNil(o.PositionCount) {
		return true
	}

	return false
}

// SetPositionCount gets a reference to the given int32 and assigns it to the PositionCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetPositionCount(v int32) {
	o.PositionCount = &v
}

// GetOpenPositionCount returns the OpenPositionCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetOpenPositionCount() int32 {
	if o == nil || IsNil(o.OpenPositionCount) {
		var ret int32
		return ret
	}
	return *o.OpenPositionCount
}

// GetOpenPositionCountOk returns a tuple with the OpenPositionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetOpenPositionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenPositionCount) {
		return nil, false
	}
	return o.OpenPositionCount, true
}

// HasOpenPositionCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasOpenPositionCount() bool {
	if o != nil && !IsNil(o.OpenPositionCount) {
		return true
	}

	return false
}

// SetOpenPositionCount gets a reference to the given int32 and assigns it to the OpenPositionCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetOpenPositionCount(v int32) {
	o.OpenPositionCount = &v
}

// GetClosedPositionCount returns the ClosedPositionCount field value if set, zero value otherwise.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetClosedPositionCount() int32 {
	if o == nil || IsNil(o.ClosedPositionCount) {
		var ret int32
		return ret
	}
	return *o.ClosedPositionCount
}

// GetClosedPositionCountOk returns a tuple with the ClosedPositionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetClosedPositionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ClosedPositionCount) {
		return nil, false
	}
	return o.ClosedPositionCount, true
}

// HasClosedPositionCount returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasClosedPositionCount() bool {
	if o != nil && !IsNil(o.ClosedPositionCount) {
		return true
	}

	return false
}

// SetClosedPositionCount gets a reference to the given int32 and assigns it to the ClosedPositionCount field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetClosedPositionCount(v int32) {
	o.ClosedPositionCount = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret string
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableString and assigns it to the Timestamp field.
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTimestamp(v string) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnsetTimestamp() {
	o.Timestamp.Unset()
}

func (o PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EntryTime) {
		toSerialize["entry_time"] = o.EntryTime
	}
	if !IsNil(o.RecvTime) {
		toSerialize["recv_time"] = o.RecvTime
	}
	if !IsNil(o.BlockNumber) {
		toSerialize["block_number"] = o.BlockNumber
	}
	if !IsNil(o.Block) {
		toSerialize["block_"] = o.Block
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.Day) {
		toSerialize["day"] = o.Day
	}
	if o.Protocol.IsSet() {
		toSerialize["protocol"] = o.Protocol.Get()
	}
	if o.Pool.IsSet() {
		toSerialize["pool"] = o.Pool.Get()
	}
	if o.Tick.IsSet() {
		toSerialize["tick"] = o.Tick.Get()
	}
	if o.TotalValueLockedUsd.IsSet() {
		toSerialize["total_value_locked_usd"] = o.TotalValueLockedUsd.Get()
	}
	if o.TotalLiquidity.IsSet() {
		toSerialize["total_liquidity"] = o.TotalLiquidity.Get()
	}
	if o.TotalLiquidityUsd.IsSet() {
		toSerialize["total_liquidity_usd"] = o.TotalLiquidityUsd.Get()
	}
	if o.ActiveLiquidity.IsSet() {
		toSerialize["active_liquidity"] = o.ActiveLiquidity.Get()
	}
	if o.ActiveLiquidityUsd.IsSet() {
		toSerialize["active_liquidity_usd"] = o.ActiveLiquidityUsd.Get()
	}
	if o.UncollectedProtocolSideTokenAmounts != nil {
		toSerialize["uncollected_protocol_side_token_amounts"] = o.UncollectedProtocolSideTokenAmounts
	}
	if o.UncollectedProtocolSideValuesUsd != nil {
		toSerialize["uncollected_protocol_side_values_usd"] = o.UncollectedProtocolSideValuesUsd
	}
	if o.UncollectedSupplySideTokenAmounts != nil {
		toSerialize["uncollected_supply_side_token_amounts"] = o.UncollectedSupplySideTokenAmounts
	}
	if o.UncollectedSupplySideValuesUsd != nil {
		toSerialize["uncollected_supply_side_values_usd"] = o.UncollectedSupplySideValuesUsd
	}
	if o.CumulativeSupplySideRevenueUsd.IsSet() {
		toSerialize["cumulative_supply_side_revenue_usd"] = o.CumulativeSupplySideRevenueUsd.Get()
	}
	if o.DailySupplySideRevenueUsd.IsSet() {
		toSerialize["daily_supply_side_revenue_usd"] = o.DailySupplySideRevenueUsd.Get()
	}
	if o.CumulativeProtocolSideRevenueUsd.IsSet() {
		toSerialize["cumulative_protocol_side_revenue_usd"] = o.CumulativeProtocolSideRevenueUsd.Get()
	}
	if o.DailyProtocolSideRevenueUsd.IsSet() {
		toSerialize["daily_protocol_side_revenue_usd"] = o.DailyProtocolSideRevenueUsd.Get()
	}
	if o.CumulativeTotalRevenueUsd.IsSet() {
		toSerialize["cumulative_total_revenue_usd"] = o.CumulativeTotalRevenueUsd.Get()
	}
	if o.DailyTotalRevenueUsd.IsSet() {
		toSerialize["daily_total_revenue_usd"] = o.DailyTotalRevenueUsd.Get()
	}
	if o.CumulativeVolumeUsd.IsSet() {
		toSerialize["cumulative_volume_usd"] = o.CumulativeVolumeUsd.Get()
	}
	if o.DailyVolumeUsd.IsSet() {
		toSerialize["daily_volume_usd"] = o.DailyVolumeUsd.Get()
	}
	if o.CumulativeVolumeByTokenAmount != nil {
		toSerialize["cumulative_volume_by_token_amount"] = o.CumulativeVolumeByTokenAmount
	}
	if o.DailyVolumeByTokenAmount != nil {
		toSerialize["daily_volume_by_token_amount"] = o.DailyVolumeByTokenAmount
	}
	if o.CumulativeVolumeByTokenUsd != nil {
		toSerialize["cumulative_volume_by_token_usd"] = o.CumulativeVolumeByTokenUsd
	}
	if o.DailyVolumeByTokenUsd != nil {
		toSerialize["daily_volume_by_token_usd"] = o.DailyVolumeByTokenUsd
	}
	if o.InputTokenBalances != nil {
		toSerialize["input_token_balances"] = o.InputTokenBalances
	}
	if o.InputTokenBalancesUsd != nil {
		toSerialize["input_token_balances_usd"] = o.InputTokenBalancesUsd
	}
	if o.InputTokenWeights != nil {
		toSerialize["input_token_weights"] = o.InputTokenWeights
	}
	if o.StakedOutputTokenAmount.IsSet() {
		toSerialize["staked_output_token_amount"] = o.StakedOutputTokenAmount.Get()
	}
	if o.RewardTokenEmissionsAmount != nil {
		toSerialize["reward_token_emissions_amount"] = o.RewardTokenEmissionsAmount
	}
	if o.RewardTokenEmissionsUsd != nil {
		toSerialize["reward_token_emissions_usd"] = o.RewardTokenEmissionsUsd
	}
	if !IsNil(o.CumulativeDepositCount) {
		toSerialize["cumulative_deposit_count"] = o.CumulativeDepositCount
	}
	if !IsNil(o.DailyDepositCount) {
		toSerialize["daily_deposit_count"] = o.DailyDepositCount
	}
	if !IsNil(o.CumulativeWithdrawCount) {
		toSerialize["cumulative_withdraw_count"] = o.CumulativeWithdrawCount
	}
	if !IsNil(o.DailyWithdrawCount) {
		toSerialize["daily_withdraw_count"] = o.DailyWithdrawCount
	}
	if !IsNil(o.CumulativeSwapCount) {
		toSerialize["cumulative_swap_count"] = o.CumulativeSwapCount
	}
	if !IsNil(o.DailySwapCount) {
		toSerialize["daily_swap_count"] = o.DailySwapCount
	}
	if !IsNil(o.PositionCount) {
		toSerialize["position_count"] = o.PositionCount
	}
	if !IsNil(o.OpenPositionCount) {
		toSerialize["open_position_count"] = o.OpenPositionCount
	}
	if !IsNil(o.ClosedPositionCount) {
		toSerialize["closed_position_count"] = o.ClosedPositionCount
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	return toSerialize, nil
}

type NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO struct {
	value *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO
	isSet bool
}

func (v NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) Get() *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO {
	return v.value
}

func (v *NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) Set(val *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) {
	v.value = val
	v.isSet = true
}

func (v NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) IsSet() bool {
	return v.isSet
}

func (v *NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO(val *PANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) *NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO {
	return &NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO{value: val, isSet: true}
}

func (v NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePANCAKESWAPV3ETHEREUMLiquidityPoolDailySnapshotDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


