/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param entryTime 
 * @param recvTime 
 * @param blockNumber Number of block in which entity was recorded.
 * @param blockRange 
 * @param id Account address.
 * @param positionCount Number of positions this account has.
 * @param openPositionCount Number of open positions this account has.
 * @param closedPositionCount Number of closed positions this account has.
 * @param depositCount Number of deposits this account made.
 * @param withdrawCount Number of withdrawals this account made.
 * @param swapCount Number of times this account has traded/swapped.
 */


data class UNISWAPV3ETHEREUMAccountDTO (

    @Json(name = "entry_time")
    val entryTime: java.time.OffsetDateTime? = null,

    @Json(name = "recv_time")
    val recvTime: java.time.OffsetDateTime? = null,

    /* Number of block in which entity was recorded. */
    @Json(name = "block_number")
    val blockNumber: kotlin.Long? = null,

    /*  */
    @Json(name = "block_range")
    val blockRange: kotlin.String? = null,

    /* Account address. */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Number of positions this account has. */
    @Json(name = "position_count")
    val positionCount: kotlin.Int? = null,

    /* Number of open positions this account has. */
    @Json(name = "open_position_count")
    val openPositionCount: kotlin.Int? = null,

    /* Number of closed positions this account has. */
    @Json(name = "closed_position_count")
    val closedPositionCount: kotlin.Int? = null,

    /* Number of deposits this account made. */
    @Json(name = "deposit_count")
    val depositCount: kotlin.Int? = null,

    /* Number of withdrawals this account made. */
    @Json(name = "withdraw_count")
    val withdrawCount: kotlin.Int? = null,

    /* Number of times this account has traded/swapped. */
    @Json(name = "swap_count")
    val swapCount: kotlin.Int? = null

)

