/*
 * On Chain Dapps - REST API
 *
 *  This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             
 *
 * The version of the OpenAPI document: v1
 * Contact: support@coinapi.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CoinAPI.EMS.REST.V1.Model;
using CoinAPI.EMS.REST.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CoinAPI.EMS.REST.V1.Test.Model
{
    /// <summary>
    ///  Class for testing PANCAKESWAPV3ETHEREUMDepositDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PANCAKESWAPV3ETHEREUMDepositDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PANCAKESWAPV3ETHEREUMDepositDTO
        //private PANCAKESWAPV3ETHEREUMDepositDTO instance;

        public PANCAKESWAPV3ETHEREUMDepositDTOTests()
        {
            // TODO uncomment below to create an instance of PANCAKESWAPV3ETHEREUMDepositDTO
            //instance = new PANCAKESWAPV3ETHEREUMDepositDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PANCAKESWAPV3ETHEREUMDepositDTO
        /// </summary>
        [Fact]
        public void PANCAKESWAPV3ETHEREUMDepositDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" PANCAKESWAPV3ETHEREUMDepositDTO
            //Assert.IsType<PANCAKESWAPV3ETHEREUMDepositDTO>(instance);
        }


        /// <summary>
        /// Test the property 'EntryTime'
        /// </summary>
        [Fact]
        public void EntryTimeTest()
        {
            // TODO unit test for the property 'EntryTime'
        }
        /// <summary>
        /// Test the property 'RecvTime'
        /// </summary>
        [Fact]
        public void RecvTimeTest()
        {
            // TODO unit test for the property 'RecvTime'
        }
        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Fact]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }
        /// <summary>
        /// Test the property 'Block'
        /// </summary>
        [Fact]
        public void BlockTest()
        {
            // TODO unit test for the property 'Block'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'LogIndex'
        /// </summary>
        [Fact]
        public void LogIndexTest()
        {
            // TODO unit test for the property 'LogIndex'
        }
        /// <summary>
        /// Test the property 'GasLimit'
        /// </summary>
        [Fact]
        public void GasLimitTest()
        {
            // TODO unit test for the property 'GasLimit'
        }
        /// <summary>
        /// Test the property 'GasUsed'
        /// </summary>
        [Fact]
        public void GasUsedTest()
        {
            // TODO unit test for the property 'GasUsed'
        }
        /// <summary>
        /// Test the property 'GasPrice'
        /// </summary>
        [Fact]
        public void GasPriceTest()
        {
            // TODO unit test for the property 'GasPrice'
        }
        /// <summary>
        /// Test the property 'Protocol'
        /// </summary>
        [Fact]
        public void ProtocolTest()
        {
            // TODO unit test for the property 'Protocol'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Pool'
        /// </summary>
        [Fact]
        public void PoolTest()
        {
            // TODO unit test for the property 'Pool'
        }
        /// <summary>
        /// Test the property 'TickLower'
        /// </summary>
        [Fact]
        public void TickLowerTest()
        {
            // TODO unit test for the property 'TickLower'
        }
        /// <summary>
        /// Test the property 'TickUpper'
        /// </summary>
        [Fact]
        public void TickUpperTest()
        {
            // TODO unit test for the property 'TickUpper'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Liquidity'
        /// </summary>
        [Fact]
        public void LiquidityTest()
        {
            // TODO unit test for the property 'Liquidity'
        }
        /// <summary>
        /// Test the property 'InputTokens'
        /// </summary>
        [Fact]
        public void InputTokensTest()
        {
            // TODO unit test for the property 'InputTokens'
        }
        /// <summary>
        /// Test the property 'InputTokenAmounts'
        /// </summary>
        [Fact]
        public void InputTokenAmountsTest()
        {
            // TODO unit test for the property 'InputTokenAmounts'
        }
        /// <summary>
        /// Test the property 'ReserveAmounts'
        /// </summary>
        [Fact]
        public void ReserveAmountsTest()
        {
            // TODO unit test for the property 'ReserveAmounts'
        }
        /// <summary>
        /// Test the property 'AmountUsd'
        /// </summary>
        [Fact]
        public void AmountUsdTest()
        {
            // TODO unit test for the property 'AmountUsd'
        }
        /// <summary>
        /// Test the property 'BlockRange'
        /// </summary>
        [Fact]
        public void BlockRangeTest()
        {
            // TODO unit test for the property 'BlockRange'
        }

    }

}
