# coding: utf-8

"""
    On Chain Dapps - REST API

     This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                               # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@coinapi.io
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.dapps_sushiswap_bundles_current.get import SushiswapBundlesCurrent
from openapi_client.paths.dapps_sushiswap_burns_current.get import SushiswapBurnsCurrent
from openapi_client.paths.dapps_sushiswap_day_data_current.get import SushiswapDayDataCurrent
from openapi_client.paths.dapps_sushiswap_factories_current.get import SushiswapFactoriesCurrent
from openapi_client.paths.dapps_sushiswap_hour_data_current.get import SushiswapHourDataCurrent
from openapi_client.paths.dapps_sushiswap_liquidity_position_snapshots_current.get import SushiswapLiquidityPositionSnapshotsCurrent
from openapi_client.paths.dapps_sushiswap_liquidity_positions_current.get import SushiswapLiquidityPositionsCurrent
from openapi_client.paths.dapps_sushiswap_mints_current.get import SushiswapMintsCurrent
from openapi_client.paths.dapps_sushiswap_pair_day_data_current.get import SushiswapPairDayDataCurrent
from openapi_client.paths.dapps_sushiswap_pair_hour_data_current.get import SushiswapPairHourDataCurrent
from openapi_client.paths.dapps_sushiswap_pairs_current.get import SushiswapPairsCurrent
from openapi_client.paths.dapps_sushiswap_swaps_current.get import SushiswapSwapsCurrent
from openapi_client.paths.dapps_sushiswap_token_day_data_current.get import SushiswapTokenDayDataCurrent
from openapi_client.paths.dapps_sushiswap_tokens_current.get import SushiswapTokensCurrent
from openapi_client.paths.dapps_sushiswap_transactions_current.get import SushiswapTransactionsCurrent
from openapi_client.paths.dapps_sushiswap_users_current.get import SushiswapUsersCurrent


class SushiswapApi(
    SushiswapBundlesCurrent,
    SushiswapBurnsCurrent,
    SushiswapDayDataCurrent,
    SushiswapFactoriesCurrent,
    SushiswapHourDataCurrent,
    SushiswapLiquidityPositionSnapshotsCurrent,
    SushiswapLiquidityPositionsCurrent,
    SushiswapMintsCurrent,
    SushiswapPairDayDataCurrent,
    SushiswapPairHourDataCurrent,
    SushiswapPairsCurrent,
    SushiswapSwapsCurrent,
    SushiswapTokenDayDataCurrent,
    SushiswapTokensCurrent,
    SushiswapTransactionsCurrent,
    SushiswapUsersCurrent,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
