/*
 * On Chain Dapps - REST API
 *
 *  This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             
 *
 * The version of the OpenAPI document: v1
 * Contact: support@coinapi.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CoinAPI.EMS.REST.V1.Api;
using CoinAPI.EMS.REST.V1.Model;
using CoinAPI.EMS.REST.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CoinAPI.EMS.REST.V1.Test
{
    /// <summary>
    ///  Class for testing UNISWAPV2ETHEREUMSwapDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UNISWAPV2ETHEREUMSwapDTOTests
    {
        // TODO uncomment below to declare an instance variable for UNISWAPV2ETHEREUMSwapDTO
        //private UNISWAPV2ETHEREUMSwapDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UNISWAPV2ETHEREUMSwapDTO
            //instance = new UNISWAPV2ETHEREUMSwapDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UNISWAPV2ETHEREUMSwapDTO
        /// </summary>
        [Test]
        public void UNISWAPV2ETHEREUMSwapDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UNISWAPV2ETHEREUMSwapDTO
            //Assert.IsInstanceOf(typeof(UNISWAPV2ETHEREUMSwapDTO), instance);
        }


        /// <summary>
        /// Test the property 'EntryTime'
        /// </summary>
        [Test]
        public void EntryTimeTest()
        {
            // TODO unit test for the property 'EntryTime'
        }
        /// <summary>
        /// Test the property 'RecvTime'
        /// </summary>
        [Test]
        public void RecvTimeTest()
        {
            // TODO unit test for the property 'RecvTime'
        }
        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Test]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }
        /// <summary>
        /// Test the property 'Block'
        /// </summary>
        [Test]
        public void BlockTest()
        {
            // TODO unit test for the property 'Block'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'LogIndex'
        /// </summary>
        [Test]
        public void LogIndexTest()
        {
            // TODO unit test for the property 'LogIndex'
        }
        /// <summary>
        /// Test the property 'Protocol'
        /// </summary>
        [Test]
        public void ProtocolTest()
        {
            // TODO unit test for the property 'Protocol'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'TokenIn'
        /// </summary>
        [Test]
        public void TokenInTest()
        {
            // TODO unit test for the property 'TokenIn'
        }
        /// <summary>
        /// Test the property 'AmountIn'
        /// </summary>
        [Test]
        public void AmountInTest()
        {
            // TODO unit test for the property 'AmountIn'
        }
        /// <summary>
        /// Test the property 'AmountInUsd'
        /// </summary>
        [Test]
        public void AmountInUsdTest()
        {
            // TODO unit test for the property 'AmountInUsd'
        }
        /// <summary>
        /// Test the property 'TokenOut'
        /// </summary>
        [Test]
        public void TokenOutTest()
        {
            // TODO unit test for the property 'TokenOut'
        }
        /// <summary>
        /// Test the property 'AmountOut'
        /// </summary>
        [Test]
        public void AmountOutTest()
        {
            // TODO unit test for the property 'AmountOut'
        }
        /// <summary>
        /// Test the property 'AmountOutUsd'
        /// </summary>
        [Test]
        public void AmountOutUsdTest()
        {
            // TODO unit test for the property 'AmountOutUsd'
        }
        /// <summary>
        /// Test the property 'ReserveAmounts'
        /// </summary>
        [Test]
        public void ReserveAmountsTest()
        {
            // TODO unit test for the property 'ReserveAmounts'
        }
        /// <summary>
        /// Test the property 'Pool'
        /// </summary>
        [Test]
        public void PoolTest()
        {
            // TODO unit test for the property 'Pool'
        }
        /// <summary>
        /// Test the property 'BlockRange'
        /// </summary>
        [Test]
        public void BlockRangeTest()
        {
            // TODO unit test for the property 'BlockRange'
        }
        /// <summary>
        /// Test the property 'PoolId'
        /// </summary>
        [Test]
        public void PoolIdTest()
        {
            // TODO unit test for the property 'PoolId'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Test]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'EvaluatedPrice'
        /// </summary>
        [Test]
        public void EvaluatedPriceTest()
        {
            // TODO unit test for the property 'EvaluatedPrice'
        }
        /// <summary>
        /// Test the property 'EvaluatedAmount'
        /// </summary>
        [Test]
        public void EvaluatedAmountTest()
        {
            // TODO unit test for the property 'EvaluatedAmount'
        }
        /// <summary>
        /// Test the property 'EvaluatedAggressor'
        /// </summary>
        [Test]
        public void EvaluatedAggressorTest()
        {
            // TODO unit test for the property 'EvaluatedAggressor'
        }

    }

}
