/**
 * On Chain Dapps - REST API
 *  This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             
 *
 * The version of the OpenAPI document: v1
 * Contact: support@coinapi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CRYPTOPUNKSMarketPlaceDTO model module.
 * @module model/CRYPTOPUNKSMarketPlaceDTO
 * @version v1
 */
class CRYPTOPUNKSMarketPlaceDTO {
    /**
     * Constructs a new <code>CRYPTOPUNKSMarketPlaceDTO</code>.
     * @alias module:model/CRYPTOPUNKSMarketPlaceDTO
     */
    constructor() { 
        
        CRYPTOPUNKSMarketPlaceDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CRYPTOPUNKSMarketPlaceDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CRYPTOPUNKSMarketPlaceDTO} obj Optional instance to populate.
     * @return {module:model/CRYPTOPUNKSMarketPlaceDTO} The populated <code>CRYPTOPUNKSMarketPlaceDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CRYPTOPUNKSMarketPlaceDTO();

            if (data.hasOwnProperty('entry_time')) {
                obj['entry_time'] = ApiClient.convertToType(data['entry_time'], 'Date');
            }
            if (data.hasOwnProperty('recv_time')) {
                obj['recv_time'] = ApiClient.convertToType(data['recv_time'], 'Date');
            }
            if (data.hasOwnProperty('block_number')) {
                obj['block_number'] = ApiClient.convertToType(data['block_number'], 'Number');
            }
            if (data.hasOwnProperty('vid')) {
                obj['vid'] = ApiClient.convertToType(data['vid'], 'Number');
            }
            if (data.hasOwnProperty('block_range')) {
                obj['block_range'] = ApiClient.convertToType(data['block_range'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'String');
            }
            if (data.hasOwnProperty('subgraph_version')) {
                obj['subgraph_version'] = ApiClient.convertToType(data['subgraph_version'], 'String');
            }
            if (data.hasOwnProperty('methodology_version')) {
                obj['methodology_version'] = ApiClient.convertToType(data['methodology_version'], 'String');
            }
            if (data.hasOwnProperty('collection_count')) {
                obj['collection_count'] = ApiClient.convertToType(data['collection_count'], 'Number');
            }
            if (data.hasOwnProperty('trade_count')) {
                obj['trade_count'] = ApiClient.convertToType(data['trade_count'], 'Number');
            }
            if (data.hasOwnProperty('cumulative_trade_volume_eth')) {
                obj['cumulative_trade_volume_eth'] = ApiClient.convertToType(data['cumulative_trade_volume_eth'], 'String');
            }
            if (data.hasOwnProperty('marketplace_revenue_eth')) {
                obj['marketplace_revenue_eth'] = ApiClient.convertToType(data['marketplace_revenue_eth'], 'String');
            }
            if (data.hasOwnProperty('creator_revenue_eth')) {
                obj['creator_revenue_eth'] = ApiClient.convertToType(data['creator_revenue_eth'], 'String');
            }
            if (data.hasOwnProperty('total_revenue_eth')) {
                obj['total_revenue_eth'] = ApiClient.convertToType(data['total_revenue_eth'], 'String');
            }
            if (data.hasOwnProperty('cumulative_unique_traders')) {
                obj['cumulative_unique_traders'] = ApiClient.convertToType(data['cumulative_unique_traders'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CRYPTOPUNKSMarketPlaceDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CRYPTOPUNKSMarketPlaceDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['block_range'] && !(typeof data['block_range'] === 'string' || data['block_range'] instanceof String)) {
            throw new Error("Expected the field `block_range` to be a primitive type in the JSON string but got " + data['block_range']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['schema_version'] && !(typeof data['schema_version'] === 'string' || data['schema_version'] instanceof String)) {
            throw new Error("Expected the field `schema_version` to be a primitive type in the JSON string but got " + data['schema_version']);
        }
        // ensure the json data is a string
        if (data['subgraph_version'] && !(typeof data['subgraph_version'] === 'string' || data['subgraph_version'] instanceof String)) {
            throw new Error("Expected the field `subgraph_version` to be a primitive type in the JSON string but got " + data['subgraph_version']);
        }
        // ensure the json data is a string
        if (data['methodology_version'] && !(typeof data['methodology_version'] === 'string' || data['methodology_version'] instanceof String)) {
            throw new Error("Expected the field `methodology_version` to be a primitive type in the JSON string but got " + data['methodology_version']);
        }
        // ensure the json data is a string
        if (data['cumulative_trade_volume_eth'] && !(typeof data['cumulative_trade_volume_eth'] === 'string' || data['cumulative_trade_volume_eth'] instanceof String)) {
            throw new Error("Expected the field `cumulative_trade_volume_eth` to be a primitive type in the JSON string but got " + data['cumulative_trade_volume_eth']);
        }
        // ensure the json data is a string
        if (data['marketplace_revenue_eth'] && !(typeof data['marketplace_revenue_eth'] === 'string' || data['marketplace_revenue_eth'] instanceof String)) {
            throw new Error("Expected the field `marketplace_revenue_eth` to be a primitive type in the JSON string but got " + data['marketplace_revenue_eth']);
        }
        // ensure the json data is a string
        if (data['creator_revenue_eth'] && !(typeof data['creator_revenue_eth'] === 'string' || data['creator_revenue_eth'] instanceof String)) {
            throw new Error("Expected the field `creator_revenue_eth` to be a primitive type in the JSON string but got " + data['creator_revenue_eth']);
        }
        // ensure the json data is a string
        if (data['total_revenue_eth'] && !(typeof data['total_revenue_eth'] === 'string' || data['total_revenue_eth'] instanceof String)) {
            throw new Error("Expected the field `total_revenue_eth` to be a primitive type in the JSON string but got " + data['total_revenue_eth']);
        }

        return true;
    }


}



/**
 * @member {Date} entry_time
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['entry_time'] = undefined;

/**
 * @member {Date} recv_time
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['recv_time'] = undefined;

/**
 * Number of block in which entity was recorded.
 * @member {Number} block_number
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['block_number'] = undefined;

/**
 * 
 * @member {Number} vid
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['vid'] = undefined;

/**
 * 
 * @member {String} block_range
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['block_range'] = undefined;

/**
 * 
 * @member {String} id
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['id'] = undefined;

/**
 * 
 * @member {String} name
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['name'] = undefined;

/**
 * 
 * @member {String} slug
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['slug'] = undefined;

/**
 * 
 * @member {String} schema_version
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['schema_version'] = undefined;

/**
 * 
 * @member {String} subgraph_version
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['subgraph_version'] = undefined;

/**
 * 
 * @member {String} methodology_version
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['methodology_version'] = undefined;

/**
 * 
 * @member {Number} collection_count
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['collection_count'] = undefined;

/**
 * 
 * @member {Number} trade_count
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['trade_count'] = undefined;

/**
 * 
 * @member {String} cumulative_trade_volume_eth
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['cumulative_trade_volume_eth'] = undefined;

/**
 * 
 * @member {String} marketplace_revenue_eth
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['marketplace_revenue_eth'] = undefined;

/**
 * 
 * @member {String} creator_revenue_eth
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['creator_revenue_eth'] = undefined;

/**
 * 
 * @member {String} total_revenue_eth
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['total_revenue_eth'] = undefined;

/**
 * 
 * @member {Number} cumulative_unique_traders
 */
CRYPTOPUNKSMarketPlaceDTO.prototype['cumulative_unique_traders'] = undefined;






export default CRYPTOPUNKSMarketPlaceDTO;

