/**
 * On Chain Dapps - REST API
 *  This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             
 *
 * The version of the OpenAPI document: v1
 * Contact: support@coinapi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionsETradeAggressiveSide from './TransactionsETradeAggressiveSide';

/**
 * The UNISWAPV2ETHEREUMSwapDTO model module.
 * @module model/UNISWAPV2ETHEREUMSwapDTO
 * @version v1
 */
class UNISWAPV2ETHEREUMSwapDTO {
    /**
     * Constructs a new <code>UNISWAPV2ETHEREUMSwapDTO</code>.
     * Trade (swap) event which occurred in a pool.
     * @alias module:model/UNISWAPV2ETHEREUMSwapDTO
     */
    constructor() { 
        
        UNISWAPV2ETHEREUMSwapDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UNISWAPV2ETHEREUMSwapDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UNISWAPV2ETHEREUMSwapDTO} obj Optional instance to populate.
     * @return {module:model/UNISWAPV2ETHEREUMSwapDTO} The populated <code>UNISWAPV2ETHEREUMSwapDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UNISWAPV2ETHEREUMSwapDTO();

            if (data.hasOwnProperty('entry_time')) {
                obj['entry_time'] = ApiClient.convertToType(data['entry_time'], 'Date');
            }
            if (data.hasOwnProperty('recv_time')) {
                obj['recv_time'] = ApiClient.convertToType(data['recv_time'], 'Date');
            }
            if (data.hasOwnProperty('block_number')) {
                obj['block_number'] = ApiClient.convertToType(data['block_number'], 'String');
            }
            if (data.hasOwnProperty('block_')) {
                obj['block_'] = ApiClient.convertToType(data['block_'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('log_index')) {
                obj['log_index'] = ApiClient.convertToType(data['log_index'], 'Number');
            }
            if (data.hasOwnProperty('protocol')) {
                obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
            if (data.hasOwnProperty('token_in')) {
                obj['token_in'] = ApiClient.convertToType(data['token_in'], 'String');
            }
            if (data.hasOwnProperty('amount_in')) {
                obj['amount_in'] = ApiClient.convertToType(data['amount_in'], 'String');
            }
            if (data.hasOwnProperty('amount_in_usd')) {
                obj['amount_in_usd'] = ApiClient.convertToType(data['amount_in_usd'], 'String');
            }
            if (data.hasOwnProperty('token_out')) {
                obj['token_out'] = ApiClient.convertToType(data['token_out'], 'String');
            }
            if (data.hasOwnProperty('amount_out')) {
                obj['amount_out'] = ApiClient.convertToType(data['amount_out'], 'String');
            }
            if (data.hasOwnProperty('amount_out_usd')) {
                obj['amount_out_usd'] = ApiClient.convertToType(data['amount_out_usd'], 'String');
            }
            if (data.hasOwnProperty('reserve_amounts')) {
                obj['reserve_amounts'] = ApiClient.convertToType(data['reserve_amounts'], ['String']);
            }
            if (data.hasOwnProperty('pool')) {
                obj['pool'] = ApiClient.convertToType(data['pool'], 'String');
            }
            if (data.hasOwnProperty('block_range')) {
                obj['block_range'] = ApiClient.convertToType(data['block_range'], 'String');
            }
            if (data.hasOwnProperty('pool_id')) {
                obj['pool_id'] = ApiClient.convertToType(data['pool_id'], 'String');
            }
            if (data.hasOwnProperty('transaction_id')) {
                obj['transaction_id'] = ApiClient.convertToType(data['transaction_id'], 'String');
            }
            if (data.hasOwnProperty('evaluated_price')) {
                obj['evaluated_price'] = ApiClient.convertToType(data['evaluated_price'], 'Number');
            }
            if (data.hasOwnProperty('evaluated_amount')) {
                obj['evaluated_amount'] = ApiClient.convertToType(data['evaluated_amount'], 'Number');
            }
            if (data.hasOwnProperty('evaluated_aggressor')) {
                obj['evaluated_aggressor'] = TransactionsETradeAggressiveSide.constructFromObject(data['evaluated_aggressor']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UNISWAPV2ETHEREUMSwapDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UNISWAPV2ETHEREUMSwapDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['block_number'] && !(typeof data['block_number'] === 'string' || data['block_number'] instanceof String)) {
            throw new Error("Expected the field `block_number` to be a primitive type in the JSON string but got " + data['block_number']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['hash'] && !(typeof data['hash'] === 'string' || data['hash'] instanceof String)) {
            throw new Error("Expected the field `hash` to be a primitive type in the JSON string but got " + data['hash']);
        }
        // ensure the json data is a string
        if (data['protocol'] && !(typeof data['protocol'] === 'string' || data['protocol'] instanceof String)) {
            throw new Error("Expected the field `protocol` to be a primitive type in the JSON string but got " + data['protocol']);
        }
        // ensure the json data is a string
        if (data['to'] && !(typeof data['to'] === 'string' || data['to'] instanceof String)) {
            throw new Error("Expected the field `to` to be a primitive type in the JSON string but got " + data['to']);
        }
        // ensure the json data is a string
        if (data['from'] && !(typeof data['from'] === 'string' || data['from'] instanceof String)) {
            throw new Error("Expected the field `from` to be a primitive type in the JSON string but got " + data['from']);
        }
        // ensure the json data is a string
        if (data['timestamp'] && !(typeof data['timestamp'] === 'string' || data['timestamp'] instanceof String)) {
            throw new Error("Expected the field `timestamp` to be a primitive type in the JSON string but got " + data['timestamp']);
        }
        // ensure the json data is a string
        if (data['token_in'] && !(typeof data['token_in'] === 'string' || data['token_in'] instanceof String)) {
            throw new Error("Expected the field `token_in` to be a primitive type in the JSON string but got " + data['token_in']);
        }
        // ensure the json data is a string
        if (data['amount_in'] && !(typeof data['amount_in'] === 'string' || data['amount_in'] instanceof String)) {
            throw new Error("Expected the field `amount_in` to be a primitive type in the JSON string but got " + data['amount_in']);
        }
        // ensure the json data is a string
        if (data['amount_in_usd'] && !(typeof data['amount_in_usd'] === 'string' || data['amount_in_usd'] instanceof String)) {
            throw new Error("Expected the field `amount_in_usd` to be a primitive type in the JSON string but got " + data['amount_in_usd']);
        }
        // ensure the json data is a string
        if (data['token_out'] && !(typeof data['token_out'] === 'string' || data['token_out'] instanceof String)) {
            throw new Error("Expected the field `token_out` to be a primitive type in the JSON string but got " + data['token_out']);
        }
        // ensure the json data is a string
        if (data['amount_out'] && !(typeof data['amount_out'] === 'string' || data['amount_out'] instanceof String)) {
            throw new Error("Expected the field `amount_out` to be a primitive type in the JSON string but got " + data['amount_out']);
        }
        // ensure the json data is a string
        if (data['amount_out_usd'] && !(typeof data['amount_out_usd'] === 'string' || data['amount_out_usd'] instanceof String)) {
            throw new Error("Expected the field `amount_out_usd` to be a primitive type in the JSON string but got " + data['amount_out_usd']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['reserve_amounts'])) {
            throw new Error("Expected the field `reserve_amounts` to be an array in the JSON data but got " + data['reserve_amounts']);
        }
        // ensure the json data is a string
        if (data['pool'] && !(typeof data['pool'] === 'string' || data['pool'] instanceof String)) {
            throw new Error("Expected the field `pool` to be a primitive type in the JSON string but got " + data['pool']);
        }
        // ensure the json data is a string
        if (data['block_range'] && !(typeof data['block_range'] === 'string' || data['block_range'] instanceof String)) {
            throw new Error("Expected the field `block_range` to be a primitive type in the JSON string but got " + data['block_range']);
        }
        // ensure the json data is a string
        if (data['pool_id'] && !(typeof data['pool_id'] === 'string' || data['pool_id'] instanceof String)) {
            throw new Error("Expected the field `pool_id` to be a primitive type in the JSON string but got " + data['pool_id']);
        }
        // ensure the json data is a string
        if (data['transaction_id'] && !(typeof data['transaction_id'] === 'string' || data['transaction_id'] instanceof String)) {
            throw new Error("Expected the field `transaction_id` to be a primitive type in the JSON string but got " + data['transaction_id']);
        }

        return true;
    }


}



/**
 * @member {Date} entry_time
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['entry_time'] = undefined;

/**
 * @member {Date} recv_time
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['recv_time'] = undefined;

/**
 * Block number of this event
 * @member {String} block_number
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['block_number'] = undefined;

/**
 * 
 * @member {Number} block_
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['block_'] = undefined;

/**
 * swap-{ Transaction hash }-{ Log index }
 * @member {String} id
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['id'] = undefined;

/**
 * Transaction hash of the transaction that emitted this event
 * @member {String} hash
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['hash'] = undefined;

/**
 * Event log index. For transactions that don't emit event, create arbitrary index starting from 0
 * @member {Number} log_index
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['log_index'] = undefined;

/**
 * The protocol this transaction belongs to
 * @member {String} protocol
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['protocol'] = undefined;

/**
 * Address that received the tokens
 * @member {String} to
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['to'] = undefined;

/**
 * Address that sent the tokens
 * @member {String} from
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['from'] = undefined;

/**
 * Timestamp of this event
 * @member {String} timestamp
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['timestamp'] = undefined;

/**
 * Token deposited into pool
 * @member {String} token_in
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['token_in'] = undefined;

/**
 * Amount of token deposited into pool in native units
 * @member {String} amount_in
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['amount_in'] = undefined;

/**
 * Amount of token deposited into pool in USD
 * @member {String} amount_in_usd
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['amount_in_usd'] = undefined;

/**
 * Token withdrawn from pool
 * @member {String} token_out
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['token_out'] = undefined;

/**
 * Amount of token withdrawn from pool in native units
 * @member {String} amount_out
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['amount_out'] = undefined;

/**
 * Amount of token withdrawn from pool in USD
 * @member {String} amount_out_usd
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['amount_out_usd'] = undefined;

/**
 * Amount of input tokens in the liquidity pool
 * @member {Array.<String>} reserve_amounts
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['reserve_amounts'] = undefined;

/**
 * The pool involving this transaction
 * @member {String} pool
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['pool'] = undefined;

/**
 * @member {String} block_range
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['block_range'] = undefined;

/**
 * @member {String} pool_id
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['pool_id'] = undefined;

/**
 * @member {String} transaction_id
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['transaction_id'] = undefined;

/**
 * @member {Number} evaluated_price
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['evaluated_price'] = undefined;

/**
 * @member {Number} evaluated_amount
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['evaluated_amount'] = undefined;

/**
 * @member {module:model/TransactionsETradeAggressiveSide} evaluated_aggressor
 */
UNISWAPV2ETHEREUMSwapDTO.prototype['evaluated_aggressor'] = undefined;






export default UNISWAPV2ETHEREUMSwapDTO;

