-module(openapi_pancakeswap_v3_ethereum_dex_amm_protocol_dto).

-export([encode/1]).

-export_type([openapi_pancakeswap_v3_ethereum_dex_amm_protocol_dto/0]).

-type openapi_pancakeswap_v3_ethereum_dex_amm_protocol_dto() ::
    #{ 'entry_time' => openapi_date_time:openapi_date_time(),
       'recv_time' => openapi_date_time:openapi_date_time(),
       'block_number' => integer(),
       'block_range' => binary(),
       'id' => binary(),
       'name' => binary(),
       'slug' => binary(),
       'schema_version' => binary(),
       'subgraph_version' => binary(),
       'methodology_version' => binary(),
       'total_value_locked_usd' => binary(),
       'total_liquidity_usd' => binary(),
       'active_liquidity_usd' => binary(),
       'uncollected_protocol_side_value_usd' => binary(),
       'uncollected_supply_side_value_usd' => binary(),
       'protocol_controlled_value_usd' => binary(),
       'cumulative_volume_usd' => binary(),
       'cumulative_supply_side_revenue_usd' => binary(),
       'cumulative_protocol_side_revenue_usd' => binary(),
       'cumulative_total_revenue_usd' => binary(),
       'cumulative_unique_users' => integer(),
       'cumulative_unique_l_ps' => integer(),
       'cumulative_unique_traders' => integer(),
       'total_pool_count' => integer(),
       'open_position_count' => integer(),
       'cumulative_position_count' => integer(),
       'last_snapshot_day_id' => integer(),
       'last_update_timestamp' => binary(),
       'last_update_block_number' => binary(),
       'regenesis' => boolean()
     }.

encode(#{ 'entry_time' := EntryTime,
          'recv_time' := RecvTime,
          'block_number' := BlockNumber,
          'block_range' := BlockRange,
          'id' := Id,
          'name' := Name,
          'slug' := Slug,
          'schema_version' := SchemaVersion,
          'subgraph_version' := SubgraphVersion,
          'methodology_version' := MethodologyVersion,
          'total_value_locked_usd' := TotalValueLockedUsd,
          'total_liquidity_usd' := TotalLiquidityUsd,
          'active_liquidity_usd' := ActiveLiquidityUsd,
          'uncollected_protocol_side_value_usd' := UncollectedProtocolSideValueUsd,
          'uncollected_supply_side_value_usd' := UncollectedSupplySideValueUsd,
          'protocol_controlled_value_usd' := ProtocolControlledValueUsd,
          'cumulative_volume_usd' := CumulativeVolumeUsd,
          'cumulative_supply_side_revenue_usd' := CumulativeSupplySideRevenueUsd,
          'cumulative_protocol_side_revenue_usd' := CumulativeProtocolSideRevenueUsd,
          'cumulative_total_revenue_usd' := CumulativeTotalRevenueUsd,
          'cumulative_unique_users' := CumulativeUniqueUsers,
          'cumulative_unique_l_ps' := CumulativeUniqueLPs,
          'cumulative_unique_traders' := CumulativeUniqueTraders,
          'total_pool_count' := TotalPoolCount,
          'open_position_count' := OpenPositionCount,
          'cumulative_position_count' := CumulativePositionCount,
          'last_snapshot_day_id' := LastSnapshotDayId,
          'last_update_timestamp' := LastUpdateTimestamp,
          'last_update_block_number' := LastUpdateBlockNumber,
          'regenesis' := Regenesis
        }) ->
    #{ 'entry_time' => EntryTime,
       'recv_time' => RecvTime,
       'block_number' => BlockNumber,
       'block_range' => BlockRange,
       'id' => Id,
       'name' => Name,
       'slug' => Slug,
       'schema_version' => SchemaVersion,
       'subgraph_version' => SubgraphVersion,
       'methodology_version' => MethodologyVersion,
       'total_value_locked_usd' => TotalValueLockedUsd,
       'total_liquidity_usd' => TotalLiquidityUsd,
       'active_liquidity_usd' => ActiveLiquidityUsd,
       'uncollected_protocol_side_value_usd' => UncollectedProtocolSideValueUsd,
       'uncollected_supply_side_value_usd' => UncollectedSupplySideValueUsd,
       'protocol_controlled_value_usd' => ProtocolControlledValueUsd,
       'cumulative_volume_usd' => CumulativeVolumeUsd,
       'cumulative_supply_side_revenue_usd' => CumulativeSupplySideRevenueUsd,
       'cumulative_protocol_side_revenue_usd' => CumulativeProtocolSideRevenueUsd,
       'cumulative_total_revenue_usd' => CumulativeTotalRevenueUsd,
       'cumulative_unique_users' => CumulativeUniqueUsers,
       'cumulative_unique_l_ps' => CumulativeUniqueLPs,
       'cumulative_unique_traders' => CumulativeUniqueTraders,
       'total_pool_count' => TotalPoolCount,
       'open_position_count' => OpenPositionCount,
       'cumulative_position_count' => CumulativePositionCount,
       'last_snapshot_day_id' => LastSnapshotDayId,
       'last_update_timestamp' => LastUpdateTimestamp,
       'last_update_block_number' => LastUpdateBlockNumber,
       'regenesis' => Regenesis
     }.
