-module(openapi_sushiswap_v3_ethereum_deposit_dto).

-export([encode/1]).

-export_type([openapi_sushiswap_v3_ethereum_deposit_dto/0]).

-type openapi_sushiswap_v3_ethereum_deposit_dto() ::
    #{ 'entry_time' => openapi_date_time:openapi_date_time(),
       'recv_time' => openapi_date_time:openapi_date_time(),
       'block_number' => integer(),
       'block_' => integer(),
       'id' => binary(),
       'hash' => binary(),
       'nonce' => binary(),
       'log_index' => integer(),
       'gas_limit' => binary(),
       'gas_used' => binary(),
       'gas_price' => binary(),
       'protocol' => binary(),
       'account' => binary(),
       'position' => binary(),
       'pool' => binary(),
       'tick_lower' => binary(),
       'tick_upper' => binary(),
       'timestamp' => binary(),
       'liquidity' => binary(),
       'input_tokens' => list(),
       'input_token_amounts' => list(),
       'reserve_amounts' => list(),
       'amount_usd' => binary(),
       'block_range' => binary()
     }.

encode(#{ 'entry_time' := EntryTime,
          'recv_time' := RecvTime,
          'block_number' := BlockNumber,
          'block_' := Block,
          'id' := Id,
          'hash' := Hash,
          'nonce' := Nonce,
          'log_index' := LogIndex,
          'gas_limit' := GasLimit,
          'gas_used' := GasUsed,
          'gas_price' := GasPrice,
          'protocol' := Protocol,
          'account' := Account,
          'position' := Position,
          'pool' := Pool,
          'tick_lower' := TickLower,
          'tick_upper' := TickUpper,
          'timestamp' := Timestamp,
          'liquidity' := Liquidity,
          'input_tokens' := InputTokens,
          'input_token_amounts' := InputTokenAmounts,
          'reserve_amounts' := ReserveAmounts,
          'amount_usd' := AmountUsd,
          'block_range' := BlockRange
        }) ->
    #{ 'entry_time' => EntryTime,
       'recv_time' => RecvTime,
       'block_number' => BlockNumber,
       'block_' => Block,
       'id' => Id,
       'hash' => Hash,
       'nonce' => Nonce,
       'log_index' => LogIndex,
       'gas_limit' => GasLimit,
       'gas_used' => GasUsed,
       'gas_price' => GasPrice,
       'protocol' => Protocol,
       'account' => Account,
       'position' => Position,
       'pool' => Pool,
       'tick_lower' => TickLower,
       'tick_upper' => TickUpper,
       'timestamp' => Timestamp,
       'liquidity' => Liquidity,
       'input_tokens' => InputTokens,
       'input_token_amounts' => InputTokenAmounts,
       'reserve_amounts' => ReserveAmounts,
       'amount_usd' => AmountUsd,
       'block_range' => BlockRange
     }.
