/**
 * On Chain Dapps - REST API
 *  This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             
 *
 * The version of the OpenAPI document: v1
 * Contact: support@coinapi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import org.openapitools.client.core.ApiModel

case class MasterChefStakingPoolDTO (
  entryTime: Option[OffsetDateTime] = None,
  recvTime: Option[OffsetDateTime] = None,
  /* Number of block in which entity was recorded. */
  blockNumber: Option[Long] = None,
  /*  */
  blockRange: Option[String] = None,
  /* (masterchef type) - (pid referenced in the masterchef contract) */
  id: Option[String] = None,
  /* Staking pool to which this rewarder is associated */
  poolAddress: Option[String] = None,
  /* Allocation point of this MasterChef Staking pool */
  poolAllocPoint: Option[String] = None,
  /* Reward Multiplier for a given staking pool */
  multiplier: Option[String] = None,
  /* Last block where rewards were given out */
  lastRewardBlock: Option[String] = None,
  /* Optional address of a bonus rewarder, to give additional tokens on top of masterchefs */
  rewarder: Option[String] = None
) extends ApiModel

